/**
 * Cloud-init user data template for bootstrapping a provisioned VM.
 *
 * Generates a shell script that:
 * 1. Installs Docker (official convenience script)
 * 2. Installs Node.js 22 (NodeSource)
 * 3. Installs ClawHQ globally via npm
 * 4. Runs `clawhq install` to scaffold ~/.clawhq
 * 5. Starts the agent with `clawhq up`
 *
 * The script is passed as cloud-init user data and runs as root on first boot.
 */

export interface CloudInitOptions {
  /** Human-readable instance name (used in agent identity). */
  readonly name: string;
}

/**
 * Generate a cloud-init user data script for bootstrapping a ClawHQ agent.
 *
 * Returns a bash script string suitable for cloud-init user data.
 */
export function generateCloudInit(options: CloudInitOptions): string {
  const { name } = options;

  // Escape single quotes in the name for safe shell embedding
  const safeName = name.replace(/'/g, "'\\''");

  return `#!/bin/bash
set -euo pipefail

# ── ClawHQ cloud-init bootstrap ─────────────────────────────────────────────
# Instance: ${safeName}
# Generated by ClawHQ provisioning engine

export DEBIAN_FRONTEND=noninteractive

# ── 1. System updates ───────────────────────────────────────────────────────

apt-get update -qq
apt-get upgrade -y -qq

# ── 2. Install Docker ───────────────────────────────────────────────────────

curl -fsSL https://get.docker.com | sh
systemctl enable docker
systemctl start docker

# ── 3. Install Node.js 22 ───────────────────────────────────────────────────

curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y -qq nodejs

# ── 4. Install ClawHQ ───────────────────────────────────────────────────────

npm install -g clawhq

# ── 5. Bootstrap agent ──────────────────────────────────────────────────────

clawhq install

# ── 6. Signal ready ─────────────────────────────────────────────────────────

# Write a sentinel file that the health poller checks for
mkdir -p /var/lib/clawhq
echo '{"status":"ready","name":"${safeName}","bootedAt":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > /var/lib/clawhq/boot-status.json
`;
}
