/**
 * Cloud-init user data template for bootstrapping a provisioned VM.
 *
 * Generates an idempotent shell script that:
 * 1. Installs Docker CE (official convenience script)
 * 2. Installs Node.js 22 (NodeSource)
 * 3. Installs ClawHQ globally via npm
 * 4. Runs `clawhq install` to scaffold ~/.clawhq
 * 5. Optionally runs `clawhq init` with blueprint + trust mode
 * 6. Starts the agent with `clawhq up`
 * 7. Signals readiness via sentinel file (+ optional health callback URL)
 *
 * Every step is guarded by sentinel files for idempotency — safe to re-run on reboot.
 * The script is passed as cloud-init user data and runs as root on first boot.
 */

/** Trust modes for cloud-init provisioned agents. */
export type CloudInitTrustMode = "paranoid" | "zero-trust" | "managed";

export interface CloudInitOptions {
  /** Human-readable instance name (used in agent identity). */
  readonly name: string;
  /** Blueprint to use for agent configuration (e.g. "replace-chatgpt-plus"). */
  readonly blueprint?: string;
  /** Gateway auth token for the provisioned agent. */
  readonly gatewayToken?: string;
  /** Trust mode for the provisioned agent. */
  readonly trustMode?: CloudInitTrustMode;
  /** Deploy directory on the remote VM (default: ~/.clawhq). */
  readonly deployDir?: string;
  /** URL to POST health status to when agent is ready. */
  readonly healthCallbackUrl?: string;
}

// ── Sentinel paths ──────────────────────────────────────────────────────────

const SENTINEL_DIR = "/var/lib/clawhq/sentinels";

function sentinel(step: string): string {
  return `${SENTINEL_DIR}/${step}.done`;
}

/**
 * Generate a cloud-init user data script for bootstrapping a ClawHQ agent.
 *
 * Returns a bash script string suitable for cloud-init user data.
 * Every step is guarded by sentinel files — safe to re-run on reboot.
 */
export function generateCloudInit(options: CloudInitOptions): string {
  const { name, blueprint, gatewayToken, trustMode, deployDir, healthCallbackUrl } = options;

  // Escape single quotes for safe shell embedding
  const safeName = name.replace(/'/g, "'\\''");
  const safeBlueprint = blueprint?.replace(/'/g, "'\\''") ?? "";
  const safeToken = gatewayToken?.replace(/'/g, "'\\''") ?? "";
  const safeDeployDir = deployDir?.replace(/'/g, "'\\''") ?? "";
  const safeCallbackUrl = healthCallbackUrl?.replace(/'/g, "'\\''") ?? "";

  const initArgs: string[] = [];
  if (safeBlueprint) initArgs.push(`--blueprint '${safeBlueprint}'`);
  if (safeDeployDir) initArgs.push(`-d '${safeDeployDir}'`);

  const upArgs: string[] = [];
  if (safeToken) upArgs.push(`--token '${safeToken}'`);
  if (safeDeployDir) upArgs.push(`-d '${safeDeployDir}'`);
  if (trustMode === "paranoid") upArgs.push("--air-gap");

  return `#!/bin/bash
set -euo pipefail

# ── ClawHQ cloud-init bootstrap ─────────────────────────────────────────────
# Instance: ${safeName}
# Blueprint: ${safeBlueprint || "(default)"}
# Trust mode: ${trustMode ?? "zero-trust"}
# Generated by ClawHQ provisioning engine

export DEBIAN_FRONTEND=noninteractive
mkdir -p ${SENTINEL_DIR}

# ── 1. System updates ───────────────────────────────────────────────────────

if [ ! -f '${sentinel("apt-update")}' ]; then
  apt-get update -qq
  apt-get upgrade -y -qq
  touch '${sentinel("apt-update")}'
fi

# ── 2. Install Docker ───────────────────────────────────────────────────────

if [ ! -f '${sentinel("docker")}' ]; then
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  touch '${sentinel("docker")}'
fi

# ── 3. Install Node.js 22 ───────────────────────────────────────────────────

if [ ! -f '${sentinel("nodejs")}' ]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y -qq nodejs
  touch '${sentinel("nodejs")}'
fi

# ── 4. Install ClawHQ ───────────────────────────────────────────────────────

if [ ! -f '${sentinel("clawhq")}' ]; then
  npm install -g clawhq
  touch '${sentinel("clawhq")}'
fi

# ── 5. Bootstrap agent ──────────────────────────────────────────────────────

if [ ! -f '${sentinel("install")}' ]; then
  clawhq install
  touch '${sentinel("install")}'
fi

${safeBlueprint ? `if [ ! -f '${sentinel("init")}' ]; then
  clawhq init ${initArgs.join(" ")}
  touch '${sentinel("init")}'
fi
` : ""}
# ── 6. Start agent ──────────────────────────────────────────────────────────

if [ ! -f '${sentinel("up")}' ]; then
  clawhq up ${upArgs.join(" ")} || true
  touch '${sentinel("up")}'
fi

# ── 7. Signal ready ─────────────────────────────────────────────────────────

mkdir -p /var/lib/clawhq
cat > /var/lib/clawhq/boot-status.json <<EOJSON
{"status":"ready","name":"${safeName}","trustMode":"${trustMode ?? "zero-trust"}","bootedAt":"$(date -u +%Y-%m-%dT%H:%M:%SZ)"}
EOJSON

${safeCallbackUrl ? `# POST health signal to provisioning engine
curl -fsSL -X POST '${safeCallbackUrl}' \\
  -H 'Content-Type: application/json' \\
  -d @/var/lib/clawhq/boot-status.json || true
` : ""}
`;
}
