/**
 * Snapshot boot-time config injection — minimal cloud-init for snapshot-booted VMs.
 *
 * Unlike the full cloud-init (cloud-init.ts), this script assumes Docker, Node.js,
 * and ClawHQ are already installed in the snapshot. It only:
 * 1. Injects blueprint config + gateway token via metadata/user-data
 * 2. Runs `clawhq init` with the blueprint (if provided)
 * 3. Starts the agent with `clawhq up`
 * 4. Signals readiness
 *
 * This is the key to sub-60s provisioning — boot from golden image, inject config, go.
 */

import type { CloudInitTrustMode } from "./cloud-init.js";

export interface SnapshotInitOptions {
  /** Human-readable instance name. */
  readonly name: string;
  /** Blueprint to configure the agent with (optional). */
  readonly blueprint?: string;
  /** Gateway auth token. */
  readonly gatewayToken?: string;
  /** Trust mode for the provisioned agent. */
  readonly trustMode?: CloudInitTrustMode;
  /** Deploy directory on the remote VM (default: ~/.clawhq). */
  readonly deployDir?: string;
  /** URL to POST health status to when agent is ready. */
  readonly healthCallbackUrl?: string;
}

/**
 * Generate a minimal cloud-init script for snapshot-booted VMs.
 *
 * Skips all install steps (Docker, Node.js, ClawHQ, `clawhq install`) because
 * they're already baked into the snapshot. Only injects blueprint config and starts.
 */
export function generateSnapshotInit(options: SnapshotInitOptions): string {
  const { name, blueprint, gatewayToken, trustMode, deployDir, healthCallbackUrl } = options;

  // Escape single quotes for safe shell embedding
  const safeName = name.replace(/'/g, "'\\''");
  const safeBlueprint = blueprint?.replace(/'/g, "'\\''") ?? "";
  const safeToken = gatewayToken?.replace(/'/g, "'\\''") ?? "";
  const safeDeployDir = deployDir?.replace(/'/g, "'\\''") ?? "";
  const safeCallbackUrl = healthCallbackUrl?.replace(/'/g, "'\\''") ?? "";

  const initArgs: string[] = [];
  if (safeBlueprint) initArgs.push(`--blueprint '${safeBlueprint}'`);
  if (safeDeployDir) initArgs.push(`-d '${safeDeployDir}'`);

  const upArgs: string[] = [];
  if (safeToken) upArgs.push(`--token '${safeToken}'`);
  if (safeDeployDir) upArgs.push(`-d '${safeDeployDir}'`);
  if (trustMode === "paranoid") upArgs.push("--air-gap");

  return `#!/bin/bash
set -euo pipefail

# ── ClawHQ snapshot boot-time config injection ────────────────────────────────
# Instance: ${safeName}
# Blueprint: ${safeBlueprint || "(default)"}
# Trust mode: ${trustMode ?? "zero-trust"}
# Boot mode: snapshot (sub-60s path)
# Generated by ClawHQ provisioning engine

export DEBIAN_FRONTEND=noninteractive

# ── 1. Configure agent (blueprint + tokens) ─────────────────────────────────

${safeBlueprint ? `clawhq init ${initArgs.join(" ")} || true` : "# No blueprint specified — using snapshot default config"}

# ── 2. Start agent ───────────────────────────────────────────────────────────

clawhq up ${upArgs.join(" ")} || true

# ── 3. Signal ready ──────────────────────────────────────────────────────────

mkdir -p /var/lib/clawhq
cat > /var/lib/clawhq/boot-status.json <<EOJSON
{"status":"ready","name":"${safeName}","trustMode":"${trustMode ?? "zero-trust"}","bootMode":"snapshot","bootedAt":"$(date -u +%Y-%m-%dT%H:%M:%SZ)"}
EOJSON

${safeCallbackUrl ? `# POST health signal to provisioning engine
curl -fsSL -X POST '${safeCallbackUrl}' \\
  -H 'Content-Type: application/json' \\
  -d @/var/lib/clawhq/boot-status.json || true
` : ""}`;
}
