#!/usr/bin/env python3
"""email-fastmail.py — JMAP backend for FastMail JMAP email backend.

Stdlib only (urllib.request, json). Generated by ClawHQ. Stdlib Python only, no deps.
Errors to stderr, data to stdout.
"""

import argparse
import datetime
import json
import os
import sys
import tempfile
import time
import urllib.error
import urllib.request
from html.parser import HTMLParser

# ClawWall: import sanitizer for untrusted email content
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from sanitize import clawwall as _clawwall, clawwall_json as _clawwall_json, clawwall_egress as _clawwall_egress, is_trusted_sender as _is_trusted
    def _cw(text, sender=None, **kw):
        """Sanitize text through ClawWall, with trusted-source awareness.

        Args:
            sender: Email address of the sender. If from a trusted domain
                    (SEC-010), Tier 2 heuristics are skipped to avoid
                    quarantining legitimate business emails.
        """
        if not text:
            return text
        if sender and 'trusted' not in kw:
            kw['trusted'] = _is_trusted(sender)
        return _clawwall(str(text), source="email", log=True, **kw)
    def _cw_json(data, fields, sender=None, **kw):
        if sender and 'trusted' not in kw:
            kw['trusted'] = _is_trusted(sender)
        return _clawwall_json(data, fields, source="email", log=True, **kw)
except ImportError:
    def _cw(text, sender=None, **kw):
        return text  # graceful degradation
    def _cw_json(data, fields, sender=None, **kw):
        return data
    def _clawwall_egress(text, source='outbound'):
        return (True, [])  # graceful degradation
    def _is_trusted(email_addr):
        return False

# ── Constants ──────────────────────────────────────────────────────────────────

_CRED_PROXY_URL = os.environ.get("CRED_PROXY_URL", "").rstrip("/")
JMAP_WELL_KNOWN = f"{_CRED_PROXY_URL}/fastmail/.well-known/jmap" if _CRED_PROXY_URL else "https://api.fastmail.com/.well-known/jmap"
STATE_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "email-state.json")
AUDIT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "email-audit.jsonl")
CONTACTS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "contacts.json")
DELEGATED_RULES_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "delegated-send-rules.json")
MEDIA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "media", "email")
SESSION_TTL = 3600  # 60 minutes
BURST_WINDOW = 300  # 5 minutes
BURST_LIMIT = 10    # max sends per 5-min window (blocks runaway loops, not real usage)
TIMEOUT = 30

# ── HTML Stripping ─────────────────────────────────────────────────────────────

class _HTMLStripper(HTMLParser):
    def __init__(self):
        super().__init__()
        self._parts = []
        self._skip = False

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self._skip = True
        elif tag in ("br", "p", "div", "tr", "li"):
            self._parts.append("\n")

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self._skip = False

    def handle_data(self, data):
        if not self._skip:
            self._parts.append(data)

    def get_text(self):
        return "".join(self._parts).strip()


def strip_html(html):
    s = _HTMLStripper()
    s.feed(html)
    return s.get_text()

# ── State Management ───────────────────────────────────────────────────────────

def _load_state():
    try:
        with open(STATE_FILE, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _save_state(state):
    d = os.path.dirname(STATE_FILE)
    fd, tmp = tempfile.mkstemp(dir=d, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(state, f, indent=2, ensure_ascii=False)
        os.replace(tmp, STATE_FILE)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _load_contacts():
    try:
        with open(CONTACTS_FILE, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {"contacts": []}


def _is_known_contact(email, contacts):
    email_lower = email.lower()
    for c in contacts.get("contacts", []):
        if c.get("email", "").lower() == email_lower:
            return True, c.get("context", "")
    return False, ""


def _load_delegated_rules():
    try:
        with open(DELEGATED_RULES_FILE, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {"categories": {}}


def _validate_delegated(category, action, subject=""):
    """Validate a delegated send against approved categories.

    Returns (ok: bool, reason: str).
    """
    rules = _load_delegated_rules()
    cats = rules.get("categories", {})
    if category not in cats:
        return False, f"Unknown delegated category: {category}"
    cat = cats[category]
    allowed = cat.get("allowed_actions", [])
    if not allowed:
        return False, f"Category '{category}' is disabled"
    if action not in allowed:
        return False, f"Action '{action}' not allowed for category '{category}' (allowed: {allowed})"
    return True, "ok"


def _audit_log(action, **kwargs):
    entry = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "action": action,
        **kwargs,
    }
    with open(AUDIT_FILE, "a") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

# ── JMAP Session ───────────────────────────────────────────────────────────────

def _get_token():
    # Auth injected by credential proxy (SEC-022) — return dummy for API compat
    if not _CRED_PROXY_URL:
        print("Error: CRED_PROXY_URL not set", file=sys.stderr)
        sys.exit(1)
    return "proxy"


def _rewrite_url(url):
    """Rewrite FastMail absolute URLs to route through credential proxy."""
    if not _CRED_PROXY_URL:
        return url
    url = url.replace("https://api.fastmail.com", f"{_CRED_PROXY_URL}/fastmail")
    url = url.replace("https://www.fastmailusercontent.com", f"{_CRED_PROXY_URL}/fastmail-dl")
    return url


def _jmap_request(url, token, data=None, method="GET"):
    url = _rewrite_url(url)
    headers = {
        "Content-Type": "application/json",
    }
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    resp = urllib.request.urlopen(req, timeout=TIMEOUT)
    return json.loads(resp.read().decode())


def _get_session(token, force=False):
    state = _load_state()
    cached = state.get("session")
    if not force and cached:
        if time.time() - cached.get("fetched_at", 0) < SESSION_TTL:
            return cached

    try:
        sess = _jmap_request(JMAP_WELL_KNOWN, token)
    except urllib.error.HTTPError as e:
        if e.code in (401, 403):
            print("Error: FastMail API token invalid or expired", file=sys.stderr)
            sys.exit(1)
        raise

    account_id = sess.get("primaryAccounts", {}).get("urn:ietf:params:jmap:mail")
    if not account_id:
        print("Error: No mail account found in JMAP session", file=sys.stderr)
        sys.exit(1)

    api_url = sess.get("apiUrl")
    download_url = sess.get("downloadUrl")

    # Fetch identity
    identity_id = None
    try:
        id_resp = _jmap_request(api_url, token, {
            "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:submission"],
            "methodCalls": [["Identity/get", {"accountId": account_id}, "id0"]],
        }, method="POST")
        identities = id_resp["methodResponses"][0][1].get("list", [])
        if identities:
            identity_id = identities[0]["id"]
    except Exception as e:
        print(f"Warning: Could not fetch identity: {e}", file=sys.stderr)

    cached = {
        "accountId": account_id,
        "apiUrl": api_url,
        "downloadUrl": download_url,
        "identityId": identity_id,
        "fetched_at": time.time(),
    }
    state["session"] = cached
    _save_state(state)
    return cached


def _api_call(session, token, method_calls, retries=1):
    data = {
        "using": [
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:mail",
            "urn:ietf:params:jmap:submission",
        ],
        "methodCalls": method_calls,
    }
    try:
        resp = _jmap_request(session["apiUrl"], token, data, method="POST")
    except urllib.error.HTTPError as e:
        if e.code in (401, 404) and retries > 0:
            session = _get_session(token, force=True)
            return _api_call(session, token, method_calls, retries=retries - 1)
        raise

    # Check for errors in method responses
    for mr in resp.get("methodResponses", []):
        if mr[0] == "error":
            print(f"JMAP error: {mr[1]}", file=sys.stderr)
    return resp


def _get_mailbox_id(session, token, role):
    """Get mailbox ID by role (inbox, archive, drafts, sent, trash, junk)."""
    state = _load_state()
    cache_key = f"mailbox_{role}"
    cached = state.get(cache_key)
    if cached:
        return cached

    resp = _api_call(session, token, [
        ["Mailbox/query", {
            "accountId": session["accountId"],
            "filter": {"role": role},
        }, "mq0"],
        ["Mailbox/get", {
            "accountId": session["accountId"],
            "#ids": {"resultOf": "mq0", "name": "Mailbox/query", "path": "/ids"},
        }, "mg0"],
    ])

    mailboxes = resp["methodResponses"][1][1].get("list", [])
    if mailboxes:
        mid = mailboxes[0]["id"]
        state[cache_key] = mid
        _save_state(state)
        return mid
    return None


def _get_mailbox_id_by_name(session, token, name):
    """Get mailbox ID by name."""
    resp = _api_call(session, token, [
        ["Mailbox/get", {
            "accountId": session["accountId"],
        }, "mg0"],
    ])
    for mb in resp["methodResponses"][0][1].get("list", []):
        if mb.get("name") == name:
            return mb["id"]
    return None


def _ensure_mailbox(session, token, name):
    """Ensure a mailbox exists, create if missing. Returns mailbox ID."""
    mid = _get_mailbox_id_by_name(session, token, name)
    if mid:
        return mid

    resp = _api_call(session, token, [
        ["Mailbox/set", {
            "accountId": session["accountId"],
            "create": {
                "new": {"name": name},
            },
        }, "ms0"],
    ])
    created = resp["methodResponses"][0][1].get("created", {})
    if "new" in created:
        return created["new"]["id"]
    print(f"Error: Could not create mailbox '{name}'", file=sys.stderr)
    sys.exit(1)

# ── Rate Limiting ──────────────────────────────────────────────────────────────
# Burst rate limiter: blocks if >BURST_LIMIT sends in BURST_WINDOW seconds.
# Catches runaway loops without capping legitimate daily volume.

def _check_send_rate():
    state = _load_state()
    now = time.time()
    timestamps = state.get("send_timestamps", [])
    # Prune old entries outside the window
    timestamps = [t for t in timestamps if now - t < BURST_WINDOW]
    if len(timestamps) >= BURST_LIMIT:
        print(f"Error: Send rate limit hit ({BURST_LIMIT} sends in {BURST_WINDOW // 60} min). "
              f"Wait a few minutes — this prevents runaway loops.", file=sys.stderr)
        sys.exit(1)


def _record_send():
    state = _load_state()
    now = time.time()
    timestamps = state.get("send_timestamps", [])
    timestamps = [t for t in timestamps if now - t < BURST_WINDOW]
    timestamps.append(now)
    state["send_timestamps"] = timestamps
    _save_state(state)

# ── Email Properties ───────────────────────────────────────────────────────────

TRIAGE_PROPERTIES = [
    "id", "threadId", "from", "replyTo", "to", "cc", "subject",
    "receivedAt", "preview", "size", "hasAttachment", "keywords",
    "mailboxIds", "inReplyTo",
    "header:list-id:asText", "header:List-Unsubscribe",
]


def _format_addr(addr):
    if not addr:
        return None
    if isinstance(addr, list):
        return [{"name": a.get("name", ""), "email": a.get("email", "")} for a in addr]
    return {"name": addr.get("name", ""), "email": addr.get("email", "")}


def _format_triage(emails, contacts, mailbox_map=None, thread_counts=None):
    result = []
    for e in emails:
        from_addr = (e.get("from") or [{}])[0]
        from_email = from_addr.get("email", "")
        known, ctx = _is_known_contact(from_email, contacts)

        # Determine folder name from mailboxIds
        folder = "INBOX"
        if mailbox_map and e.get("mailboxIds"):
            for mid in e["mailboxIds"]:
                if mid in mailbox_map:
                    folder = mailbox_map[mid]
                    break

        # isReply: check inReplyTo header, not $answered keyword
        in_reply_to = e.get("inReplyTo")
        is_reply = bool(in_reply_to and len(in_reply_to) > 0)

        thread_id = e.get("threadId")
        thread_size = (thread_counts or {}).get(thread_id)

        item = {
            "id": e.get("id"),
            "threadId": thread_id,
            "from": _format_addr(from_addr),
            "replyTo": _format_addr((e.get("replyTo") or [None])[0]),
            "to": _format_addr(e.get("to") or []),
            "cc": _format_addr(e.get("cc") or []),
            "subject": _cw(e.get("subject", ""), sender=from_email),
            "date": e.get("receivedAt", ""),
            "preview": _cw(e.get("preview", ""), sender=from_email),
            "size": e.get("size", 0),
            "hasAttachments": e.get("hasAttachment", False),
            "threadSize": thread_size,
            "isReply": is_reply,
            "folder": folder,
            "listId": e.get("header:list-id:asText"),
            "unsubscribeUrl": e.get("header:List-Unsubscribe"),
            "knownContact": known,
            "contactContext": ctx if known else None,
        }
        result.append(item)
    return result

# ── Commands ───────────────────────────────────────────────────────────────────

def cmd_triage(args):
    token = _get_token()
    session = _get_session(token)
    inbox_id = _get_mailbox_id(session, token, "inbox")
    contacts = _load_contacts()

    limit = args.limit or 50

    method_calls = [
        ["Email/query", {
            "accountId": session["accountId"],
            "filter": {
                "inMailbox": inbox_id,
                "notKeyword": "$seen",
            },
            "sort": [{"property": "receivedAt", "isAscending": False}],
            "limit": limit,
        }, "eq0"],
        ["Email/get", {
            "accountId": session["accountId"],
            "#ids": {"resultOf": "eq0", "name": "Email/query", "path": "/ids"},
            "properties": TRIAGE_PROPERTIES,
            "fetchTextBodyValues": True,
        }, "eg0"],
    ]

    resp = _api_call(session, token, method_calls)

    if args.count:
        total = resp["methodResponses"][0][1].get("total", 0)
        print(total)
        return

    emails = resp["methodResponses"][1][1].get("list", [])

    # Fetch thread sizes for context
    thread_counts = {}
    thread_ids = list({e["threadId"] for e in emails if e.get("threadId")})
    if thread_ids:
        t_resp = _api_call(session, token, [
            ["Thread/get", {
                "accountId": session["accountId"],
                "ids": thread_ids,
            }, "tg0"],
        ])
        for t in t_resp["methodResponses"][0][1].get("list", []):
            thread_counts[t["id"]] = len(t.get("emailIds", []))

    result = _format_triage(emails, contacts, thread_counts=thread_counts)
    print(json.dumps(result, indent=2, ensure_ascii=False))


def cmd_inbox(args):
    token = _get_token()
    session = _get_session(token)
    inbox_id = _get_mailbox_id(session, token, "inbox")

    resp = _api_call(session, token, [
        ["Email/query", {
            "accountId": session["accountId"],
            "filter": {"inMailbox": inbox_id, "notKeyword": "$seen"},
            "sort": [{"property": "receivedAt", "isAscending": False}],
            "limit": 50,
        }, "eq0"],
        ["Email/get", {
            "accountId": session["accountId"],
            "#ids": {"resultOf": "eq0", "name": "Email/query", "path": "/ids"},
            "properties": ["id", "from", "subject", "receivedAt", "preview", "hasAttachment"],
        }, "eg0"],
    ])

    emails = resp["methodResponses"][1][1].get("list", [])
    if not emails:
        print("No unread emails.")
        return

    for i, e in enumerate(emails, 1):
        from_addr = (e.get("from") or [{}])[0]
        sender = from_addr.get("email", "")
        name = _cw(from_addr.get("name") or from_addr.get("email", "unknown"), sender=sender)
        subj = _cw(e.get("subject", "(no subject)"), sender=sender)
        date = e.get("receivedAt", "")[:16].replace("T", " ")
        att = " 📎" if e.get("hasAttachment") else ""
        print(f"{i}. [{e['id']}] {name} — {subj}")
        print(f"   {date}{att}")
        if e.get("preview"):
            print(f"   {_cw(e['preview'][:100], sender=sender)}")
        print()


def cmd_all(args):
    token = _get_token()
    session = _get_session(token)
    inbox_id = _get_mailbox_id(session, token, "inbox")
    limit = args.limit or 50

    resp = _api_call(session, token, [
        ["Email/query", {
            "accountId": session["accountId"],
            "filter": {"inMailbox": inbox_id},
            "sort": [{"property": "receivedAt", "isAscending": False}],
            "limit": limit,
        }, "eq0"],
        ["Email/get", {
            "accountId": session["accountId"],
            "#ids": {"resultOf": "eq0", "name": "Email/query", "path": "/ids"},
            "properties": ["id", "from", "subject", "receivedAt", "preview", "hasAttachment", "keywords"],
        }, "eg0"],
    ])

    emails = resp["methodResponses"][1][1].get("list", [])
    if not emails:
        print("No emails.")
        return

    for i, e in enumerate(emails, 1):
        from_addr = (e.get("from") or [{}])[0]
        sender = from_addr.get("email", "")
        name = _cw(from_addr.get("name") or from_addr.get("email", "unknown"), sender=sender)
        subj = _cw(e.get("subject", "(no subject)"), sender=sender)
        date = e.get("receivedAt", "")[:16].replace("T", " ")
        read = "✓" if e.get("keywords", {}).get("$seen") else "•"
        att = " 📎" if e.get("hasAttachment") else ""
        print(f"{read} {i}. [{e['id']}] {name} — {subj}")
        print(f"   {date}{att}")
        print()


def cmd_read(args):
    token = _get_token()
    session = _get_session(token)

    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["id", "from", "to", "cc", "subject", "receivedAt", "textBody", "htmlBody", "bodyValues", "attachments"],
            "fetchTextBodyValues": True,
            "fetchHTMLBodyValues": True,
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    e = emails[0]
    from_addr = (e.get("from") or [{}])[0]
    sender = from_addr.get("email", "")
    print(f"From: {_cw(from_addr.get('name', ''), sender=sender)} <{sender}>")
    to_addrs = e.get("to") or []
    to_str = ", ".join(f"{_cw(a.get('name', ''), sender=sender)} <{a.get('email', '')}>" for a in to_addrs)
    print(f"To: {to_str}")
    if e.get("cc"):
        cc_addrs = e["cc"]
        cc_str = ", ".join(f"{_cw(a.get('name', ''), sender=sender)} <{a.get('email', '')}>" for a in cc_addrs)
        print(f"Cc: {cc_str}")
    print(f"Subject: {_cw(e.get('subject', ''), sender=sender)}")
    print(f"Date: {e.get('receivedAt', '')}")
    print(f"ID: {e['id']}")
    print("---")

    body_values = e.get("bodyValues", {})
    text_parts = e.get("textBody") or []
    html_parts = e.get("htmlBody") or []

    body = ""
    for part in text_parts:
        part_id = part.get("partId")
        if part_id and part_id in body_values:
            body += body_values[part_id].get("value", "")

    if not body.strip():
        for part in html_parts:
            part_id = part.get("partId")
            if part_id and part_id in body_values:
                body += strip_html(body_values[part_id].get("value", ""))

    # ClawWall: sanitize email body (biggest attack surface)
    print(_cw(body, sender=sender, quarantine=True))


def cmd_thread(args):
    token = _get_token()
    session = _get_session(token)
    last = args.last or 5

    # First get the email to find its threadId
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["threadId"],
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    thread_id = emails[0]["threadId"]

    # Get thread emails
    resp = _api_call(session, token, [
        ["Thread/get", {
            "accountId": session["accountId"],
            "ids": [thread_id],
        }, "tg0"],
    ])

    threads = resp["methodResponses"][0][1].get("list", [])
    if not threads:
        print("Error: Thread not found", file=sys.stderr)
        sys.exit(1)

    email_ids = threads[0].get("emailIds", [])
    # Take last N
    email_ids = email_ids[-last:]

    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": email_ids,
            "properties": ["id", "from", "subject", "receivedAt", "textBody", "htmlBody", "bodyValues"],
            "fetchTextBodyValues": True,
            "fetchHTMLBodyValues": True,
        }, "eg0"],
    ])

    thread_emails = resp["methodResponses"][0][1].get("list", [])
    # Sort by date
    thread_emails.sort(key=lambda x: x.get("receivedAt", ""))

    print(f"Thread: {len(email_ids)} messages (showing last {last})")
    print("=" * 60)
    for e in thread_emails:
        from_addr = (e.get("from") or [{}])[0]
        sender = from_addr.get("email", "")
        print(f"\nFrom: {_cw(from_addr.get('name', ''), sender=sender)} <{sender}>")
        print(f"Date: {e.get('receivedAt', '')}")
        print(f"Subject: {_cw(e.get('subject', ''), sender=sender)}")
        print(f"ID: {e['id']}")
        print("---")

        body_values = e.get("bodyValues", {})
        text_parts = e.get("textBody") or []
        html_parts = e.get("htmlBody") or []

        body = ""
        for part in text_parts:
            part_id = part.get("partId")
            if part_id and part_id in body_values:
                body += body_values[part_id].get("value", "")
        if not body.strip():
            for part in html_parts:
                part_id = part.get("partId")
                if part_id and part_id in body_values:
                    body += strip_html(body_values[part_id].get("value", ""))
        print(_cw(body, sender=sender, quarantine=True))
        print("-" * 60)


def cmd_search(args):
    token = _get_token()
    session = _get_session(token)

    filt = {}
    if args.query:
        filt["text"] = args.query
    if args.from_addr:
        filt["from"] = args.from_addr
    if args.subject:
        filt["subject"] = args.subject
    if args.since:
        filt["after"] = args.since + "T00:00:00Z"
    if args.has_attachment:
        filt["hasAttachment"] = True

    limit = args.limit or 50

    resp = _api_call(session, token, [
        ["Email/query", {
            "accountId": session["accountId"],
            "filter": filt,
            "sort": [{"property": "receivedAt", "isAscending": False}],
            "limit": limit,
        }, "eq0"],
        ["Email/get", {
            "accountId": session["accountId"],
            "#ids": {"resultOf": "eq0", "name": "Email/query", "path": "/ids"},
            "properties": ["id", "from", "subject", "receivedAt", "preview", "hasAttachment"],
        }, "eg0"],
    ])

    emails = resp["methodResponses"][1][1].get("list", [])
    if not emails:
        print("No results.")
        return

    for i, e in enumerate(emails, 1):
        from_addr = (e.get("from") or [{}])[0]
        sender = from_addr.get("email", "")
        name = _cw(from_addr.get("name") or from_addr.get("email", "unknown"), sender=sender)
        subj = _cw(e.get("subject", "(no subject)"), sender=sender)
        date = e.get("receivedAt", "")[:16].replace("T", " ")
        att = " 📎" if e.get("hasAttachment") else ""
        print(f"{i}. [{e['id']}] {name} — {subj}")
        print(f"   {date}{att}")
        if e.get("preview"):
            print(f"   {_cw(e['preview'][:100], sender=sender)}")
        print()


def cmd_folders(args):
    token = _get_token()
    session = _get_session(token)

    resp = _api_call(session, token, [
        ["Mailbox/get", {
            "accountId": session["accountId"],
        }, "mg0"],
    ])

    mailboxes = resp["methodResponses"][0][1].get("list", [])
    mailboxes.sort(key=lambda m: m.get("sortOrder", 0))

    for mb in mailboxes:
        role = f" ({mb['role']})" if mb.get("role") else ""
        total = mb.get("totalEmails", 0)
        unread = mb.get("unreadEmails", 0)
        unread_str = f" [{unread} unread]" if unread else ""
        print(f"  {mb['name']}{role} — {total} emails{unread_str}  [{mb['id']}]")


def cmd_attachments(args):
    token = _get_token()
    session = _get_session(token)

    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["id", "subject", "attachments"],
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    e = emails[0]
    attachments = e.get("attachments") or []
    if not attachments:
        print("No attachments.")
        return

    print(f"Attachments for: {e.get('subject', '(no subject)')}")
    for att in attachments:
        size = att.get("size", 0)
        size_str = f"{size / 1024:.1f} KB" if size < 1048576 else f"{size / 1048576:.1f} MB"
        print(f"  [{att.get('partId', '?')}] {att.get('name', 'unnamed')} ({att.get('type', '?')}, {size_str})")


def cmd_download(args):
    token = _get_token()
    session = _get_session(token)

    # Get blob info
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["attachments"],
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    attachment = None
    for att in emails[0].get("attachments") or []:
        if att.get("partId") == args.part_id:
            attachment = att
            break

    if not attachment:
        print(f"Error: Attachment {args.part_id} not found", file=sys.stderr)
        sys.exit(1)

    blob_id = attachment["blobId"]
    filename = attachment.get("name", f"attachment-{args.part_id}")

    # Build download URL
    download_url = session["downloadUrl"]
    download_url = download_url.replace("{accountId}", session["accountId"])
    download_url = download_url.replace("{blobId}", blob_id)
    download_url = download_url.replace("{name}", urllib.request.quote(filename))
    download_url = download_url.replace("{type}", attachment.get("type", "application/octet-stream"))

    os.makedirs(MEDIA_DIR, exist_ok=True)
    filepath = os.path.join(MEDIA_DIR, filename)

    headers = {"Authorization": f"Bearer {token}"}
    req = urllib.request.Request(download_url, headers=headers)
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        with open(filepath, "wb") as f:
            f.write(resp.read())

    print(f"Downloaded: {filepath}")


# ── Write Operations ───────────────────────────────────────────────────────────

def cmd_mark_read(args):
    if args.dry_run:
        print(f"[DRY RUN] Would mark as read: {args.ids}")
        return

    token = _get_token()
    session = _get_session(token)

    updates = {}
    for eid in args.ids:
        updates[eid] = {"keywords/$seen": True}
        _audit_log("mark-read", messageId=eid)

    _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "update": updates,
        }, "es0"],
    ])
    print(f"Marked {len(args.ids)} email(s) as read.")


def cmd_archive(args):
    if args.dry_run:
        print(f"[DRY RUN] Would archive: {args.ids}")
        return

    token = _get_token()
    session = _get_session(token)
    archive_id = _get_mailbox_id(session, token, "archive")

    if not archive_id:
        archive_id = _ensure_mailbox(session, token, "Archive")

    # Fetch current mailbox membership so we remove from actual source, not assumed inbox
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": args.ids,
            "properties": ["mailboxIds"],
        }, "eg0"],
    ])

    updates = {}
    for e in resp["methodResponses"][0][1].get("list", []):
        eid = e["id"]
        update = {"keywords/$seen": True, f"mailboxIds/{archive_id}": True}
        for mid in e.get("mailboxIds", {}):
            if mid != archive_id:
                update[f"mailboxIds/{mid}"] = None
        updates[eid] = update
        _audit_log("archive", messageId=eid)

    if updates:
        _api_call(session, token, [
            ["Email/set", {
                "accountId": session["accountId"],
                "update": updates,
            }, "es0"],
        ])
    print(f"Archived {len(updates)} email(s).")


def cmd_delete(args):
    """Soft delete — move to ClawHQ-Spam folder."""
    if args.dry_run:
        print(f"[DRY RUN] Would move to ClawHQ-Spam: {args.ids}")
        return

    token = _get_token()
    session = _get_session(token)
    spam_id = _ensure_mailbox(session, token, "ClawHQ-Spam")

    # Fetch current mailbox membership
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": args.ids,
            "properties": ["mailboxIds"],
        }, "eg0"],
    ])

    updates = {}
    for e in resp["methodResponses"][0][1].get("list", []):
        eid = e["id"]
        update = {"keywords/$seen": True, f"mailboxIds/{spam_id}": True}
        for mid in e.get("mailboxIds", {}):
            if mid != spam_id:
                update[f"mailboxIds/{mid}"] = None
        updates[eid] = update
        _audit_log("delete", messageId=eid)

    if updates:
        _api_call(session, token, [
            ["Email/set", {
                "accountId": session["accountId"],
                "update": updates,
            }, "es0"],
        ])
    print(f"Moved {len(updates)} email(s) to ClawHQ-Spam.")


def cmd_move(args):
    if args.dry_run:
        print(f"[DRY RUN] Would move {args.id} to {args.folder}")
        return

    token = _get_token()
    session = _get_session(token)

    target_id = _get_mailbox_id_by_name(session, token, args.folder)
    if not target_id:
        print(f"Error: Folder '{args.folder}' not found", file=sys.stderr)
        sys.exit(1)

    # Get current mailboxes
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["mailboxIds"],
        }, "eg0"],
    ])
    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    update = {f"mailboxIds/{target_id}": True}
    for mid in emails[0].get("mailboxIds", {}):
        update[f"mailboxIds/{mid}"] = None
    update[f"mailboxIds/{target_id}"] = True

    _audit_log("move", messageId=args.id, folder=args.folder)
    _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "update": {args.id: update},
        }, "es0"],
    ])
    print(f"Moved to {args.folder}.")


def cmd_label(args):
    if args.dry_run:
        print(f"[DRY RUN] Would label {args.id} with {args.keyword}")
        return

    token = _get_token()
    session = _get_session(token)

    _audit_log("label", messageId=args.id, keyword=args.keyword)
    _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "update": {args.id: {f"keywords/{args.keyword}": True}},
        }, "es0"],
    ])
    print(f"Added keyword '{args.keyword}'.")


def cmd_unlabel(args):
    if args.dry_run:
        print(f"[DRY RUN] Would unlabel {args.id} keyword {args.keyword}")
        return

    token = _get_token()
    session = _get_session(token)

    _audit_log("unlabel", messageId=args.id, keyword=args.keyword)
    _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "update": {args.id: {f"keywords/{args.keyword}": None}},
        }, "es0"],
    ])
    print(f"Removed keyword '{args.keyword}'.")


def cmd_batch(args):
    """Process batch operations from stdin JSON.

    Merges multiple actions for the same email into one JMAP update.
    Archive and delete implicitly mark as read.
    """
    data = json.loads(sys.stdin.read())
    if not isinstance(data, list):
        print("Error: Expected JSON array on stdin", file=sys.stderr)
        sys.exit(1)

    if args.dry_run:
        for op in data:
            print(f"[DRY RUN] {op.get('action', '?')}: {op.get('id', '?')}")
        return

    token = _get_token()
    session = _get_session(token)

    # Collect all email IDs to fetch current mailbox state
    all_ids = list({op["id"] for op in data if op.get("id")})
    if not all_ids:
        return

    # Fetch current mailboxes for all emails in one call
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": all_ids,
            "properties": ["mailboxIds"],
        }, "eg0"],
    ])
    email_mailboxes = {}
    for e in resp["methodResponses"][0][1].get("list", []):
        email_mailboxes[e["id"]] = set(e.get("mailboxIds", {}).keys())

    # Preload mailbox IDs lazily
    archive_id = None
    spam_id = None

    # Merge actions per email ID (multiple actions on same email → single update)
    updates = {}
    for op in data:
        eid = op.get("id")
        action = op.get("action")
        if not eid or not action:
            print(f"Warning: Skipping invalid batch entry: {op}", file=sys.stderr)
            continue

        _audit_log(action, messageId=eid, reason=op.get("reason", "batch"))

        if eid not in updates:
            updates[eid] = {}

        if action == "archive":
            if not archive_id:
                archive_id = _get_mailbox_id(session, token, "archive")
                if not archive_id:
                    archive_id = _ensure_mailbox(session, token, "Archive")
            updates[eid]["keywords/$seen"] = True
            updates[eid][f"mailboxIds/{archive_id}"] = True
            for mid in email_mailboxes.get(eid, set()):
                if mid != archive_id:
                    updates[eid][f"mailboxIds/{mid}"] = None
        elif action == "delete":
            if not spam_id:
                spam_id = _ensure_mailbox(session, token, "ClawHQ-Spam")
            updates[eid]["keywords/$seen"] = True
            updates[eid][f"mailboxIds/{spam_id}"] = True
            for mid in email_mailboxes.get(eid, set()):
                if mid != spam_id:
                    updates[eid][f"mailboxIds/{mid}"] = None
        elif action == "mark-read":
            updates[eid]["keywords/$seen"] = True
        elif action == "label":
            kw = op.get("keyword")
            if kw:
                updates[eid][f"keywords/{kw}"] = True
        elif action == "unlabel":
            kw = op.get("keyword")
            if kw:
                updates[eid][f"keywords/{kw}"] = None
        else:
            print(f"Warning: Unknown action '{action}' for {eid}", file=sys.stderr)

    if not updates:
        return

    _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "update": updates,
        }, "es0"],
    ])
    print(f"Batch: processed {len(updates)} email(s).")


# ── Send / Reply / Forward / Draft ────────────────────────────────────────────

def _read_body():
    if sys.stdin.isatty():
        print("Error: Body must be piped via stdin", file=sys.stderr)
        sys.exit(1)
    return sys.stdin.read()


def _create_email_and_submit(session, token, email_obj, dry_run=False):
    """Create an email in Drafts and submit it."""
    # ClawWall egress: scan subject + body for leaked secrets before sending
    egress_text = email_obj.get("subject", "")
    body_vals = email_obj.get("bodyValues", {})
    for bv in body_vals.values():
        if isinstance(bv, dict):
            egress_text += " " + bv.get("value", "")
    ok, leaks = _clawwall_egress(egress_text, source="email-fastmail")
    if not ok:
        labels = ", ".join(lk.label() for lk in leaks)
        print(f"EGRESS BLOCKED: secrets detected in outbound email ({labels}). Send aborted.", file=sys.stderr)
        sys.exit(3)

    if dry_run:
        print(f"[DRY RUN] Would send to: {email_obj.get('to', [])}")
        print(f"  Subject: {email_obj.get('subject', '')}")
        return

    _check_send_rate()

    identity_id = session.get("identityId")
    if not identity_id:
        print("Error: No identity found. Cannot send.", file=sys.stderr)
        sys.exit(1)

    drafts_id = _get_mailbox_id(session, token, "drafts")
    sent_id = _get_mailbox_id(session, token, "sent")

    email_obj["mailboxIds"] = {drafts_id: True}
    email_obj["keywords"] = {"$draft": True}

    resp = _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "create": {"draft": email_obj},
        }, "es0"],
        ["EmailSubmission/set", {
            "accountId": session["accountId"],
            "create": {
                "sub": {
                    "identityId": identity_id,
                    "emailId": "#draft",
                },
            },
            "onSuccessUpdateEmail": {
                "#sub": {
                    "mailboxIds/" + drafts_id: None,
                    "mailboxIds/" + sent_id: True,
                    "keywords/$draft": None,
                },
            },
        }, "ss0"],
    ])

    # Check for errors
    created = resp["methodResponses"][0][1].get("created", {})
    if "draft" not in created:
        not_created = resp["methodResponses"][0][1].get("notCreated", {})
        print(f"Error creating email: {not_created}", file=sys.stderr)
        sys.exit(1)

    sub_created = resp["methodResponses"][1][1].get("created", {})
    if "sub" not in sub_created:
        not_created = resp["methodResponses"][1][1].get("notCreated", {})
        print(f"Error submitting email: {not_created}", file=sys.stderr)
        sys.exit(1)

    _record_send()
    print("Sent.")


def cmd_send(args):
    # Delegated send validation
    if args.delegated:
        ok, reason = _validate_delegated(args.delegated, "send", args.subject)
        if not ok:
            print(f"Error: Delegated send rejected — {reason}", file=sys.stderr)
            sys.exit(1)

    token = _get_token()
    session = _get_session(token)
    body = _read_body()

    to = [{"email": args.to}]
    cc = [{"email": a} for a in args.cc] if args.cc else None
    bcc = [{"email": a} for a in args.bcc] if args.bcc else None

    email_obj = {
        "to": to,
        "subject": args.subject,
        "bodyValues": {"body": {"value": body, "charset": "utf-8"}},
        "textBody": [{"partId": "body", "type": "text/plain"}],
    }
    if cc:
        email_obj["cc"] = cc
    if bcc:
        email_obj["bcc"] = bcc

    _audit_log("send", to=args.to, subject=args.subject,
               delegated=args.delegated or False)
    _create_email_and_submit(session, token, email_obj, dry_run=args.dry_run)


def cmd_reply(args):
    # Delegated reply validation
    if args.delegated:
        ok, reason = _validate_delegated(args.delegated, "reply")
        if not ok:
            print(f"Error: Delegated reply rejected — {reason}", file=sys.stderr)
            sys.exit(1)

    token = _get_token()
    session = _get_session(token)
    body = _read_body()

    # Get original email
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["id", "from", "to", "cc", "replyTo", "subject", "messageId",
                           "references", "textBody", "bodyValues"],
            "fetchTextBodyValues": True,
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    orig = emails[0]
    reply_to = orig.get("replyTo") or orig.get("from") or []
    subject = orig.get("subject", "")
    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"

    message_id = (orig.get("messageId") or [None])[0]
    references = list(orig.get("references") or [])
    if message_id:
        references.append(message_id)

    # Quote original
    orig_body = ""
    for part in orig.get("textBody") or []:
        pid = part.get("partId")
        if pid and pid in orig.get("bodyValues", {}):
            orig_body += orig["bodyValues"][pid].get("value", "")

    quoted = "\n".join(f"> {line}" for line in orig_body.splitlines())
    full_body = f"{body}\n\n{quoted}"

    to = reply_to
    if args.reply_all:
        # Add original To and CC, excluding our own address
        # Fetch our email to filter it out
        own_email = None
        identity_id = session.get("identityId")
        if identity_id:
            try:
                id_resp = _api_call(session, token, [
                    ["Identity/get", {
                        "accountId": session["accountId"],
                        "ids": [identity_id],
                    }, "ig0"],
                ])
                identities = id_resp["methodResponses"][0][1].get("list", [])
                if identities:
                    own_email = identities[0].get("email", "").lower()
            except Exception:
                pass

        to = list(reply_to)
        for addr in (orig.get("to") or []) + (orig.get("cc") or []):
            addr_email = addr.get("email", "").lower()
            if own_email and addr_email == own_email:
                continue
            # Avoid duplicates with reply_to
            if not any(a.get("email", "").lower() == addr_email for a in to):
                to.append(addr)

    email_obj = {
        "to": to,
        "subject": subject,
        "inReplyTo": [message_id] if message_id else None,
        "references": references if references else None,
        "bodyValues": {"body": {"value": full_body, "charset": "utf-8"}},
        "textBody": [{"partId": "body", "type": "text/plain"}],
    }
    # Remove None values
    email_obj = {k: v for k, v in email_obj.items() if v is not None}

    _audit_log("reply", messageId=args.id, to=[a.get("email") for a in to],
               delegated=args.delegated or False)
    _create_email_and_submit(session, token, email_obj, dry_run=args.dry_run)


def cmd_forward(args):
    token = _get_token()
    session = _get_session(token)

    # Gate on contacts
    contacts = _load_contacts()
    known, _ = _is_known_contact(args.to, contacts)
    if not known:
        print(f"Error: '{args.to}' is not in contacts.json. Cannot forward to unknown addresses.", file=sys.stderr)
        sys.exit(1)

    # Get original
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["id", "from", "subject", "textBody", "bodyValues"],
            "fetchTextBodyValues": True,
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    orig = emails[0]
    subject = f"Fwd: {orig.get('subject', '')}"
    from_addr = (orig.get("from") or [{}])[0]

    orig_body = ""
    for part in orig.get("textBody") or []:
        pid = part.get("partId")
        if pid and pid in orig.get("bodyValues", {}):
            orig_body += orig["bodyValues"][pid].get("value", "")

    comment = args.comment + "\n\n" if args.comment else ""
    body = f"{comment}---------- Forwarded message ----------\nFrom: {from_addr.get('name', '')} <{from_addr.get('email', '')}>\nSubject: {orig.get('subject', '')}\n\n{orig_body}"

    email_obj = {
        "to": [{"email": args.to}],
        "subject": subject,
        "bodyValues": {"body": {"value": body, "charset": "utf-8"}},
        "textBody": [{"partId": "body", "type": "text/plain"}],
    }

    _audit_log("forward", messageId=args.id, to=args.to)
    _create_email_and_submit(session, token, email_obj, dry_run=args.dry_run)


def cmd_draft(args):
    token = _get_token()
    session = _get_session(token)
    body = _read_body()

    drafts_id = _get_mailbox_id(session, token, "drafts")

    to = [{"email": args.to}]
    cc = [{"email": a} for a in args.cc] if args.cc else None
    bcc = [{"email": a} for a in args.bcc] if args.bcc else None

    email_obj = {
        "to": to,
        "subject": args.subject,
        "mailboxIds": {drafts_id: True},
        "keywords": {"$draft": True},
        "bodyValues": {"body": {"value": body, "charset": "utf-8"}},
        "textBody": [{"partId": "body", "type": "text/plain"}],
    }
    if cc:
        email_obj["cc"] = cc
    if bcc:
        email_obj["bcc"] = bcc

    if args.dry_run:
        print(f"[DRY RUN] Would create draft to: {args.to}, subject: {args.subject}")
        return

    _audit_log("draft", to=args.to, subject=args.subject)
    resp = _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "create": {"draft": email_obj},
        }, "es0"],
    ])

    created = resp["methodResponses"][0][1].get("created", {})
    if "draft" in created:
        print(f"Draft saved: {created['draft']['id']}")
    else:
        not_created = resp["methodResponses"][0][1].get("notCreated", {})
        print(f"Error: {not_created}", file=sys.stderr)
        sys.exit(1)


def cmd_draft_reply(args):
    token = _get_token()
    session = _get_session(token)
    body = _read_body()

    # Get original email
    resp = _api_call(session, token, [
        ["Email/get", {
            "accountId": session["accountId"],
            "ids": [args.id],
            "properties": ["id", "from", "replyTo", "subject", "messageId",
                           "references", "textBody", "bodyValues"],
            "fetchTextBodyValues": True,
        }, "eg0"],
    ])

    emails = resp["methodResponses"][0][1].get("list", [])
    if not emails:
        print(f"Error: Email {args.id} not found", file=sys.stderr)
        sys.exit(1)

    orig = emails[0]
    reply_to = orig.get("replyTo") or orig.get("from") or []
    subject = orig.get("subject", "")
    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"

    message_id = (orig.get("messageId") or [None])[0]
    references = list(orig.get("references") or [])
    if message_id:
        references.append(message_id)

    orig_body = ""
    for part in orig.get("textBody") or []:
        pid = part.get("partId")
        if pid and pid in orig.get("bodyValues", {}):
            orig_body += orig["bodyValues"][pid].get("value", "")

    quoted = "\n".join(f"> {line}" for line in orig_body.splitlines())
    full_body = f"{body}\n\n{quoted}"

    drafts_id = _get_mailbox_id(session, token, "drafts")

    email_obj = {
        "to": reply_to,
        "subject": subject,
        "inReplyTo": [message_id] if message_id else None,
        "references": references if references else None,
        "mailboxIds": {drafts_id: True},
        "keywords": {"$draft": True},
        "bodyValues": {"body": {"value": full_body, "charset": "utf-8"}},
        "textBody": [{"partId": "body", "type": "text/plain"}],
    }
    email_obj = {k: v for k, v in email_obj.items() if v is not None}

    if args.dry_run:
        print(f"[DRY RUN] Would create draft reply to: {[a.get('email') for a in reply_to]}")
        return

    _audit_log("draft-reply", messageId=args.id)
    resp = _api_call(session, token, [
        ["Email/set", {
            "accountId": session["accountId"],
            "create": {"draft": email_obj},
        }, "es0"],
    ])

    created = resp["methodResponses"][0][1].get("created", {})
    if "draft" in created:
        print(f"Draft reply saved: {created['draft']['id']}")
    else:
        not_created = resp["methodResponses"][0][1].get("notCreated", {})
        print(f"Error: {not_created}", file=sys.stderr)
        sys.exit(1)


def cmd_send_draft(args):
    token = _get_token()
    session = _get_session(token)

    if args.dry_run:
        print(f"[DRY RUN] Would send draft: {args.id}")
        return

    _check_send_rate()

    identity_id = session.get("identityId")
    if not identity_id:
        print("Error: No identity found. Cannot send.", file=sys.stderr)
        sys.exit(1)

    drafts_id = _get_mailbox_id(session, token, "drafts")
    sent_id = _get_mailbox_id(session, token, "sent")

    _audit_log("send-draft", messageId=args.id)
    resp = _api_call(session, token, [
        ["EmailSubmission/set", {
            "accountId": session["accountId"],
            "create": {
                "sub": {
                    "identityId": identity_id,
                    "emailId": args.id,
                },
            },
            "onSuccessUpdateEmail": {
                "#sub": {
                    "mailboxIds/" + drafts_id: None,
                    "mailboxIds/" + sent_id: True,
                    "keywords/$draft": None,
                },
            },
        }, "ss0"],
    ])

    sub_created = resp["methodResponses"][0][1].get("created", {})
    if "sub" in sub_created:
        _record_send()
        print("Draft sent.")
    else:
        not_created = resp["methodResponses"][0][1].get("notCreated", {})
        print(f"Error: {not_created}", file=sys.stderr)
        sys.exit(1)


# ── Follow-ups ─────────────────────────────────────────────────────────────────

def cmd_followup(args):
    state = _load_state()
    followups = state.get("followups", [])

    if args.followup_cmd == "add":
        entry = {
            "messageId": args.id,
            "addedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "due": args.due,
            "done": False,
        }
        followups.append(entry)
        state["followups"] = followups
        _save_state(state)
        print(f"Follow-up added for {args.id}" + (f" (due: {args.due})" if args.due else ""))

    elif args.followup_cmd == "list":
        pending = [f for f in followups if not f.get("done")]
        if not pending:
            print("No pending follow-ups.")
            return
        today = datetime.date.today().isoformat()
        for f in pending:
            due_date = f.get("due")
            if due_date and due_date <= today:
                status = " ⚠️ OVERDUE"
            elif due_date:
                status = f" [due: {due_date}]"
            else:
                status = ""
            print(f"  {f['messageId']} — added {f['addedAt'][:10]}{status}")

    elif args.followup_cmd == "done":
        found = False
        for f in followups:
            if f["messageId"] == args.id:
                f["done"] = True
                f["doneAt"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
                found = True
                break
        if found:
            state["followups"] = followups
            _save_state(state)
            print(f"Follow-up resolved: {args.id}")
        else:
            print(f"Error: No follow-up found for {args.id}", file=sys.stderr)
            sys.exit(1)


# ── Contacts ───────────────────────────────────────────────────────────────────

def cmd_contacts(args):
    contacts = _load_contacts()

    if args.contacts_cmd == "list":
        for c in contacts.get("contacts", []):
            ctx = f" — {c['context']}" if c.get("context") else ""
            trust = f" [{c['trust']}]" if c.get("trust") else ""
            print(f"  {c['name']} <{c['email']}>{trust}{ctx}")

    elif args.contacts_cmd == "add":
        # Check for duplicates
        existing = {c["email"].lower() for c in contacts.get("contacts", [])}
        if args.email.lower() in existing:
            print(f"Error: {args.email} already in contacts. Use 'fm contacts find' to see it.", file=sys.stderr)
            sys.exit(1)

        entry = {
            "email": args.email,
            "name": args.name,
            "context": args.context or "",
            "trust": "known",
            "addedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        }
        contacts.setdefault("contacts", []).append(entry)
        d = os.path.dirname(CONTACTS_FILE)
        fd, tmp = tempfile.mkstemp(dir=d, suffix=".tmp")
        with os.fdopen(fd, "w") as f:
            json.dump(contacts, f, indent=2, ensure_ascii=False)
        os.replace(tmp, CONTACTS_FILE)
        print(f"Added: {args.name} <{args.email}>")

    elif args.contacts_cmd == "find":
        query = args.query.lower()
        matches = [c for c in contacts.get("contacts", [])
                    if query in c.get("name", "").lower() or query in c.get("email", "").lower()]
        if not matches:
            print("No matches.")
            return
        for c in matches:
            ctx = f" — {c['context']}" if c.get("context") else ""
            print(f"  {c['name']} <{c['email']}>{ctx}")

    elif args.contacts_cmd == "import":
        print("Contact import: scanning sent mail for frequent recipients...")
        token = _get_token()
        session = _get_session(token)
        sent_id = _get_mailbox_id(session, token, "sent")
        if not sent_id:
            print("Error: Sent folder not found", file=sys.stderr)
            sys.exit(1)

        resp = _api_call(session, token, [
            ["Email/query", {
                "accountId": session["accountId"],
                "filter": {"inMailbox": sent_id},
                "sort": [{"property": "receivedAt", "isAscending": False}],
                "limit": 100,
            }, "eq0"],
            ["Email/get", {
                "accountId": session["accountId"],
                "#ids": {"resultOf": "eq0", "name": "Email/query", "path": "/ids"},
                "properties": ["to", "cc"],
            }, "eg0"],
        ])

        emails = resp["methodResponses"][1][1].get("list", [])
        addr_count = {}
        for e in emails:
            for addr in (e.get("to") or []) + (e.get("cc") or []):
                email_addr = addr.get("email", "")
                if email_addr:
                    key = email_addr.lower()
                    if key not in addr_count:
                        addr_count[key] = {"email": email_addr, "name": addr.get("name", ""), "count": 0}
                    addr_count[key]["count"] += 1

        existing = {c["email"].lower() for c in contacts.get("contacts", [])}
        new_contacts = []
        for key, info in sorted(addr_count.items(), key=lambda x: -x[1]["count"]):
            if key not in existing and info["count"] >= 2:
                new_contacts.append(info)

        if not new_contacts:
            print("No new frequent contacts found.")
            return

        print(f"Found {len(new_contacts)} frequent recipients not in contacts:")
        for c in new_contacts[:20]:
            print(f"  {c['name']} <{c['email']}> ({c['count']} emails)")
        print("\nAdd them with: fm contacts add <email> <name>")


# ── Audit ──────────────────────────────────────────────────────────────────────

def cmd_audit(args):
    last = args.last or 20
    try:
        with open(AUDIT_FILE, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("No audit log yet.")
        return

    for line in lines[-last:]:
        try:
            entry = json.loads(line)
            ts = entry.get("timestamp", "")[:19]
            action = entry.get("action", "?")
            mid = entry.get("messageId", "")
            subj = entry.get("subject", "")
            extra = f" — {subj}" if subj else ""
            if entry.get("to"):
                extra = f" → {entry['to']}"
            print(f"  {ts}  {action:12s}  {mid}{extra}")
        except json.JSONDecodeError:
            continue


def cmd_audit_summary(args):
    try:
        with open(AUDIT_FILE, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("No audit log yet.")
        return

    cutoff = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=24)).isoformat()
    counts = {}
    for line in lines:
        try:
            entry = json.loads(line)
            if entry.get("timestamp", "") >= cutoff:
                action = entry.get("action", "other")
                counts[action] = counts.get(action, 0) + 1
        except json.JSONDecodeError:
            continue

    total = sum(counts.values())
    print(f"Last 24 hours: {total} actions")
    for action, count in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {action}: {count}")


# ── Argument Parsing ───────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="FastMail JMAP email client")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen without making changes")
    subparsers = parser.add_subparsers(dest="command")

    # Read commands
    p = subparsers.add_parser("triage")
    p.add_argument("--limit", type=int)
    p.add_argument("--count", action="store_true")

    subparsers.add_parser("inbox")

    p = subparsers.add_parser("all")
    p.add_argument("--limit", type=int)

    p = subparsers.add_parser("read")
    p.add_argument("id")

    p = subparsers.add_parser("thread")
    p.add_argument("id")
    p.add_argument("--last", type=int)

    p = subparsers.add_parser("search")
    p.add_argument("query", nargs="?")
    p.add_argument("--from", dest="from_addr")
    p.add_argument("--subject")
    p.add_argument("--since")
    p.add_argument("--has-attachment", action="store_true")
    p.add_argument("--limit", type=int)

    subparsers.add_parser("folders")

    p = subparsers.add_parser("attachments")
    p.add_argument("id")

    p = subparsers.add_parser("download")
    p.add_argument("id")
    p.add_argument("part_id")

    # Write commands
    p = subparsers.add_parser("mark-read")
    p.add_argument("ids", nargs="+")

    p = subparsers.add_parser("archive")
    p.add_argument("ids", nargs="+")

    p = subparsers.add_parser("delete")
    p.add_argument("ids", nargs="+")

    p = subparsers.add_parser("move")
    p.add_argument("id")
    p.add_argument("folder")

    p = subparsers.add_parser("label")
    p.add_argument("id")
    p.add_argument("keyword")

    p = subparsers.add_parser("unlabel")
    p.add_argument("id")
    p.add_argument("keyword")

    subparsers.add_parser("batch")

    # Send commands
    p = subparsers.add_parser("send")
    p.add_argument("to")
    p.add_argument("subject")
    p.add_argument("--cc", nargs="*")
    p.add_argument("--bcc", nargs="*")
    p.add_argument("--delegated", help="Delegated send category (e.g. unsubscribe, vendor-reply)")

    p = subparsers.add_parser("reply")
    p.add_argument("id")
    p.add_argument("--delegated", help="Delegated reply category (e.g. appointment-confirm, vendor-reply)")

    p = subparsers.add_parser("reply-all")
    p.add_argument("id")
    p.add_argument("--delegated", help="Delegated reply category")

    p = subparsers.add_parser("forward")
    p.add_argument("id")
    p.add_argument("to")
    p.add_argument("--comment", default="")

    p = subparsers.add_parser("draft")
    p.add_argument("to")
    p.add_argument("subject")
    p.add_argument("--cc", nargs="*")
    p.add_argument("--bcc", nargs="*")

    p = subparsers.add_parser("draft-reply")
    p.add_argument("id")

    p = subparsers.add_parser("send-draft")
    p.add_argument("id")

    # Follow-ups
    p_fu = subparsers.add_parser("followup")
    fu_sub = p_fu.add_subparsers(dest="followup_cmd")
    p_fu_add = fu_sub.add_parser("add")
    p_fu_add.add_argument("id")
    p_fu_add.add_argument("--due")
    fu_sub.add_parser("list")
    p_fu_done = fu_sub.add_parser("done")
    p_fu_done.add_argument("id")

    # Contacts
    p_ct = subparsers.add_parser("contacts")
    ct_sub = p_ct.add_subparsers(dest="contacts_cmd")
    ct_sub.add_parser("list")
    p_ct_add = ct_sub.add_parser("add")
    p_ct_add.add_argument("email")
    p_ct_add.add_argument("name")
    p_ct_add.add_argument("--context")
    p_ct_find = ct_sub.add_parser("find")
    p_ct_find.add_argument("query")
    ct_sub.add_parser("import")

    # Audit
    p = subparsers.add_parser("audit")
    p.add_argument("--last", type=int)

    subparsers.add_parser("audit-summary")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    cmd_map = {
        "triage": cmd_triage,
        "inbox": cmd_inbox,
        "all": cmd_all,
        "read": cmd_read,
        "thread": cmd_thread,
        "search": cmd_search,
        "folders": cmd_folders,
        "attachments": cmd_attachments,
        "download": cmd_download,
        "mark-read": cmd_mark_read,
        "archive": cmd_archive,
        "delete": cmd_delete,
        "move": cmd_move,
        "label": cmd_label,
        "unlabel": cmd_unlabel,
        "batch": cmd_batch,
        "send": cmd_send,
        "reply": lambda a: cmd_reply(type('Args', (), {**vars(a), 'reply_all': False})()),
        "reply-all": lambda a: cmd_reply(type('Args', (), {**vars(a), 'reply_all': True})()),
        "forward": cmd_forward,
        "draft": cmd_draft,
        "draft-reply": cmd_draft_reply,
        "send-draft": cmd_send_draft,
        "followup": cmd_followup,
        "contacts": cmd_contacts,
        "audit": cmd_audit,
        "audit-summary": cmd_audit_summary,
    }

    handler = cmd_map.get(args.command)
    if handler:
        try:
            handler(args)
        except urllib.error.HTTPError as e:
            print(f"HTTP error {e.code}: {e.reason}", file=sys.stderr)
            try:
                print(e.read().decode()[:500], file=sys.stderr)
            except Exception:
                pass
            sys.exit(1)
        except urllib.error.URLError as e:
            print(f"Network error: {e.reason}", file=sys.stderr)
            sys.exit(1)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
