/**
 * Cloud demo orchestrator — ephemeral DigitalOcean droplet for zero-Docker demos.
 *
 * Provisions the smallest DO droplet, runs `clawhq demo` on it via cloud-init,
 * opens the browser to the cloud chat UI, and destroys the droplet on exit.
 * The user only needs a DIGITALOCEAN_TOKEN — no Docker, no local setup.
 */

import { createDigitalOceanAdapter } from "../cloud/provisioning/providers/digitalocean.js";

// ── Constants ────────────────────────────────────────────────────────────────

/** Smallest DO droplet — sufficient for demo (mock LLM, no Ollama). */
const DEMO_DROPLET_SIZE = "s-1vcpu-512mb-10gb";

/** Default region for demo droplets. */
const DEMO_REGION = "nyc3";

/** Port the demo chat UI listens on (matches local demo default). */
const DEMO_CHAT_PORT = 3838;

/** Max time to wait for the demo agent to become healthy (ms). */
const DEMO_HEALTH_TIMEOUT_MS = 180_000; // 3 minutes

/** Polling interval for health checks (ms). */
const DEMO_HEALTH_INTERVAL_MS = 5_000;

/** Name prefix for ephemeral demo droplets. */
const DEMO_NAME_PREFIX = "clawhq-demo";

// ── Types ────────────────────────────────────────────────────────────────────

export interface CloudDemoOptions {
  /** DigitalOcean API token (defaults to DIGITALOCEAN_TOKEN env var). */
  readonly token?: string;
  /** DO region slug (defaults to nyc3). */
  readonly region?: string;
}

export interface CloudDemoProgress {
  step:
    | "token-validate"
    | "create-droplet"
    | "wait-boot"
    | "firewall"
    | "health"
    | "ready"
    | "destroy";
  status: "running" | "done" | "failed";
  message: string;
}

export type CloudDemoProgressCallback = (event: CloudDemoProgress) => void;

export interface CloudDemoResult {
  /** Public IP of the running demo droplet. */
  readonly ipAddress: string;
  /** URL to the cloud chat UI. */
  readonly chatUrl: string;
  /** Monthly cost of the droplet size. */
  readonly monthlyCost: number;
  /** Destroy the droplet and clean up. Returns true if destruction verified. */
  readonly destroy: () => Promise<boolean>;
}

// ── Cost estimate ────────────────────────────────────────────────────────────

/** Get the hourly cost for the demo droplet (for display purposes). */
export function getDemoCostEstimate(): { monthlyCost: number; hourlyCost: string; description: string } {
  // s-1vcpu-512mb-10gb = $4/mo
  const monthlyCost = 4;
  const hourlyCost = (monthlyCost / 730).toFixed(4); // ~$0.0055
  return {
    monthlyCost,
    hourlyCost: `$${hourlyCost}`,
    description: `${DEMO_DROPLET_SIZE} (512 MB / 1 vCPU) — $${monthlyCost}/mo, ~$${hourlyCost}/hr`,
  };
}

// ── Cloud-init for demo ──────────────────────────────────────────────────────

/**
 * Generate cloud-init script that bootstraps a demo agent on the droplet.
 *
 * Installs Docker, Node.js 22, ClawHQ, then runs `clawhq demo` as a
 * systemd service. The demo includes a mock LLM — no Ollama needed.
 */
function generateDemoCloudInit(name: string): string {
  const safeName = name.replace(/'/g, "'\\''");

  return `#!/bin/bash
set -euo pipefail

# ── ClawHQ cloud demo bootstrap ─────────────────────────────────────────────
# Instance: ${safeName}
# Mode: ephemeral demo (auto-destroys on user exit)
# Generated by ClawHQ provisioning engine

export DEBIAN_FRONTEND=noninteractive
SENTINEL_DIR="/var/lib/clawhq/sentinels"
mkdir -p "\${SENTINEL_DIR}"

# ── 1. System updates ───────────────────────────────────────────────────────

if [ ! -f "\${SENTINEL_DIR}/apt-update.done" ]; then
  apt-get update -qq
  apt-get upgrade -y -qq
  touch "\${SENTINEL_DIR}/apt-update.done"
fi

# ── 2. Install Node.js 22 ───────────────────────────────────────────────────

if [ ! -f "\${SENTINEL_DIR}/nodejs.done" ]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y -qq nodejs
  touch "\${SENTINEL_DIR}/nodejs.done"
fi

# ── 3. Install ClawHQ ───────────────────────────────────────────────────────

if [ ! -f "\${SENTINEL_DIR}/clawhq.done" ]; then
  npm install -g clawhq
  touch "\${SENTINEL_DIR}/clawhq.done"
fi

# ── 4. Run demo as systemd service ──────────────────────────────────────────

cat > /etc/systemd/system/clawhq-demo.service <<EOSERVICE
[Unit]
Description=ClawHQ Demo Agent
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/env clawhq demo --port ${DEMO_CHAT_PORT}
Restart=on-failure
RestartSec=3
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
EOSERVICE

systemctl daemon-reload
systemctl enable clawhq-demo
systemctl start clawhq-demo

# ── 5. Signal ready ─────────────────────────────────────────────────────────

mkdir -p /var/lib/clawhq
cat > /var/lib/clawhq/boot-status.json <<EOJSON
{"status":"ready","name":"${safeName}","mode":"demo","bootedAt":"$(date -u +%Y-%m-%dT%H:%M:%SZ)"}
EOJSON
`;
}

// ── Cloud demo runner ────────────────────────────────────────────────────────

/**
 * Provision an ephemeral DigitalOcean droplet running the ClawHQ demo.
 *
 * Flow: validate token → create droplet → firewall → poll health → return URL.
 * The returned `destroy` function tears down the droplet.
 */
export async function runCloudDemo(
  options: CloudDemoOptions,
  onProgress?: CloudDemoProgressCallback,
): Promise<CloudDemoResult> {
  const progress = onProgress ?? (() => {});
  const token = options.token ?? process.env.DIGITALOCEAN_TOKEN;

  if (!token) {
    throw new Error(
      "DIGITALOCEAN_TOKEN environment variable is required for cloud demo.\n" +
      "Set it with: export DIGITALOCEAN_TOKEN=<your-token>",
    );
  }

  const region = options.region ?? DEMO_REGION;
  const adapter = createDigitalOceanAdapter(token);
  const name = `${DEMO_NAME_PREFIX}-${Date.now()}`;

  // Track provider instance ID for cleanup even on partial failure
  let providerInstanceId: string | undefined;

  // Build the destroy function (used for cleanup on success or failure)
  const destroyDroplet = async (): Promise<boolean> => {
    if (!providerInstanceId) return true;

    progress({ step: "destroy", status: "running", message: "Destroying demo droplet..." });

    try {
      const result = await adapter.destroyVm(providerInstanceId);
      if (result.success) {
        // Verify destruction
        for (let i = 0; i < 5; i++) {
          const gone = await adapter.verifyDestroyed(providerInstanceId);
          if (gone) break;
          await sleep(3_000);
        }
        progress({ step: "destroy", status: "done", message: "Demo droplet destroyed — no ongoing cost" });
        providerInstanceId = undefined;
        return true;
      }
      progress({ step: "destroy", status: "failed", message: `Destroy failed: ${result.error}` });
      return false;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      progress({ step: "destroy", status: "failed", message: `Destroy error: ${msg}` });
      return false;
    }
  };

  try {
    // Step 1: Validate token
    progress({ step: "token-validate", status: "running", message: "Validating DigitalOcean token..." });
    const validation = await adapter.validateToken();
    if (!validation.valid) {
      throw new Error(`Invalid DigitalOcean token: ${validation.error ?? "token rejected by API"}`);
    }
    progress({ step: "token-validate", status: "done", message: `Token valid (${validation.account ?? "authenticated"})` });

    // Step 2: Create droplet
    const monthlyCost = adapter.getMonthlyCost(DEMO_DROPLET_SIZE) ?? 4;
    progress({
      step: "create-droplet",
      status: "running",
      message: `Creating ${DEMO_DROPLET_SIZE} droplet in ${region}...`,
    });

    const userData = generateDemoCloudInit(name);
    const createResult = await adapter.createVm({
      name,
      region,
      size: DEMO_DROPLET_SIZE,
      userData,
    });

    if (!createResult.success || !createResult.providerInstanceId) {
      throw new Error(`Failed to create droplet: ${createResult.error ?? "unknown error"}`);
    }

    providerInstanceId = createResult.providerInstanceId;
    progress({ step: "create-droplet", status: "done", message: `Droplet created (ID: ${providerInstanceId})` });

    // Step 3: Wait for boot + IP
    progress({ step: "wait-boot", status: "running", message: "Waiting for droplet to boot..." });

    let ipAddress = createResult.ipAddress;
    if (!ipAddress) {
      // Poll for IP assignment
      for (let i = 0; i < 30; i++) {
        await sleep(2_000);
        const status = await adapter.getVmStatus(providerInstanceId);
        if (status.ipAddress) {
          ipAddress = status.ipAddress;
          break;
        }
      }
    }

    if (!ipAddress) {
      throw new Error("Droplet created but no IP address assigned after 60 seconds");
    }

    progress({ step: "wait-boot", status: "done", message: `Droplet active at ${ipAddress}` });

    // Step 4: Create firewall
    progress({ step: "firewall", status: "running", message: `Creating firewall (allow port ${DEMO_CHAT_PORT})...` });

    const firewallResult = await adapter.createFirewall({
      name: `clawhq-demo-${providerInstanceId}`,
      inboundPorts: [DEMO_CHAT_PORT],
      dropletIds: [providerInstanceId],
    });

    if (firewallResult.success) {
      progress({ step: "firewall", status: "done", message: "Firewall configured" });
    } else {
      // Non-fatal — log and continue
      progress({ step: "firewall", status: "failed", message: `Firewall failed: ${firewallResult.error} (port may be open anyway)` });
    }

    // Step 5: Poll health (wait for cloud-init + demo to start)
    progress({ step: "health", status: "running", message: "Waiting for demo agent to start (up to 3 min)..." });

    const healthResult = await pollDemoHealth({
      ipAddress,
      port: DEMO_CHAT_PORT,
      timeoutMs: DEMO_HEALTH_TIMEOUT_MS,
      intervalMs: DEMO_HEALTH_INTERVAL_MS,
    });

    if (!healthResult.healthy) {
      throw new Error(
        `Demo agent did not become healthy within 3 minutes.\n` +
        `The droplet (${ipAddress}) may still be installing. ` +
        `Try: curl http://${ipAddress}:${DEMO_CHAT_PORT}/`,
      );
    }

    progress({
      step: "health",
      status: "done",
      message: `Demo agent healthy (${healthResult.attempts} checks, ${Math.round(healthResult.elapsedMs / 1000)}s)`,
    });

    const chatUrl = `http://${ipAddress}:${DEMO_CHAT_PORT}`;
    progress({ step: "ready", status: "done", message: `Cloud demo running at ${chatUrl}` });

    return {
      ipAddress,
      chatUrl,
      monthlyCost,
      destroy: destroyDroplet,
    };
  } catch (err) {
    // Best-effort cleanup on failure
    if (providerInstanceId) {
      await destroyDroplet();
    }
    throw err;
  }
}

// ── Demo health polling ──────────────────────────────────────────────────────

interface DemoHealthOptions {
  readonly ipAddress: string;
  readonly port: number;
  readonly timeoutMs: number;
  readonly intervalMs: number;
  readonly signal?: AbortSignal;
}

interface DemoHealthResult {
  readonly healthy: boolean;
  readonly attempts: number;
  readonly elapsedMs: number;
}

/**
 * Poll the demo chat UI port until it responds.
 * More targeted than the generic health poller — checks the specific demo port.
 */
async function pollDemoHealth(options: DemoHealthOptions): Promise<DemoHealthResult> {
  const start = Date.now();
  let attempts = 0;

  while (Date.now() - start < options.timeoutMs) {
    if (options.signal?.aborted) break;

    attempts++;

    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 5_000);
      const res = await fetch(`http://${options.ipAddress}:${options.port}/`, {
        signal: controller.signal,
      });
      clearTimeout(timer);

      if (res.ok) {
        return { healthy: true, attempts, elapsedMs: Date.now() - start };
      }
    } catch {
      // Expected — droplet still bootstrapping
    }

    await sleep(options.intervalMs, options.signal);
  }

  return { healthy: false, attempts, elapsedMs: Date.now() - start };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve) => {
    if (signal?.aborted) {
      resolve();
      return;
    }
    const timer = setTimeout(resolve, ms);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      resolve();
    }, { once: true });
  });
}
