/**
 * Ownership table for the deployment directory (~/.clawhq/).
 *
 * Every file under a deployment has exactly one owner. The owner determines
 * who may write to the file and what happens when its content drifts from
 * the expected state. This is the single source of truth — all future
 * reconciler work (atomic apply, drift detection, unclassified-file audit)
 * reads from this table.
 *
 * This module is correctness scaffolding. It does NOT yet enforce ownership
 * on writes — that's Phase 2. For now it backs two observability tools:
 *   - `deploy-unclassified` doctor check (surfaces files not covered here)
 *   - snapshot-diff tool (groups drift by owner)
 *
 * References:
 *   - docs/ARCHITECTURE.md §703 "The Deployment Directory"
 *   - docs/BLUEPRINT-SPEC.md §143, §531 (identity_mount: read-only is the
 *     security baseline — not a stylistic choice)
 *   - docs/security/INCIDENTS.md §321 (supply-chain skill attack rationale)
 */

// ── Types ───────────────────────────────────────────────────────────────────

export type Owner =
  /** Regenerated by clawhq on every `apply`. Any edit will be reverted.
   *  Identity files fall here per the read-only security baseline. */
  | "clawhq"
  /** Clawhq never touches. User/agent state that must survive everything. */
  | "user"
  /** OpenClaw runtime writes, clawhq only reads. Sessions, cron runtime
   *  state, paired devices, delivery queue, channel pairings. */
  | "openclaw"
  /** Compiled definitions merged with preserved runtime state. Today only
   *  cron/jobs.json and engine/.env (credential protection). */
  | "merged"
  /** Template seeded on first apply, then owned by user or the
   *  `integrate add` flow. Never overwritten after creation. */
  | "seeded-once"
  /** Owned by `clawhq build`, not `clawhq apply`. Compose, Dockerfile,
   *  build manifests, OpenClaw source tree. */
  | "build";

export interface OwnershipRule {
  /** Path relative to the deployment directory. Supports two pattern forms:
   *    - exact match: "workspace/SOUL.md"
   *    - directory prefix: "workspace/memory/**" matches the dir and
   *      everything recursively under it. */
  readonly pattern: string;
  readonly owner: Owner;
  /** Short rationale. Surfaces in `clawhq inspect <path>` and drift reports. */
  readonly reason: string;
}

// ── Rules ───────────────────────────────────────────────────────────────────

/**
 * Ordered list of ownership rules. First match wins, so put more specific
 * rules before broader ones. Broad directory patterns go last.
 *
 * Coverage target: every path emitted by the compiler (grep compiler.ts
 * for `relativePath:`), plus every runtime path OpenClaw writes to under
 * the deploy directory. The `deploy-unclassified` doctor check surfaces
 * anything this table misses.
 */
export const OWNERSHIP_RULES: readonly OwnershipRule[] = [
  // ── ClawHQ meta ───────────────────────────────────────────────────────────
  { pattern: "clawhq.yaml", owner: "seeded-once",
    reason: "init creates, user edits via integrate add / direct" },
  { pattern: "clawhq.yaml.bak", owner: "clawhq",
    reason: "automatic backup of clawhq.yaml" },
  { pattern: "update-check.json", owner: "clawhq",
    reason: "updater's last-check cache" },
  { pattern: ".clawhq.lock", owner: "clawhq",
    reason: "deploy-dir advisory lock (src/config/lock.ts)" },

  // ── Install-from-source topology (engine/source) ─────────────────────────
  // When OpenClaw is installed from source, the deployDir root *is* the
  // openclaw deploy dir — so openclaw.json/.env/credentials.json appear at
  // root as well as under engine/. Classify them the same as their engine/
  // siblings (topology-agnostic).
  { pattern: "openclaw.json", owner: "clawhq",
    reason: "root copy for install-from-source topology" },
  { pattern: ".env", owner: "merged",
    reason: "root copy for install-from-source topology" },
  { pattern: "credentials.json", owner: "seeded-once",
    reason: "root copy for install-from-source topology (Phase 0)" },

  // ── Identity files (OWNED_BY_CLAWHQ per BLUEPRINT-SPEC.md §143) ──────────
  // Read-only mount (chmod 444, Docker :ro) is the supply-chain-attack
  // countermeasure. Regeneration reverts any in-container tampering.
  { pattern: "workspace/SOUL.md",      owner: "clawhq", reason: "identity; read-only security baseline" },
  { pattern: "workspace/AGENTS.md",    owner: "clawhq", reason: "identity; read-only security baseline" },
  { pattern: "workspace/BOOTSTRAP.md", owner: "clawhq", reason: "identity; read-only security baseline" },
  { pattern: "workspace/IDENTITY.md",  owner: "clawhq", reason: "identity; read-only security baseline" },
  { pattern: "workspace/TOOLS.md",     owner: "clawhq", reason: "identity; read-only security baseline" },
  { pattern: "workspace/HEARTBEAT.md", owner: "clawhq", reason: "identity; read-only security baseline" },

  // USER.md is SEEDED_ONCE: apply roundtrips it via parseUserMd to preserve
  // user-edited name/timezone/communication/constraints fields.
  { pattern: "workspace/USER.md", owner: "seeded-once",
    reason: "user context; apply roundtrips via parseUserMd" },

  // ── User-owned ───────────────────────────────────────────────────────────
  { pattern: "workspace/MEMORY.md", owner: "user",
    reason: "user's curated memory" },
  { pattern: "workspace/memory/**", owner: "user",
    reason: "agent memory store (hot/warm/cold)" },
  { pattern: "workspace/config/substack-aliases.json", owner: "user",
    reason: "user publication aliases" },

  // ── Runtime config (engine/) ─────────────────────────────────────────────
  { pattern: "engine/openclaw.json", owner: "clawhq",
    reason: "runtime config; regenerated from blueprint" },
  { pattern: "engine/.env", owner: "merged",
    reason: "template + credential preservation via protectCredentials" },
  { pattern: "engine/credentials.json", owner: "seeded-once",
    reason: "integrate add populates; never overwritten" },
  { pattern: "engine/docker-compose.yml", owner: "build",
    reason: "owned by clawhq build" },
  { pattern: "engine/Dockerfile", owner: "build",
    reason: "owned by clawhq build" },
  { pattern: "engine/build-manifest.json", owner: "build",
    reason: "build change-detection manifest" },
  { pattern: "engine/cred-proxy.js", owner: "clawhq",
    reason: "credential proxy sidecar" },
  { pattern: "engine/cred-proxy-routes.json", owner: "clawhq",
    reason: "credential proxy route config" },
  { pattern: "engine/Dockerfile.stage1", owner: "build",
    reason: "two-stage Docker base image" },
  { pattern: "engine/workspace-integrity.json", owner: "clawhq",
    reason: "workspace integrity manifest for drift detection" },
  { pattern: "engine/clawwall/**", owner: "build",
    reason: "ClawWall security wrapper (curl-egress-wrapper, etc.)" },
  { pattern: "engine/clawdius-trading/**", owner: "clawhq",
    reason: "clawdius-trading sidecar container (alert-grade trading assistant)" },
  { pattern: "engine/credentials", owner: "openclaw",
    reason: "openclaw-managed channel credentials dir" },
  { pattern: "engine/source/**", owner: "build",
    reason: "openclaw source tree (install --from-source)" },
  { pattern: "engine/workspace/**", owner: "openclaw",
    reason: "openclaw-native workspace (source install topology)" },
  { pattern: "engine/tmp/**", owner: "openclaw",
    reason: "openclaw temp files" },

  // ── Cron ─────────────────────────────────────────────────────────────────
  { pattern: "cron/jobs.json", owner: "merged",
    reason: "clawhq job defs + openclaw runtime state" },
  { pattern: "cron/jobs.json.bak", owner: "openclaw",
    reason: "saveCronStore backup" },
  { pattern: "cron/runs/**", owner: "openclaw",
    reason: "cron execution log (JSONL per job)" },

  // ── Compiled workspace outputs ───────────────────────────────────────────
  { pattern: "workspace/skills/**", owner: "clawhq",
    reason: "skills compiled from blueprint" },
  { pattern: "workspace/tools/**", owner: "clawhq",
    reason: "tool wrappers compiled from blueprint" },
  { pattern: "workspace/delegated-rules.json", owner: "clawhq",
    reason: "compiled delegation rule set" },
  { pattern: "workspace/identity/**", owner: "clawhq",
    reason: "identity subdir artifacts (per ARCHITECTURE.md §717)" },

  // ── User-curated workspace content ───────────────────────────────────────
  { pattern: "workspace/knowledge/**", owner: "user",
    reason: "user knowledge base (wiki, references)" },
  { pattern: "workspace/references/**", owner: "user",
    reason: "user-curated reference docs" },
  { pattern: "workspace/markets/**", owner: "user",
    reason: "markets tool workspace — user-editable CONFIG.json + caches" },
  { pattern: "workspace/state/**", owner: "openclaw",
    reason: "openclaw workspace runtime state" },

  // ── Ops ──────────────────────────────────────────────────────────────────
  { pattern: "ops/firewall/allowlist.yaml", owner: "clawhq",
    reason: "compiled egress allowlist" },
  { pattern: "ops/audit/**", owner: "clawhq",
    reason: "append-only audit logs (tool/egress/secret)" },
  { pattern: "ops/backup/**", owner: "clawhq",
    reason: "encrypted backup snapshots" },
  { pattern: "ops/doctor/**", owner: "clawhq",
    reason: "doctor state" },
  { pattern: "ops/monitor/**", owner: "clawhq",
    reason: "health monitor daemon state" },
  { pattern: "ops/updater/**", owner: "clawhq",
    reason: "update state + rollback images" },
  { pattern: "ops/automation/**", owner: "clawhq",
    reason: "systemd units + scripts generated by clawhq" },

  // ── Other clawhq-managed trees ───────────────────────────────────────────
  { pattern: "security/**", owner: "clawhq",
    reason: "security posture + sandbox config" },
  { pattern: "cloud/**", owner: "clawhq",
    reason: "cloud connection state" },
  { pattern: "shared/**", owner: "clawhq",
    reason: "shared configs" },
  { pattern: "logs/**", owner: "clawhq",
    reason: "clawhq operational logs" },

  // ── OpenClaw runtime (source-install topology) ───────────────────────────
  { pattern: "agents/**", owner: "openclaw",
    reason: "openclaw agent sessions + state" },
  { pattern: "canvas/**", owner: "openclaw",
    reason: "openclaw canvas UI state" },
  { pattern: "delivery-queue/**", owner: "openclaw",
    reason: "message delivery queue (pending/failed)" },
  { pattern: "devices/**", owner: "openclaw",
    reason: "paired devices registry" },
  { pattern: "credentials/**", owner: "openclaw",
    reason: "openclaw channel credentials (telegram pairing, etc.)" },
  { pattern: "telegram/**", owner: "openclaw",
    reason: "telegram channel state" },
  { pattern: "media/**", owner: "openclaw",
    reason: "openclaw media store" },
  { pattern: "identity/**", owner: "openclaw",
    reason: "openclaw-managed identity artifacts (source-install layout)" },
  { pattern: "qqbot/**", owner: "openclaw",
    reason: "openclaw qq channel state" },
  { pattern: "memory/**", owner: "user",
    reason: "root-level memory dir (source-install topology)" },
  { pattern: "tasks/**", owner: "openclaw",
    reason: "openclaw task runs log" },
  { pattern: "exec-approvals.json", owner: "openclaw",
    reason: "openclaw tool approval queue" },

  // ── Transient backups (clawhq + openclaw both produce these) ─────────────
  { pattern: "**/*.bak", owner: "openclaw",
    reason: "transient backup (saveCronStore, compose fix, etc.)" },

  // ── Workspace runtime state (per-tool JSON files) ────────────────────────
  { pattern: "workspace/.openclaw/**", owner: "openclaw",
    reason: "openclaw hidden workspace state" },
  { pattern: "**/*-state.json", owner: "openclaw",
    reason: "per-tool runtime state (email-state, portfolio-state, etc.)" },
];

// ── Classification API ──────────────────────────────────────────────────────

/**
 * Return the owner of a path, or `null` if no rule matches.
 *
 * @param relativePath — path relative to the deployment directory (no
 *   leading slash, forward-slash separated on all platforms).
 */
export function classify(relativePath: string): Owner | null {
  const rule = classifyRule(relativePath);
  return rule ? rule.owner : null;
}

/**
 * Return the full matching rule (or `null`), so callers can display the
 * `reason` alongside drift reports.
 */
export function classifyRule(relativePath: string): OwnershipRule | null {
  for (const rule of OWNERSHIP_RULES) {
    if (matchesPattern(relativePath, rule.pattern)) return rule;
  }
  return null;
}

function matchesPattern(path: string, pattern: string): boolean {
  // Directory prefix: "ops/audit/**" matches "ops/audit" and anything under
  if (pattern.endsWith("/**")) {
    const prefix = pattern.slice(0, -3);
    return path === prefix || path.startsWith(prefix + "/");
  }
  // Tail suffix: "**/*.bak" matches any path ending in ".bak"
  if (pattern.startsWith("**/*")) {
    const suffix = pattern.slice(3);
    if (suffix.startsWith("*")) {
      return path.endsWith(suffix.slice(1));
    }
  }
  // Exact path match
  return path === pattern;
}
