/**
 * Operational script generators — auto-update, security monitor, workspace backup.
 *
 * Each function returns the content of a bash script that can be run standalone
 * or via systemd timer. Scripts are generated during `clawhq init` and written
 * to the deployment directory at ops/automation/scripts/.
 */

import {
  GITHUB_ADVISORIES_URL,
  OPS_BACKUP_RETENTION_DAYS,
  OPS_SECURITY_SEVERITIES,
} from "../../config/defaults.js";

// ── Auto-Update Script ─────────────────────────────────────────────────────

/**
 * Generate the auto-update bash script.
 *
 * Runs `clawhq update` with rollback support. Logs to ops/automation/logs/.
 */
export function generateAutoUpdateScript(deployDir: string): string {
  return `#!/usr/bin/env bash
# ClawHQ Auto-Update Script
# Generated by clawhq init — do not edit manually.
# Runs on a systemd timer schedule (default: daily).

set -euo pipefail

DEPLOY_DIR="${deployDir}"
LOG_DIR="\${DEPLOY_DIR}/ops/automation/logs"
LOG_FILE="\${LOG_DIR}/autoupdate-\$(date +%Y%m%d-%H%M%S).log"

mkdir -p "\${LOG_DIR}"

log() {
  echo "[\$(date -Iseconds)] \$*" | tee -a "\${LOG_FILE}"
}

log "Auto-update started"

# Check for updates first
if ! clawhq update --check --deploy-dir "\${DEPLOY_DIR}" >> "\${LOG_FILE}" 2>&1; then
  log "Update check failed — see log for details"
  exit 1
fi

# Apply update (clawhq update handles backup + rollback internally)
if clawhq update --deploy-dir "\${DEPLOY_DIR}" >> "\${LOG_FILE}" 2>&1; then
  log "Auto-update completed successfully"
else
  log "Auto-update failed — rollback may have been applied"
  exit 1
fi

# Prune old logs (keep last 30 days)
find "\${LOG_DIR}" -name "autoupdate-*.log" -mtime +30 -delete 2>/dev/null || true

log "Auto-update finished"
`;
}

// ── Security Monitor Script ────────────────────────────────────────────────

/**
 * Generate the security advisory monitor script.
 *
 * Checks GitHub Security Advisories API for OpenClaw CVEs and alerts
 * on critical/high severity findings.
 */
export function generateSecurityMonitorScript(
  deployDir: string,
  severities: readonly string[] = OPS_SECURITY_SEVERITIES,
): string {
  const sevFilter = severities.map((s) => `"${s}"`).join(" ");

  return `#!/usr/bin/env bash
# ClawHQ Security Monitor Script
# Generated by clawhq init — do not edit manually.
# Checks GitHub Security Advisories for OpenClaw CVEs.

set -euo pipefail

DEPLOY_DIR="${deployDir}"
LOG_DIR="\${DEPLOY_DIR}/ops/automation/logs"
STATE_DIR="\${DEPLOY_DIR}/ops/automation/state"
LOG_FILE="\${LOG_DIR}/security-\$(date +%Y%m%d-%H%M%S).log"
SEEN_FILE="\${STATE_DIR}/seen-advisories.txt"
ALERT_FILE="\${DEPLOY_DIR}/ops/automation/alerts/security-alerts.json"
ADVISORIES_URL="${GITHUB_ADVISORIES_URL}"
SEVERITIES=(${sevFilter})

mkdir -p "\${LOG_DIR}" "\${STATE_DIR}" "\$(dirname "\${ALERT_FILE}")"
touch "\${SEEN_FILE}"

log() {
  echo "[\$(date -Iseconds)] \$*" | tee -a "\${LOG_FILE}"
}

log "Security monitor started"

# Fetch advisories from GitHub API (public, no auth required for public repos)
RESPONSE=\$(curl -sfL \\
  -H "Accept: application/vnd.github+json" \\
  -H "X-GitHub-Api-Version: 2022-11-28" \\
  "\${ADVISORIES_URL}" 2>>\${LOG_FILE}) || {
  log "Failed to fetch security advisories"
  exit 1
}

# Parse advisories and check for new critical/high CVEs
NEW_ALERTS=0
echo "\${RESPONSE}" | jq -c '.[]' 2>/dev/null | while IFS= read -r advisory; do
  GHSA_ID=\$(echo "\${advisory}" | jq -r '.ghsa_id // empty')
  SEVERITY=\$(echo "\${advisory}" | jq -r '.severity // "unknown"')
  CVE_ID=\$(echo "\${advisory}" | jq -r '.cve_id // "none"')
  SUMMARY=\$(echo "\${advisory}" | jq -r '.summary // "No summary"')

  # Skip if already seen
  if grep -qF "\${GHSA_ID}" "\${SEEN_FILE}" 2>/dev/null; then
    continue
  fi

  # Check severity filter
  MATCH=false
  for sev in "\${SEVERITIES[@]}"; do
    if [ "\${SEVERITY}" = "\${sev}" ]; then
      MATCH=true
      break
    fi
  done

  if [ "\${MATCH}" = "true" ]; then
    log "ALERT: \${SEVERITY} advisory \${GHSA_ID} (CVE: \${CVE_ID}): \${SUMMARY}"
    echo "\${GHSA_ID}" >> "\${SEEN_FILE}"

    # Append to alerts file (JSON lines format)
    jq -n \\
      --arg ghsa "\${GHSA_ID}" \\
      --arg cve "\${CVE_ID}" \\
      --arg severity "\${SEVERITY}" \\
      --arg summary "\${SUMMARY}" \\
      --arg detected "\$(date -Iseconds)" \\
      '{ghsa_id: \$ghsa, cve_id: \$cve, severity: \$severity, summary: \$summary, detected_at: \$detected}' \\
      >> "\${ALERT_FILE}"

    NEW_ALERTS=\$((NEW_ALERTS + 1))
  else
    # Track non-matching advisories too so we don't re-check them
    echo "\${GHSA_ID}" >> "\${SEEN_FILE}"
  fi
done

log "Security monitor completed — \${NEW_ALERTS:-0} new alert(s)"

# Prune old logs (keep last 30 days)
find "\${LOG_DIR}" -name "security-*.log" -mtime +30 -delete 2>/dev/null || true

log "Security monitor finished"
`;
}

// ── Workspace Backup Script ────────────────────────────────────────────────

/**
 * Generate the workspace backup script.
 *
 * Uses rsync for incremental backup with configurable retention policy.
 */
export function generateBackupScript(
  deployDir: string,
  targetDir?: string,
  retentionDays: number = OPS_BACKUP_RETENTION_DAYS,
): string {
  const backupTarget = targetDir ?? `${deployDir}/ops/backup/incremental`;

  return `#!/usr/bin/env bash
# ClawHQ Workspace Backup Script
# Generated by clawhq init — do not edit manually.
# Incremental rsync backup with retention policy.

set -euo pipefail

DEPLOY_DIR="${deployDir}"
BACKUP_DIR="${backupTarget}"
RETENTION_DAYS=${retentionDays}
LOG_DIR="\${DEPLOY_DIR}/ops/automation/logs"
LOG_FILE="\${LOG_DIR}/backup-\$(date +%Y%m%d-%H%M%S).log"
TIMESTAMP=\$(date +%Y%m%d-%H%M%S)
SNAPSHOT_DIR="\${BACKUP_DIR}/\${TIMESTAMP}"
LATEST_LINK="\${BACKUP_DIR}/latest"

mkdir -p "\${LOG_DIR}" "\${BACKUP_DIR}"

log() {
  echo "[\$(date -Iseconds)] \$*" | tee -a "\${LOG_FILE}"
}

log "Workspace backup started"

# Source directories to back up
SOURCES=(
  "\${DEPLOY_DIR}/engine"
  "\${DEPLOY_DIR}/workspace"
  "\${DEPLOY_DIR}/cron"
  "\${DEPLOY_DIR}/clawhq.yaml"
)

# Build rsync source list (only include paths that exist)
RSYNC_SOURCES=()
for src in "\${SOURCES[@]}"; do
  if [ -e "\${src}" ]; then
    RSYNC_SOURCES+=("\${src}")
  else
    log "Skipping non-existent source: \${src}"
  fi
done

if [ \${#RSYNC_SOURCES[@]} -eq 0 ]; then
  log "ERROR: No source files found to back up"
  exit 1
fi

# Incremental backup using hard links to previous snapshot
LINK_DEST=""
if [ -L "\${LATEST_LINK}" ] && [ -d "\${LATEST_LINK}" ]; then
  LINK_DEST="--link-dest=\${LATEST_LINK}"
fi

# Run rsync
rsync -a --delete \\
  \${LINK_DEST} \\
  "\${RSYNC_SOURCES[@]}" \\
  "\${SNAPSHOT_DIR}/" >> "\${LOG_FILE}" 2>&1

# Update latest symlink
rm -f "\${LATEST_LINK}"
ln -s "\${SNAPSHOT_DIR}" "\${LATEST_LINK}"

log "Backup snapshot created: \${SNAPSHOT_DIR}"

# Apply retention policy — remove snapshots older than RETENTION_DAYS
REMOVED=0
for old_snap in "\${BACKUP_DIR}"/20*; do
  [ -d "\${old_snap}" ] || continue
  snap_name=\$(basename "\${old_snap}")
  # Parse timestamp from directory name (YYYYMMDD-HHMMSS)
  snap_date=\$(echo "\${snap_name}" | cut -c1-8)
  cutoff_date=\$(date -d "-\${RETENTION_DAYS} days" +%Y%m%d 2>/dev/null || date -v-\${RETENTION_DAYS}d +%Y%m%d 2>/dev/null || echo "")

  if [ -n "\${cutoff_date}" ] && [ "\${snap_date}" '<' "\${cutoff_date}" ]; then
    log "Removing expired snapshot: \${snap_name}"
    rm -rf "\${old_snap}"
    REMOVED=\$((REMOVED + 1))
  fi
done

log "Retention applied: \${REMOVED} expired snapshot(s) removed"

# Prune old logs (keep last 30 days)
find "\${LOG_DIR}" -name "backup-*.log" -mtime +30 -delete 2>/dev/null || true

log "Workspace backup finished"
`;
}
