/**
 * approve-action tool wrapper generator — approval gate for high-stakes actions.
 *
 * Generates a Node.js script that agents use to submit actions for approval
 * and check approval status. This tool writes to workspace/memory/approval-queue.json,
 * which is the same file ClawHQ reads for the approval workflow.
 *
 * When Telegram credentials are available in .env, the tool automatically
 * sends a notification with approve/reject buttons.
 *
 * Uses CommonJS (require) since the generated script runs as an extensionless
 * file in workspace/tools/ where Node.js defaults to CJS.
 *
 * Commands:
 *   approve-action submit <category> <summary> <detail> [--source <name>]
 *   approve-action check <id>
 *   approve-action list
 */

export function generateApproveActionTool(): string {
  return `#!/usr/bin/env node
// approve-action — submit high-stakes actions for user approval
// Generated by ClawHQ from blueprint config
//
// Usage:
//   approve-action submit <category> <summary> <detail> [--source <name>] [--meta key=val,...]
//   approve-action check <id>
//   approve-action list
//
// Categories: send_email, send_message, account_change, public_post, delete, purchase, other
//
// The agent MUST use this tool before executing any action that requires approval.
// The action is queued and the user is notified via Telegram (if configured).
// The agent should poll with 'check' until the status is 'approved' or 'rejected'.

"use strict";

const { existsSync, mkdirSync, readFileSync, writeFileSync } = require("node:fs");
const { randomBytes } = require("node:crypto");
const { join, dirname } = require("node:path");

const QUEUE_FILE = join(__dirname, "..", "memory", "approval-queue.json");

// ── Queue I/O ───────────────────────────────────────────────────────────────

function loadQueue() {
  if (!existsSync(QUEUE_FILE)) return { version: 1, items: [] };
  try {
    return JSON.parse(readFileSync(QUEUE_FILE, "utf-8"));
  } catch {
    return { version: 1, items: [] };
  }
}

function saveQueue(queue) {
  const dir = dirname(QUEUE_FILE);
  mkdirSync(dir, { recursive: true });
  writeFileSync(QUEUE_FILE, JSON.stringify(queue, null, 2));
}

function generateId() {
  const ts = Date.now().toString(36);
  const rand = randomBytes(4).toString("hex");
  return \`apv-\${ts}-\${rand}\`;
}

// ── Telegram Notification ───────────────────────────────────────────────────

function loadTelegramConfig() {
  const envPath = join(__dirname, "..", "..", "engine", ".env");
  if (!existsSync(envPath)) return null;
  try {
    const content = readFileSync(envPath, "utf-8");
    const get = (key) => {
      for (const line of content.split("\\n")) {
        const t = line.trim();
        if (t.startsWith("#") || !t.includes("=")) continue;
        const eq = t.indexOf("=");
        if (t.slice(0, eq).trim() !== key) continue;
        let v = t.slice(eq + 1).trim();
        if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
        return v || null;
      }
      return null;
    };
    const botToken = get("TELEGRAM_BOT_TOKEN");
    const chatId = get("TELEGRAM_CHAT_ID");
    return botToken && chatId ? { botToken, chatId } : null;
  } catch {
    return null;
  }
}

const CATEGORY_LABELS = {
  send_email: "Send Email",
  send_message: "Send Message",
  account_change: "Account Change",
  public_post: "Public Post",
  delete: "Delete",
  purchase: "Purchase",
  other: "Action",
};

function escapeMarkdown(text) {
  return text.replace(/([_*[\\]()~\\\`>#+\\-=|{}.!])/g, "\\\\$1");
}

async function sendTelegramNotification(config, item) {
  const label = CATEGORY_LABELS[item.category] || "Action";
  const text = [
    "*Approval Required*",
    "",
    \`*\${label}:* \${escapeMarkdown(item.summary)}\`,
    \`*Source:* \${escapeMarkdown(item.source)}\`,
    ...(item.detail ? ["", escapeMarkdown(item.detail.slice(0, 500))] : []),
    "",
    \`ID: \\\\\\\`\${item.id}\\\\\\\`\`,
  ].join("\\n");

  const keyboard = {
    inline_keyboard: [[
      { text: "Approve", callback_data: \`apv:approve:\${item.id}\` },
      { text: "Reject", callback_data: \`apv:reject:\${item.id}\` },
    ]],
  };

  try {
    const res = await fetch(\`https://api.telegram.org/bot\${config.botToken}/sendMessage\`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: config.chatId,
        text,
        parse_mode: "MarkdownV2",
        reply_markup: keyboard,
      }),
    });
    return res.ok;
  } catch {
    return false;
  }
}

// ── Commands ────────────────────────────────────────────────────────────────

async function submit(args) {
  if (args.length < 3) {
    console.error("Usage: approve-action submit <category> <summary> <detail> [--source <name>] [--meta key=val,...]");
    process.exit(1);
  }

  const category = args[0];
  const summary = args[1];
  const detail = args[2];
  let source = "agent";
  let metadata;

  for (let i = 3; i < args.length; i++) {
    if (args[i] === "--source" && args[i + 1]) { source = args[++i]; continue; }
    if (args[i] === "--meta" && args[i + 1]) {
      metadata = {};
      for (const pair of args[++i].split(",")) {
        const [k, ...vParts] = pair.split("=");
        if (k) metadata[k] = vParts.join("=");
      }
      continue;
    }
  }

  const queue = loadQueue();
  const item = {
    id: generateId(),
    category,
    summary,
    detail,
    source,
    status: "pending",
    createdAt: new Date().toISOString(),
  };
  if (metadata) item.metadata = metadata;

  queue.items.push(item);

  // Expire oldest if queue exceeds 100 pending items
  const pending = queue.items.filter((i) => i.status === "pending");
  if (pending.length > 100) {
    pending.sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
    const oldest = pending[0];
    const idx = queue.items.findIndex((i) => i.id === oldest.id);
    if (idx !== -1) {
      queue.items[idx] = Object.assign({}, queue.items[idx], {
        status: "expired",
        resolvedAt: new Date().toISOString(),
      });
    }
  }

  saveQueue(queue);

  // Auto-notify via Telegram
  const tg = loadTelegramConfig();
  const notified = tg ? await sendTelegramNotification(tg, item) : false;

  console.log(JSON.stringify({
    queued: true,
    id: item.id,
    status: "pending",
    notified,
  }));
}

function check(args) {
  if (args.length < 1) {
    console.error("Usage: approve-action check <id>");
    process.exit(1);
  }

  const queue = loadQueue();
  const item = queue.items.find((i) => i.id === args[0]);

  if (!item) {
    console.log(JSON.stringify({ found: false, id: args[0] }));
    return;
  }

  console.log(JSON.stringify({
    found: true,
    id: item.id,
    status: item.status,
    category: item.category,
    summary: item.summary,
    resolvedAt: item.resolvedAt || null,
  }));
}

function listPending() {
  const queue = loadQueue();
  const pending = queue.items.filter((i) => i.status === "pending");
  console.log(JSON.stringify(pending.map((i) => ({
    id: i.id,
    category: i.category,
    summary: i.summary,
    source: i.source,
    createdAt: i.createdAt,
  }))));
}

// ── Main ────────────────────────────────────────────────────────────────────

const cmd = process.argv[2];
const rest = process.argv.slice(3);

(async () => {
  switch (cmd) {
    case "submit": await submit(rest); break;
    case "check":  check(rest); break;
    case "list":   listPending(); break;
    default:
      console.error(\`Usage: approve-action <submit|check|list> [args]
Commands:
  submit <category> <summary> <detail> [--source <name>] [--meta key=val,...]
    Queue an action for approval. Returns JSON with the approval ID.
    Categories: send_email, send_message, account_change, public_post, delete, purchase, other

  check <id>
    Check status of an approval item. Returns JSON with status.

  list
    List all pending approval items.\`);
      if (cmd) process.exit(1);
  }
})();
`;
}
