/**
 * Email tool wrapper generator - inbox management via himalaya.
 *
 * Generates a bash script that wraps the himalaya CLI for email
 * operations: inbox, read, send, reply, search, mark-read, delete.
 *
 * All inbound content piped through ClawWall sanitizer.
 * All outbound content scanned for secret leaks via egress check.
 */

export function generateEmailTool(): string {
  return `#!/usr/bin/env bash
# email - inbox management via himalaya
# Generated by ClawHQ
#
# Commands:
#   inbox                - list unread emails (JSON)
#   all                  - list all recent emails (JSON)
#   read <id>            - read email body (JSON)
#   send <to> <subject>  - compose and send (reads body from stdin)
#   reply <id>           - reply to email (reads body from stdin)
#   mark-read <id>       - mark as read
#   delete <id>          - delete email
#   search <query>       - search emails (JSON)
#   folders              - list available folders
set -euo pipefail

HIMALAYA="\${HIMALAYA_BIN:-himalaya}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ClawWall: sanitize untrusted inbound email content
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source email --log
  else
    cat
  fi
}

# ClawWall egress: scan outbound content for leaked secrets before sending
_egress_check() {
  local text="$1"
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    if ! printf '%s' "$text" | "$SCRIPT_DIR/sanitize" --egress --source email 2>&1; then
      echo "SEND ABORTED: ClawWall egress check failed." >&2
      exit 3
    fi
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  inbox)
    "$HIMALAYA" envelope list --output json "$@" -- not flag seen | _sanitize
    ;;
  all)
    "$HIMALAYA" envelope list --output json "$@" | _sanitize
    ;;
  read)
    "$HIMALAYA" message read --output json "$@" | _sanitize
    ;;
  send)
    to="\${1:?Usage: email send <to> <subject>}"
    subject="\${2:?Usage: email send <to> <subject>}"
    shift 2
    if [[ "$to" == *$'\\n'* || "$to" == *$'\\r'* ]]; then
      echo "email: invalid recipient (contains newline)" >&2; exit 1
    fi
    if [[ "$subject" == *$'\\n'* || "$subject" == *$'\\r'* ]]; then
      echo "email: invalid subject (contains newline)" >&2; exit 1
    fi
    body="$(cat)"
    _egress_check "$subject $body"
    printf 'To: %s\\r\\nSubject: %s\\r\\nMIME-Version: 1.0\\r\\nContent-Type: text/plain; charset=utf-8\\r\\n\\r\\n%s\\n' \\
      "$to" "$subject" "$body" | "$HIMALAYA" message send
    jq -n --arg to "$to" --arg subj "$subject" '{status:"sent",to:$to,subject:$subj}'
    ;;
  reply)
    id="\${1:?Usage: email reply <id>}"
    body="$(cat)"
    _egress_check "$body"
    echo "$body" | "$HIMALAYA" message reply "$id"
    ;;
  mark-read)
    "$HIMALAYA" flag add "\${1:?Usage: email mark-read <id>}" seen
    jq -n --arg id "$1" '{status:"marked_read",id:$id}'
    ;;
  delete)
    "$HIMALAYA" message delete "\${1:?Usage: email delete <id>}"
    jq -n --arg id "$1" '{status:"deleted",id:$id}'
    ;;
  search)
    "$HIMALAYA" envelope list --output json -- subject "$*" | _sanitize
    ;;
  folders)
    "$HIMALAYA" folder list --output json "$@" | _sanitize
    ;;
  help|--help|-h|"")
    sed -n '2,14p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "email: unknown command '$cmd'" >&2
    sed -n '2,14p' "$0" | sed 's/^# \\?//' >&2
    exit 1
    ;;
esac
`;
}
