/**
 * Email tool wrapper generator — inbox management via himalaya.
 *
 * Generates a bash script that wraps the himalaya CLI for email
 * operations: list, read, reply, send, search, move, delete.
 * Credentials come from environment variables set in .env.
 */

export function generateEmailTool(): string {
  return `#!/usr/bin/env bash
# email — inbox management via himalaya
# Generated by ClawHQ from blueprint config
set -euo pipefail

HIMALAYA="\${HIMALAYA_BIN:-himalaya}"

usage() {
  cat <<'USAGE'
Usage: email <command> [args]

Commands:
  list [--folder FOLDER] [--count N]   List messages (default: INBOX, 20)
  read <id>                            Read a message by ID
  reply <id> <body>                    Reply to a message
  send <to> <subject> <body>           Send a new message
  search <query>                       Search messages
  move <id> <folder>                   Move message to folder
  delete <id>                          Delete a message
  folders                              List available folders
USAGE
}

case "\${1:-}" in
  list)    shift; exec "$HIMALAYA" list "$@" ;;
  read)    shift; exec "$HIMALAYA" read "$@" ;;
  reply)   shift; exec "$HIMALAYA" reply "$@" ;;
  send)    shift; exec "$HIMALAYA" send "$@" ;;
  search)  shift; exec "$HIMALAYA" search "$@" ;;
  move)    shift; exec "$HIMALAYA" move "$@" ;;
  delete)  shift; exec "$HIMALAYA" delete "$@" ;;
  folders) shift; exec "$HIMALAYA" folders "$@" ;;
  -h|--help|help|"") usage ;;
  *) echo "email: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
