/**
 * Email tool wrapper generator — inbox management via himalaya.
 *
 * Generates a bash script that wraps the himalaya CLI for email
 * operations: list, read, reply, send, search, move, delete.
 * Credentials come from environment variables set in .env.
 *
 * High-stakes commands (reply, send, delete) route through the
 * approval queue via the approve-action tool. The agent must wait
 * for approval before the action executes.
 */

export function generateEmailTool(): string {
  return `#!/usr/bin/env bash
# email — inbox management via himalaya
# Generated by ClawHQ from blueprint config
# High-stakes commands (reply, send, delete) require approval before execution.
# Read commands piped through ClawWall sanitizer for prompt injection defense.
set -euo pipefail

HIMALAYA="\${HIMALAYA_BIN:-himalaya}"
TOOLS_DIR="$(cd "$(dirname "$0")" && pwd)"
APPROVE_ACTION="\${TOOLS_DIR}/approve-action"
SANITIZE="\${TOOLS_DIR}/sanitize"

# Pipe output through ClawWall sanitizer if available.
pipe_sanitize() {
  if [ -x "$SANITIZE" ]; then
    "$SANITIZE" --source email --strict --wrap
  else
    cat
  fi
}

usage() {
  cat <<'USAGE'
Usage: email <command> [args]

Commands:
  list [--folder FOLDER] [--count N]   List messages (default: INBOX, 20)
  read <id>                            Read a message by ID
  reply <id> <body>                    Reply to a message (requires approval)
  send <to> <subject> <body>           Send a new message (requires approval)
  search <query>                       Search messages
  move <id> <folder>                   Move message to folder
  delete <id>                          Delete a message (requires approval)
  folders                              List available folders
USAGE
}

# Gate a high-stakes action through the approval queue.
# Submits the action for approval, outputs the queue result, and exits.
# The agent must poll 'approve-action check <id>' and re-invoke after approval.
require_approval() {
  local category="$1"
  local summary="$2"
  local detail="$3"
  local source="\${4:-email}"

  if [ -x "$APPROVE_ACTION" ]; then
    exec "$APPROVE_ACTION" submit "$category" "$summary" "$detail" --source "$source"
  else
    echo '{"error": "approve-action tool not found. Cannot execute high-stakes action without approval gate."}' >&2
    exit 1
  fi
}

case "\${1:-}" in
  list)    shift; "$HIMALAYA" list "$@" | pipe_sanitize ;;
  read)    shift; "$HIMALAYA" read "$@" | pipe_sanitize ;;
  reply)
    shift
    local_id="\${1:-}"
    local_body="\${2:-}"
    if [ -z "$local_id" ]; then echo "email reply: missing message ID" >&2; exit 1; fi
    require_approval "send_email" "Reply to message $local_id" "$local_body" "email"
    ;;
  send)
    shift
    local_to="\${1:-}"
    local_subject="\${2:-}"
    local_body="\${3:-}"
    if [ -z "$local_to" ]; then echo "email send: missing recipient" >&2; exit 1; fi
    require_approval "send_email" "Send email to $local_to: $local_subject" "$local_body" "email"
    ;;
  search)  shift; "$HIMALAYA" search "$@" | pipe_sanitize ;;
  move)    shift; exec "$HIMALAYA" move "$@" ;;
  delete)
    shift
    local_id="\${1:-}"
    if [ -z "$local_id" ]; then echo "email delete: missing message ID" >&2; exit 1; fi
    require_approval "delete" "Delete email $local_id" "Permanently delete message $local_id" "email"
    ;;
  folders) shift; exec "$HIMALAYA" folders "$@" ;;
  -h|--help|help|"") usage ;;
  *) echo "email: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
