/**
 * Home Assistant tool wrapper generator — HA REST API via credential proxy.
 *
 * Routes through cred-proxy /ha prefix, fallback to HA_TOKEN + HA_URL.
 * Subcommands: states, services, call-service, history.
 * Entity-based allow/deny list for safety — HA_ENTITY_ALLOW and
 * HA_ENTITY_DENY env vars control which entities can be queried/controlled.
 *
 * Auth: credential proxy (preferred) or direct HA_TOKEN fallback.
 */

export function generateHaTool(): string {
  return `#!/usr/bin/env bash
# ha - Home Assistant REST API wrapper
# Generated by ClawHQ
#
# Commands:
#   states                           List all entity states (JSON)
#   state <entity_id>                Get state of a specific entity (JSON)
#   services                         List available services (JSON)
#   call-service <domain> <service> <entity_id> [data_json]  Call a service
#   history <entity_id> [hours]      Get entity history (JSON, default 24h)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\$0")" && pwd)"

# Auth: prefer credential proxy, fall back to direct token
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/ha"
  _curl() { curl -sS -H "Content-Type: application/json" "\$@"; }
else
  HA_BASE="\${HA_URL:?Set HA_URL or CRED_PROXY_URL}"
  TOKEN="\${HA_TOKEN:?Set HA_TOKEN or CRED_PROXY_URL}"
  API="\${HA_BASE}/api"
  _curl() { curl -sS -H "Content-Type: application/json" -H "Authorization: Bearer \$TOKEN" "\$@"; }
fi

# Entity allow/deny list for safety
# HA_ENTITY_ALLOW: comma-separated list of allowed entity ID prefixes (e.g. "light.,sensor.,switch.")
# HA_ENTITY_DENY: comma-separated list of denied entity ID prefixes (e.g. "lock.,alarm_control_panel.")
_check_entity() {
  local entity="\$1"
  local deny="\${HA_ENTITY_DENY:-}"
  local allow="\${HA_ENTITY_ALLOW:-}"

  # If deny list is set, check entity is not denied
  if [[ -n "\$deny" ]]; then
    IFS=',' read -ra DENIED <<< "\$deny"
    for prefix in "\${DENIED[@]}"; do
      prefix=\$(echo "\$prefix" | xargs)
      if [[ "\$entity" == \$prefix* ]]; then
        echo "ha: entity '\$entity' is denied by HA_ENTITY_DENY" >&2
        exit 1
      fi
    done
  fi

  # If allow list is set, check entity is allowed
  if [[ -n "\$allow" ]]; then
    IFS=',' read -ra ALLOWED <<< "\$allow"
    local matched=false
    for prefix in "\${ALLOWED[@]}"; do
      prefix=\$(echo "\$prefix" | xargs)
      if [[ "\$entity" == \$prefix* ]]; then
        matched=true
        break
      fi
    done
    if [[ "\$matched" == "false" ]]; then
      echo "ha: entity '\$entity' is not in HA_ENTITY_ALLOW" >&2
      exit 1
    fi
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "\$cmd" in
  states)
    _curl "\$API/states"
    ;;
  state)
    entity="\${1:?Usage: ha state <entity_id>}"
    _check_entity "\$entity"
    _curl "\$API/states/\$entity"
    ;;
  services)
    _curl "\$API/services"
    ;;
  call-service)
    domain="\${1:?Usage: ha call-service <domain> <service> <entity_id> [data_json]}"
    service="\${2:?Usage: ha call-service <domain> <service> <entity_id>}"
    entity="\${3:?Usage: ha call-service <domain> <service> <entity_id>}"
    data="\${4:-\\{\\}}"
    _check_entity "\$entity"
    payload=\$(jq -n --arg e "\$entity" --argjson d "\$data" '{entity_id: \$e} + \$d')
    _curl -X POST -d "\$payload" "\$API/services/\$domain/\$service"
    ;;
  history)
    entity="\${1:?Usage: ha history <entity_id> [hours]}"
    hours="\${2:-24}"
    _check_entity "\$entity"
    start=\$(date -u -d "-\${hours} hours" +%Y-%m-%dT%H:%M:%S%z 2>/dev/null || date -u -v-\${hours}H +%Y-%m-%dT%H:%M:%S%z)
    _curl "\$API/history/period/\$start?filter_entity_id=\$entity"
    ;;
  help|--help|-h|"")
    sed -n '2,11p' "\$0" | sed 's/^# \\\\?//'
    ;;
  *)
    echo "ha: unknown command '\$cmd'" >&2
    exit 1
    ;;
esac
`;
}
