/**
 * Himalaya config generator — renders workspace/config/himalaya/config.toml
 * from the himalaya-backed providers in a deployment.
 *
 * Himalaya (v1.2+) expects a TOML config with `backend.type = "imap"` and
 * `message.send.backend.type = "smtp"` sections per account. Passwords are
 * pulled from env vars at runtime via `backend.auth.cmd` so secrets stay in
 * .env (mode 0600), not duplicated in the config file.
 *
 * Multi-slot support: when a provider is bound to a numbered slot (e.g.
 * `email-2: icloud`) its env vars are prefixed (`EMAIL_2_IMAP_*`). The
 * account name in the TOML matches the slot so users can reference the
 * right mailbox per account (`email --account icloud`).
 */

import type { Provider } from "../catalog/providers.js";

/** Provider resolved from config with its domain slot attached. */
type ResolvedProvider = Provider & { domainKey: string };

/**
 * Render himalaya config TOML for all himalaya-backed providers.
 * Returns an empty string when no himalaya accounts are configured — caller
 * should skip emitting the file in that case.
 */
export function generateHimalayaConfig(
  providers: readonly ResolvedProvider[],
  env: Record<string, string> = {},
): string {
  const himalayaProviders = providers.filter(p => p.cli === "himalaya" && p.domain === "email");
  if (himalayaProviders.length === 0) return "";

  const sections: string[] = [
    "# Generated by clawhq — do not edit by hand. Re-run `clawhq apply`.",
    "# Passwords are pulled from .env at runtime via backend.auth.cmd (printenv).",
    "",
  ];

  let defaultAssigned = false;
  for (const provider of himalayaProviders) {
    const account = provider.id.replace(/[^a-zA-Z0-9_-]/g, "-");
    const prefix = envPrefixForSlot(provider.domainKey);
    const envKey = (key: string): string => `${prefix}${key}`;
    const resolved = (key: string): string => env[envKey(key)] ?? defaultFor(provider, key) ?? "";

    const imapHost = resolved("IMAP_HOST");
    const imapUser = resolved("IMAP_USER");
    const smtpHost = resolved("SMTP_HOST");
    const smtpUser = resolved("SMTP_USER");

    sections.push(`[accounts.${account}]`);
    if (!defaultAssigned) {
      sections.push("default = true");
      defaultAssigned = true;
    }
    sections.push(`email = "${imapUser}"`);
    sections.push(`display-name = "${provider.name}"`);
    sections.push("");
    sections.push(`backend.type = "imap"`);
    sections.push(`backend.host = "${imapHost}"`);
    sections.push(`backend.port = 993`);
    sections.push(`backend.login = "${imapUser}"`);
    sections.push(`backend.auth.type = "password"`);
    sections.push(`backend.auth.cmd = "printenv ${envKey("IMAP_PASS")}"`);
    sections.push("");
    sections.push(`message.send.backend.type = "smtp"`);
    sections.push(`message.send.backend.host = "${smtpHost}"`);
    sections.push(`message.send.backend.port = 587`);
    sections.push(`message.send.backend.login = "${smtpUser}"`);
    sections.push(`message.send.backend.auth.type = "password"`);
    sections.push(`message.send.backend.auth.cmd = "printenv ${envKey("SMTP_PASS")}"`);
    sections.push("");
  }

  return sections.join("\n");
}

/**
 * Env-var prefix for a provider slot. Primary slot (`email`) uses no prefix;
 * numbered slots (`email-2`, `email-3`) add `EMAIL_N_`.
 */
function envPrefixForSlot(domainKey: string): string {
  const match = domainKey.match(/^([a-z]+)-(\d+)$/);
  if (!match) return "";
  const domain = match[1] ?? "";
  const n = match[2] ?? "";
  return `${domain.toUpperCase()}_${n}_`;
}

/** Look up a default value for a provider env-var key. */
function defaultFor(provider: Provider, key: string): string {
  const ev = provider.envVars.find(v => v.key === key);
  return ev?.default ?? "";
}
