/**
 * iCal tool wrapper generator — calendar management via CalDAV.
 *
 * Generates a python3 script that uses the caldav library to interact
 * with CalDAV servers (iCloud, Google, Nextcloud, etc.).
 * Credentials come from environment variables set in .env.
 */

export function generateIcalTool(): string {
  return `#!/usr/bin/env python3
"""ical — calendar management via CalDAV.

Generated by ClawHQ from blueprint config.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta

def get_client():
    """Connect to CalDAV server using environment credentials."""
    try:
        import caldav
    except ImportError:
        print("error: caldav library not installed. Run: pip3 install caldav", file=sys.stderr)
        sys.exit(1)

    url = os.environ.get("CALDAV_URL", "")
    user = os.environ.get("CALDAV_USER", "")
    password = os.environ.get("CALDAV_PASSWORD", "")

    if not url:
        print("error: CALDAV_URL not set", file=sys.stderr)
        sys.exit(1)

    return caldav.DAVClient(url=url, username=user, password=password)

def cmd_list(args):
    """List upcoming events."""
    client = get_client()
    calendar = client.principal().calendars()[0]
    start = datetime.now()
    end = start + timedelta(days=args.days)
    events = calendar.date_search(start=start, end=end, expand=True)
    for event in events:
        vevent = event.vobject_instance.vevent
        summary = str(vevent.summary.value) if hasattr(vevent, "summary") else "(no title)"
        dtstart = str(vevent.dtstart.value) if hasattr(vevent, "dtstart") else "?"
        print(f"{dtstart}  {summary}")

def cmd_today(args):
    """List today's events."""
    args.days = 1
    cmd_list(args)

def cmd_add(args):
    """Add a calendar event."""
    client = get_client()
    calendar = client.principal().calendars()[0]
    vcal = f"""BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:{args.summary}
DTSTART:{args.start}
DTEND:{args.end}
END:VEVENT
END:VCALENDAR"""
    calendar.save_event(vcal)
    print(f"Created: {args.summary}")

def cmd_calendars(args):
    """List available calendars."""
    client = get_client()
    for cal in client.principal().calendars():
        print(cal.name)

def main():
    parser = argparse.ArgumentParser(prog="ical", description="Calendar management via CalDAV")
    sub = parser.add_subparsers(dest="command")

    p_list = sub.add_parser("list", help="List upcoming events")
    p_list.add_argument("--days", type=int, default=7, help="Days ahead (default: 7)")

    sub.add_parser("today", help="List today's events")

    p_add = sub.add_parser("add", help="Add an event")
    p_add.add_argument("summary", help="Event title")
    p_add.add_argument("start", help="Start time (ISO format)")
    p_add.add_argument("end", help="End time (ISO format)")

    sub.add_parser("calendars", help="List available calendars")

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(0)

    commands = {"list": cmd_list, "today": cmd_today, "add": cmd_add, "calendars": cmd_calendars}
    commands[args.command](args)

if __name__ == "__main__":
    main()
`;
}
