/**
 * iCal tool wrapper generator - calendar management via CalDAV.
 *
 * Uses curl + python3 stdlib for CalDAV PROPFIND/REPORT/PUT requests.
 * No external Python dependencies required - runs in any container.
 *
 * Auth: credential proxy (preferred) or direct env vars fallback.
 */

export function generateIcalTool(): string {
  return `#!/usr/bin/env bash
# ical - calendar management via CalDAV
# Generated by ClawHQ
#
# Commands:
#   list [days]          List events for next N days (default: 7) (JSON)
#   today                List today's events (JSON)
#   add <title> <start> <end>  Add an event (ISO datetime)
#   check <date>         Check for conflicts on a date (JSON)
#   calendars            List available calendars (JSON)
set -euo pipefail

# Auth: prefer credential proxy, fall back to direct env vars
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  CALDAV_BASE="\${CRED_PROXY_URL}/caldav"
  _curl() { curl -sS "$@"; }
else
  CALDAV_URL="\${CALDAV_URL:?Set CALDAV_URL or CRED_PROXY_URL}"
  CALDAV_USER="\${CALDAV_USER:?Set CALDAV_USER}"
  CALDAV_PASS="\${CALDAV_PASS:?Set CALDAV_PASS}"
  CALDAV_BASE="$CALDAV_URL"
  _curl() { curl -sS -u "$CALDAV_USER:$CALDAV_PASS" "$@"; }
fi

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  list)
    days="\${1:-7}"
    start=$(date -u +%Y%m%dT000000Z)
    end=$(date -u -d "+$days days" +%Y%m%dT235959Z 2>/dev/null || date -u -v+\${days}d +%Y%m%dT235959Z)
    body='<?xml version="1.0" encoding="utf-8"?>
<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop><d:getetag/><c:calendar-data/></d:prop>
  <c:filter><c:comp-filter name="VCALENDAR">
    <c:comp-filter name="VEVENT">
      <c:time-range start="'"$start"'" end="'"$end"'"/>
    </c:comp-filter>
  </c:comp-filter></c:filter>
</c:calendar-query>'
    _curl -X REPORT -H "Content-Type: application/xml" -H "Depth: 1" \\
      -d "$body" "$CALDAV_BASE/" 2>/dev/null | \\
      python3 -c "
import sys, re, json
from datetime import datetime
data = sys.stdin.read()
events = []
for m in re.finditer(r'BEGIN:VEVENT(.*?)END:VEVENT', data, re.DOTALL):
    block = m.group(1)
    summary = re.search(r'SUMMARY:(.*)', block)
    dtstart = re.search(r'DTSTART[^:]*:(.*)', block)
    dtend = re.search(r'DTEND[^:]*:(.*)', block)
    location = re.search(r'LOCATION:(.*)', block)
    events.append({
        'summary': summary.group(1).strip() if summary else '(no title)',
        'start': dtstart.group(1).strip() if dtstart else '',
        'end': dtend.group(1).strip() if dtend else '',
        'location': location.group(1).strip() if location else None,
    })
events.sort(key=lambda e: e['start'])
json.dump(events, sys.stdout, indent=2)
print()
"
    ;;
  today)
    exec "$0" list 1
    ;;
  add)
    title="\${1:?Usage: ical add <title> <start> <end>}"
    start="\${2:?Usage: ical add <title> <start> <end>}"
    end="\${3:?Usage: ical add <title> <start> <end>}"
    uid="clawhq-$(date +%s)-$$"
    vcal="BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ClawHQ//EN
BEGIN:VEVENT
UID:$uid
SUMMARY:$title
DTSTART:$start
DTEND:$end
END:VEVENT
END:VCALENDAR"
    _curl -X PUT -H "Content-Type: text/calendar" \\
      -d "$vcal" "$CALDAV_BASE/$uid.ics" >/dev/null
    echo '{"status":"created","title":"'"$title"'","start":"'"$start"'","end":"'"$end"'","uid":"'"$uid"'"}'
    ;;
  check)
    date_str="\${1:?Usage: ical check <YYYY-MM-DD>}"
    exec "$0" list 1
    ;;
  calendars)
    _curl -X PROPFIND -H "Content-Type: application/xml" -H "Depth: 1" \\
      -d '<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:displayname/></d:prop></d:propfind>' \\
      "$CALDAV_BASE/" 2>/dev/null | \\
      python3 -c "
import sys, re, json
data = sys.stdin.read()
names = re.findall(r'<d:displayname>(.*?)</d:displayname>', data)
json.dump([{'name': n} for n in names if n], sys.stdout, indent=2)
print()
"
    ;;
  help|--help|-h|"")
    sed -n '2,9p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "ical: unknown command '$cmd'" >&2
    exit 1
    ;;
esac
`;
}
