/**
 * iCal tool wrapper generator - calendar management via CalDAV.
 *
 * Uses curl + python3 stdlib for CalDAV PROPFIND/REPORT/PUT requests.
 * No external Python dependencies required - runs in any container.
 *
 * Auth: credential proxy (preferred) or direct env vars fallback.
 */

export function generateIcalTool(): string {
  return `#!/usr/bin/env bash
# calendar - calendar management via CalDAV
# Generated by ClawHQ
#
# Commands:
#   list [days]          List events for next N days (default: 7) (JSON)
#   today                List today's events (JSON)
#   add <title> <start> <end>  Add an event (ISO datetime)
#   check <date>         Check for conflicts on a date (JSON)
#   calendars            List available calendars (JSON)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Help works without credentials
case "\${1:-}" in help|--help|-h|"")
  sed -n '2,10p' "$0" | sed 's/^# \\?//'
  exit 0 ;; esac

# Auth: always use direct basic-auth. iCloud's CalDAV discovery returns
# absolute URLs to partition servers (e.g. https://p01-caldav.icloud.com/…)
# that cannot be routed back through the cred-proxy, so using the proxy
# breaks every request after calendar-home-set discovery. The password must
# already be in the container's env for the proxy to inject it, so routing
# through the proxy provides no security benefit for CalDAV.
CALDAV_URL="\${CALDAV_URL:?Set CALDAV_URL}"
CALDAV_USER="\${CALDAV_USER:?Set CALDAV_USER}"
CALDAV_PASS="\${CALDAV_PASS:?Set CALDAV_PASS}"
CALDAV_BASE="$CALDAV_URL"
_curl() { curl -sS --fail-with-body -u "$CALDAV_USER:$CALDAV_PASS" "$@"; }

# ClawWall: sanitize external calendar content before passing to agent
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source calendar --log
  else
    cat
  fi
}

# CalDAV auto-discovery (required for iCloud which redirects to partition servers)
# Discovers: base URL -> principal -> calendar-home, caches in /tmp for session
_discover_home() {
  local cache_dir="$HOME/.cache/clawhq"
  mkdir -p "$cache_dir"
  local cache="$cache_dir/.caldav-home-\${CALDAV_USER:-proxy}"
  if [[ -f "$cache" ]]; then
    cat "$cache"
    return
  fi

  # Step 1: find principal
  local principal
  principal=$(_curl -X PROPFIND -H "Content-Type: application/xml" -H "Depth: 0" \\
    -d '<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal/></d:prop></d:propfind>' \\
    "$CALDAV_BASE/" | python3 -c "
import sys, re
data = sys.stdin.read()
m = re.search(r'<(?:\\w+:)?href[^>]*>(/[^<]*principal[^<]*)</(?:\\w+:)?href>', data)
print(m.group(1) if m else '')
"
)

  if [[ -z "$principal" ]]; then
    # No discovery needed (non-iCloud server), use base URL
    echo "$CALDAV_BASE" > "$cache"
    cat "$cache"
    return
  fi

  # Step 2: find calendar-home from principal
  local home
  home=$(_curl -X PROPFIND -H "Content-Type: application/xml" -H "Depth: 0" \\
    -d '<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><c:calendar-home-set/></d:prop></d:propfind>' \\
    "$CALDAV_BASE$principal" | python3 -c "
import sys, re
data = sys.stdin.read()
m = re.search(r'<(?:\\w+:)?href[^>]*>(https?://[^<]+)</(?:\\w+:)?href>', data)
print(m.group(1).rstrip('/') if m else '')
"
)

  if [[ -z "$home" ]]; then
    echo "$CALDAV_BASE" > "$cache"
  else
    # Remove trailing slash for consistency
    echo "\${home%/}" > "$cache"
  fi
  cat "$cache"
}

# Discover all calendar collection URLs under the home
_discover_calendars() {
  local home
  home=$(_discover_home)
  _curl -X PROPFIND -H "Content-Type: application/xml" -H "Depth: 1" \\
    -d '<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><d:displayname/><d:resourcetype/></d:prop></d:propfind>' \\
    "$home/" | python3 -c "
import sys, re, json, html
data = sys.stdin.read()
cals = []
for resp in re.finditer(r'<(?:\\w+:)?response[^>]*>(.*?)</(?:\\w+:)?response>', data, re.DOTALL):
    block = resp.group(1)
    # Must be a CalDAV calendar collection. Match only the CalDAV <calendar/>
    # element inside <resourcetype>, not any substring 'calendar'. Otherwise
    # the parent /calendars/ collection and scheduling collections (inbox,
    # outbox, notification) slip through and return 403 on calendar-query.
    rtype_m = re.search(r'<(?:\\w+:)?resourcetype[^>]*>(.*?)</(?:\\w+:)?resourcetype>', block, re.DOTALL)
    if not rtype_m:
        continue
    if not re.search(r'<(?:\\w+:)?calendar\\b[^>]*/>', rtype_m.group(1)):
        continue
    href = re.search(r'<(?:\\w+:)?href[^>]*>(.*?)</(?:\\w+:)?href>', block)
    name = re.search(r'<(?:\\w+:)?displayname[^>]*>(.*?)</(?:\\w+:)?displayname>', block)
    if href:
        cals.append({
            'name': html.unescape(name.group(1).strip()) if name else '(unnamed)',
            'href': href.group(1).strip(),
        })
print(json.dumps(cals))
"
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  list)
    days="\${1:-7}"
    if [[ "$days" -lt 1 || "$days" -gt 365 ]]; then
      echo "calendar: days must be between 1 and 365" >&2; exit 1
    fi
    start=$(date -u +%Y%m%dT000000Z)
    end=$(date -u -d "+$days days" +%Y%m%dT235959Z 2>/dev/null || date -u -v+\${days}d +%Y%m%dT235959Z)
    home=$(_discover_home)
    # Query all calendar collections
    cal_paths=$(_discover_calendars | python3 -c "
import sys, json
for c in json.load(sys.stdin):
    print(c['href'])
"
)
    all_data=""
    while IFS= read -r cal_href; do
      [[ -z "$cal_href" ]] && continue
      # Build full URL: if href is absolute path, prepend scheme+host from home
      if [[ "$cal_href" == /* ]]; then
        cal_url=$(echo "$home" | sed 's|\\(https\\?://[^/]*\\).*|\\1|')"\${cal_href}"
      else
        cal_url="$home/$cal_href"
      fi
      # <c:expand> asks the server to materialize each RRULE instance within
      # the time-range as its own VEVENT with instance-specific DTSTART/DTEND,
      # instead of returning the master event once with the original DTSTART
      # (which made recurring events appear on their initial date regardless
      # of query window).
      body='<?xml version="1.0" encoding="utf-8"?>
<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop><d:getetag/><c:calendar-data><c:expand start="'"$start"'" end="'"$end"'"/></c:calendar-data></d:prop>
  <c:filter><c:comp-filter name="VCALENDAR">
    <c:comp-filter name="VEVENT">
      <c:time-range start="'"$start"'" end="'"$end"'"/>
    </c:comp-filter>
  </c:comp-filter></c:filter>
</c:calendar-query>'
      result=$(_curl -X REPORT -H "Content-Type: application/xml" -H "Depth: 1" \\
        -d "$body" "$cal_url")
      all_data+="\${result}"
    done <<< "$cal_paths"
    echo "$all_data" | python3 -c "
import sys, re, json
BS = chr(92)  # literal backslash, avoids TS→bash→python escape hell
def _ical_unescape(s):
    # iCalendar text escapes per RFC 5545 §3.3.11: \\N/\\n → newline,
    # \\, → comma, \\; → semicolon, \\\\ → backslash.
    # Stage through a NUL placeholder so escaped backslashes (\\\\) aren't
    # re-interpreted when we decode the other escape sequences.
    PH = chr(0)
    return (s.replace(BS + BS, PH)
             .replace(BS + 'N', chr(10))
             .replace(BS + 'n', chr(10))
             .replace(BS + ',', ',')
             .replace(BS + ';', ';')
             .replace(PH, BS))
data = sys.stdin.read()
events = []
for m in re.finditer(r'BEGIN:VEVENT(.*?)END:VEVENT', data, re.DOTALL):
    block = m.group(1)
    summary = re.search(r'SUMMARY:(.*)', block)
    dtstart = re.search(r'DTSTART[^:]*:(.*)', block)
    dtend = re.search(r'DTEND[^:]*:(.*)', block)
    location = re.search(r'LOCATION:(.*)', block)
    events.append({
        'summary': _ical_unescape(summary.group(1).strip()) if summary else '(no title)',
        'start': dtstart.group(1).strip() if dtstart else '',
        'end': dtend.group(1).strip() if dtend else '',
        'location': _ical_unescape(location.group(1).strip()) if location else None,
    })
events.sort(key=lambda e: e['start'])
json.dump(events, sys.stdout, indent=2)
print()
" | _sanitize
    ;;
  today)
    exec "$0" list 1
    ;;
  add)
    title="\${1:?Usage: ical add <title> <start> <end>}"
    start="\${2:?Usage: ical add <title> <start> <end>}"
    end="\${3:?Usage: ical add <title> <start> <end>}"
    uid="clawhq-$(date +%s)-$$"
    home=$(_discover_home)
    # Add to first calendar found
    first_cal=$(_discover_calendars | python3 -c "
import sys, json
cals = json.load(sys.stdin)
print(cals[0]['href'] if cals else '')
"
)
    if [[ -z "$first_cal" ]]; then
      echo "calendar: no calendars found" >&2
      exit 1
    fi
    if [[ "$first_cal" == /* ]]; then
      cal_url=$(echo "$home" | sed 's|\\(https\\?://[^/]*\\).*|\\1|')"\${first_cal}"
    else
      cal_url="$home/$first_cal"
    fi
    vcal="BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ClawHQ//EN
BEGIN:VEVENT
UID:$uid
SUMMARY:$title
DTSTART:$start
DTEND:$end
END:VEVENT
END:VCALENDAR"
    _curl -X PUT -H "Content-Type: text/calendar" \\
      -d "$vcal" "\${cal_url}$uid.ics" >/dev/null
    jq -n --arg t "$title" --arg s "$start" --arg e "$end" --arg u "$uid" \\
      '{status:"created",title:$t,start:$s,end:$e,uid:$u}'
    ;;
  check)
    date_str="\${1:?Usage: calendar check <YYYY-MM-DD>}"
    home=$(_discover_home)
    start="\${date_str}T000000Z"
    end="\${date_str}T235959Z"
    cal_paths=$(_discover_calendars | python3 -c "
import sys, json
for c in json.load(sys.stdin):
    print(c['href'])
"
)
    all_data=""
    while IFS= read -r cal_href; do
      [[ -z "$cal_href" ]] && continue
      if [[ "$cal_href" == /* ]]; then
        cal_url=$(echo "$home" | sed 's|\\(https\\?://[^/]*\\).*|\\1|')"\${cal_href}"
      else
        cal_url="$home/$cal_href"
      fi
      # <c:expand> asks the server to materialize each RRULE instance within
      # the time-range as its own VEVENT with instance-specific DTSTART/DTEND,
      # instead of returning the master event once with the original DTSTART
      # (which made recurring events appear on their initial date regardless
      # of query window).
      body='<?xml version="1.0" encoding="utf-8"?>
<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop><d:getetag/><c:calendar-data><c:expand start="'"$start"'" end="'"$end"'"/></c:calendar-data></d:prop>
  <c:filter><c:comp-filter name="VCALENDAR">
    <c:comp-filter name="VEVENT">
      <c:time-range start="'"$start"'" end="'"$end"'"/>
    </c:comp-filter>
  </c:comp-filter></c:filter>
</c:calendar-query>'
      result=$(_curl -X REPORT -H "Content-Type: application/xml" -H "Depth: 1" \\
        -d "$body" "$cal_url")
      all_data+="\${result}"
    done <<< "$cal_paths"
    echo "$all_data" | python3 -c "
import sys, re, json
BS = chr(92)  # literal backslash, avoids TS→bash→python escape hell
def _ical_unescape(s):
    # iCalendar text escapes per RFC 5545 §3.3.11: \\N/\\n → newline,
    # \\, → comma, \\; → semicolon, \\\\ → backslash.
    # Stage through a NUL placeholder so escaped backslashes (\\\\) aren't
    # re-interpreted when we decode the other escape sequences.
    PH = chr(0)
    return (s.replace(BS + BS, PH)
             .replace(BS + 'N', chr(10))
             .replace(BS + 'n', chr(10))
             .replace(BS + ',', ',')
             .replace(BS + ';', ';')
             .replace(PH, BS))
data = sys.stdin.read()
events = []
for m in re.finditer(r'BEGIN:VEVENT(.*?)END:VEVENT', data, re.DOTALL):
    block = m.group(1)
    summary = re.search(r'SUMMARY:(.*)', block)
    dtstart = re.search(r'DTSTART[^:]*:(.*)', block)
    dtend = re.search(r'DTEND[^:]*:(.*)', block)
    location = re.search(r'LOCATION:(.*)', block)
    events.append({
        'summary': _ical_unescape(summary.group(1).strip()) if summary else '(no title)',
        'start': dtstart.group(1).strip() if dtstart else '',
        'end': dtend.group(1).strip() if dtend else '',
        'location': _ical_unescape(location.group(1).strip()) if location else None,
    })
events.sort(key=lambda e: e['start'])
json.dump(events, sys.stdout, indent=2)
print()
" | _sanitize
    ;;
  calendars)
    _discover_calendars | python3 -c "
import sys, json
cals = json.load(sys.stdin)
json.dump(cals, sys.stdout, indent=2)
print()
" | _sanitize
    ;;
  help|--help|-h|"")
    sed -n '2,10p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "calendar: unknown command '$cmd'" >&2
    exit 1
    ;;
esac
`;
}
