/**
 * Journal tool wrapper generator - append-only markdown journal.
 *
 * Generates a bash script that manages an append-only markdown journal.
 * Entries are timestamped and optionally tagged. The journal file lives
 * at workspace/memory/journal.md. Entries can never be modified or
 * deleted - this is a permanent record of reflections and intentions.
 */

export function generateJournalTool(): string {
  return `#!/usr/bin/env bash
# journal - append-only markdown journal for reflections, intentions, and insights
# Generated by ClawHQ from blueprint config
set -euo pipefail

JOURNAL_FILE="\${JOURNAL_FILE:-\${OPENCLAW_HOME:-$HOME/.openclaw}/workspace/memory/journal.md}"

# Ensure journal file exists with header
if [ ! -f "$JOURNAL_FILE" ]; then
  mkdir -p "$(dirname "$JOURNAL_FILE")"
  printf '# Journal\\n\\nAppend-only record of reflections, intentions, and insights.\\n\\n' > "$JOURNAL_FILE"
fi

usage() {
  cat <<'USAGE'
Usage: journal <command> [args]

Commands:
  add <text> [--tag TAG]          Append a timestamped entry (tag: intention, reflection, insight, weekly-review)
  list [--days N] [--tag TAG]     List entries (default: all; --days N: last N days; --tag: filter by tag)
  count [--days N] [--tag TAG]    Count entries matching filters
  search <query>                  Search entries by keyword
USAGE
}

now_iso() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
today_date() { date -u +"%Y-%m-%d"; }

cmd_add() {
  local text=""
  local tag=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --tag) tag="$2"; shift 2 ;;
      *) if [ -z "$text" ]; then text="$1"; else text="$text $1"; fi; shift ;;
    esac
  done

  if [ -z "$text" ]; then
    echo "journal: entry text required" >&2
    exit 1
  fi

  local timestamp
  timestamp="$(now_iso)"
  local tag_str=""
  if [ -n "$tag" ]; then
    tag_str=" #$tag"
  fi

  printf '\\n## %s%s\\n\\n%s\\n' "$timestamp" "$tag_str" "$text" >> "$JOURNAL_FILE"
  echo "Logged:$tag_str $text (at $timestamp)"
}

cmd_list() {
  local days=""
  local tag=""
  local date_filter=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --days) days="$2"; shift 2 ;;
      --tag) tag="$2"; shift 2 ;;
      --date)
        if [ "$2" = "today" ]; then
          date_filter="$(today_date)"
        else
          date_filter="$2"
        fi
        shift 2
        ;;
      *) shift ;;
    esac
  done

  JOURNAL_FILE="$JOURNAL_FILE" DAYS="$days" TAG="$tag" DATE_FILTER="$date_filter" python3 -c "
import os, sys
from datetime import datetime, timedelta, timezone

jf = os.environ['JOURNAL_FILE']
days = os.environ.get('DAYS', '')
tag = os.environ.get('TAG', '')
date_filter = os.environ.get('DATE_FILTER', '')

with open(jf) as f:
    content = f.read()

# Split into entries (each starts with ## timestamp)
entries = []
current = []
for line in content.split('\\n'):
    if line.startswith('## 20') and current:
        entries.append('\\n'.join(current))
        current = [line]
    elif line.startswith('## 20'):
        current = [line]
    elif current:
        current.append(line)
if current:
    entries.append('\\n'.join(current))

now = datetime.now(timezone.utc)

for entry in entries:
    header = entry.split('\\n')[0]

    # Filter by tag
    if tag and f'#{tag}' not in header:
        continue

    # Filter by days
    if days:
        try:
            ts_str = header.replace('## ', '').split(' #')[0].strip()
            ts = datetime.fromisoformat(ts_str.replace('Z', '+00:00'))
            if (now - ts).days > int(days):
                continue
        except (ValueError, IndexError):
            continue

    # Filter by date
    if date_filter:
        if date_filter not in header:
            continue

    print(entry)
    print()
"
}

cmd_count() {
  local days=""
  local tag=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --days) days="$2"; shift 2 ;;
      --tag) tag="$2"; shift 2 ;;
      *) shift ;;
    esac
  done

  JOURNAL_FILE="$JOURNAL_FILE" DAYS="$days" TAG="$tag" python3 -c "
import os
from datetime import datetime, timedelta, timezone

jf = os.environ['JOURNAL_FILE']
days = os.environ.get('DAYS', '')
tag = os.environ.get('TAG', '')

with open(jf) as f:
    content = f.read()

count = 0
now = datetime.now(timezone.utc)

for line in content.split('\\n'):
    if not line.startswith('## 20'):
        continue
    if tag and f'#{tag}' not in line:
        continue
    if days:
        try:
            ts_str = line.replace('## ', '').split(' #')[0].strip()
            ts = datetime.fromisoformat(ts_str.replace('Z', '+00:00'))
            if (now - ts).days > int(days):
                continue
        except (ValueError, IndexError):
            continue
    count += 1

print(count)
"
}

cmd_search() {
  local query="$1"
  JOURNAL_FILE="$JOURNAL_FILE" QUERY="$query" python3 -c "
import os

jf = os.environ['JOURNAL_FILE']
query = os.environ['QUERY'].lower()

with open(jf) as f:
    content = f.read()

entries = []
current = []
for line in content.split('\\n'):
    if line.startswith('## 20') and current:
        entries.append('\\n'.join(current))
        current = [line]
    elif line.startswith('## 20'):
        current = [line]
    elif current:
        current.append(line)
if current:
    entries.append('\\n'.join(current))

for entry in entries:
    if query in entry.lower():
        print(entry)
        print()
"
}

case "\${1:-}" in
  add)     shift; cmd_add "\$@" ;;
  list)    shift; cmd_list "\$@" ;;
  count)   shift; cmd_count "\$@" ;;
  search)  shift; cmd_search "\${1:?query required}" ;;
  -h|--help|help|"") usage ;;
  *) echo "journal: unknown command '\$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
