/**
 * Plaid tool wrapper generator — read-only bank feed access via Plaid API.
 *
 * Implements a strict read-only financial data interface:
 *   accounts, balances, transactions, recurring, categories
 *
 * Architecturally cannot initiate transfers, payments, or account
 * modifications — no write endpoints are exposed.
 *
 * Supports two auth modes:
 * 1. Credential proxy (CRED_PROXY_URL) — token never enters container
 * 2. Direct API token (PLAID_CLIENT_ID + PLAID_SECRET + PLAID_ACCESS_TOKEN)
 *
 * All Plaid API calls are POST requests with JSON bodies.
 * Account numbers are masked to last-4 in all output.
 * External responses are piped through ClawWall sanitizer.
 */

export function generatePlaidTool(): string {
  return `#!/usr/bin/env bash
# plaid - read-only bank feed access via Plaid API
# Generated by ClawHQ
#
# Commands:
#   accounts                         List linked accounts
#   balances                         Current balances for all accounts
#   transactions [--days N]          Recent transactions (default: 30 days)
#   recurring                        Recurring transactions
#   categories                       Transaction category taxonomy
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Help works without credentials
case "\${1:-}" in help|--help|-h|"")
  grep '^#' "$0" | tail -n +2 | head -n 9 | sed 's/^# \\?//'
  exit 0 ;; esac

# Auth: prefer credential proxy (all 3 credentials injected by proxy),
# fall back to direct tokens in env vars
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  PLAID_API="\${CRED_PROXY_URL}/plaid"
  _plaid() {
    local endpoint="$1"; shift
    curl -sS --fail-with-body -X POST \\
      -H "Content-Type: application/json" \\
      -d "$@" "\${PLAID_API}\${endpoint}"
  }
else
  PLAID_ENV="\${PLAID_ENV:-production}"
  case "$PLAID_ENV" in
    sandbox)     PLAID_API="https://sandbox.plaid.com" ;;
    development) PLAID_API="https://development.plaid.com" ;;
    *)           PLAID_API="https://production.plaid.com" ;;
  esac
  CLIENT_ID="\${PLAID_CLIENT_ID:?Set PLAID_CLIENT_ID or CRED_PROXY_URL}"
  SECRET="\${PLAID_SECRET:?Set PLAID_SECRET or CRED_PROXY_URL}"
  ACCESS="\${PLAID_ACCESS_TOKEN:?Set PLAID_ACCESS_TOKEN or CRED_PROXY_URL}"
  _plaid() {
    local endpoint="$1"; shift
    local body="$1"
    body=$(printf '%s' "$body" | jq --arg c "$CLIENT_ID" --arg s "$SECRET" --arg a "$ACCESS" \\
      '. + {client_id: $c, secret: $s, access_token: $a}')
    curl -sS --fail-with-body -X POST \\
      -H "Content-Type: application/json" \\
      -d "$body" "\${PLAID_API}\${endpoint}"
  }
fi

# ClawWall: sanitize external content before passing to agent
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source plaid --log
  else
    cat
  fi
}

# Mask account numbers to last 4 digits for PII safety
_mask_accounts() {
  jq '
    (.. | objects | select(has("account_id"))) |=
      (if .mask then . else . + {mask: "****"} end) |
    del(.. | objects | .numbers? // empty)
  '
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  accounts)
    _plaid "/accounts/get" '{}' | jq '.accounts' | _mask_accounts | _sanitize
    ;;
  balances)
    _plaid "/accounts/balance/get" '{}' | jq '.accounts | [.[] | {
      name, mask, type, subtype,
      current: .balances.current,
      available: .balances.available,
      currency: .balances.iso_currency_code
    }]' | _mask_accounts | _sanitize
    ;;
  transactions)
    days=30
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --days) days="\${2:?--days requires a number}"; shift 2 ;;
        *) echo "plaid transactions: unknown option '$1'" >&2; exit 1 ;;
      esac
    done
    end_date=$(date +%Y-%m-%d)
    start_date=$(date -d "-\${days} days" +%Y-%m-%d 2>/dev/null || date -v-\${days}d +%Y-%m-%d)
    body=$(jq -n --arg s "$start_date" --arg e "$end_date" \\
      '{start_date: $s, end_date: $e, options: {count: 500, offset: 0}}')
    _plaid "/transactions/get" "$body" | jq '.transactions | [.[] | {
      date, name, amount, category: .category[0],
      merchant: .merchant_name, pending,
      account_mask: .account_id
    }]' | _mask_accounts | _sanitize
    ;;
  recurring)
    _plaid "/transactions/recurring/get" '{}' | jq '{
      inflows: [.inflow_streams[] | {description, amount, frequency, last_date: .last_date}],
      outflows: [.outflow_streams[] | {description, amount, frequency, last_date: .last_date}]
    }' | _sanitize
    ;;
  categories)
    # Categories endpoint doesn't require auth
    curl -sS --fail-with-body -X POST \\
      -H "Content-Type: application/json" \\
      -d '{}' "https://production.plaid.com/categories/get" \\
      | jq '.categories | [.[] | {id: .category_id, hierarchy}]' | _sanitize
    ;;
  help|--help|-h|"")
    grep '^#' "$0" | tail -n +2 | head -n 9 | sed 's/^# \\?//'
    ;;
  *)
    echo "plaid: unknown command '$cmd'" >&2
    grep '^#' "$0" | tail -n +2 | head -n 9 | sed 's/^# \\?//' >&2
    exit 1
    ;;
esac
`;
}
