/**
 * Quote tool wrapper generator - market data via Yahoo Finance API.
 *
 * Generates a bash script that fetches stock quotes, historical data,
 * and market summaries using Yahoo Finance's public API endpoints.
 * Routes through cred-proxy /yahoo prefix when available for egress control.
 * No API key required - uses public Yahoo Finance endpoints.
 */

export function generateQuoteTool(): string {
  return `#!/usr/bin/env bash
# quote - market data and financial quotes via Yahoo Finance
# Generated by ClawHQ
# All results piped through ClawWall sanitizer for prompt injection defense.
set -euo pipefail

# Auth: prefer credential proxy (egress control), fall back to direct
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/yahoo/v8/finance"
else
  API="https://query1.finance.yahoo.com/v8/finance"
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source quote --log
  else
    cat
  fi
}

usage() {
  cat <<'USAGE'
Usage: quote <command> [args]

Commands:
  get <symbol>                  Get current quote for a symbol
  batch <sym1,sym2,...>         Get quotes for multiple symbols
  history <symbol> [--range R]  Price history (range: 1d,5d,1mo,3mo,6mo,1y,5y)
  summary <symbol>              Detailed quote summary
USAGE
}

cmd_get() {
  local symbol
  symbol=$(echo "$1" | tr '[:lower:]' '[:upper:]')
  curl -sS --fail-with-body "$API/chart/\${symbol}?range=1d&interval=1d" \\
    -H "User-Agent: ClawHQ/1.0" | jq '{quote: (.chart.result[0].meta // {}) | {symbol, price: .regularMarketPrice, dayHigh: .regularMarketDayHigh, dayLow: .regularMarketDayLow, volume: .regularMarketVolume, fiftyTwoWeekHigh, fiftyTwoWeekLow, currency}}' | _sanitize
}

cmd_batch() {
  local symbols="$1"
  local results="[]"
  IFS=',' read -ra SYMS <<< "$(echo "$symbols" | tr '[:lower:]' '[:upper:]')"
  for sym in "\${SYMS[@]}"; do
    local data
    data=$(curl -sS --fail-with-body "$API/chart/\${sym}?range=1d&interval=1d" \\
      -H "User-Agent: ClawHQ/1.0" | jq '(.chart.result[0].meta // {}) | {symbol, price: .regularMarketPrice, dayHigh: .regularMarketDayHigh, dayLow: .regularMarketDayLow, volume: .regularMarketVolume, currency}')
    results=$(echo "$results" | jq --argjson d "$data" '. + [$d]')
  done
  echo "$results" | _sanitize
}

cmd_history() {
  local symbol="$1"
  local range="\${2:-1mo}"
  curl -sS --fail-with-body "$API/chart/$(echo "$symbol" | tr '[:lower:]' '[:upper:]')?range=$range&interval=1d" \\
    -H "User-Agent: ClawHQ/1.0" | _sanitize
}

cmd_summary() {
  local symbol
  symbol=$(echo "$1" | tr '[:lower:]' '[:upper:]')
  curl -sS --fail-with-body "$API/chart/\${symbol}?range=5d&interval=1d" \\
    -H "User-Agent: ClawHQ/1.0" | jq '{summary: (.chart.result[0].meta // {}) | {
      symbol,
      currency,
      price: .regularMarketPrice,
      dayHigh: .regularMarketDayHigh,
      dayLow: .regularMarketDayLow,
      volume: .regularMarketVolume,
      fiftyTwoWeekHigh,
      fiftyTwoWeekLow,
      previousClose: .chartPreviousClose,
      change: (if .regularMarketPrice and .chartPreviousClose then ((.regularMarketPrice - .chartPreviousClose) * 100 | round | . / 100) else null end),
      changePercent: (if .chartPreviousClose > 0 then (((.regularMarketPrice - .chartPreviousClose) / .chartPreviousClose * 10000 | round | . / 100)) else null end)
    }}' | _sanitize
}

case "\${1:-}" in
  get)     shift; cmd_get "\${1:?symbol required}" ;;
  batch)   shift; cmd_batch "\${1:?symbols required}" ;;
  history)
    shift
    symbol="\${1:?symbol required}"; shift
    range="1mo"
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --range) range="\${2:?--range requires a value}"; shift 2 ;;
        *) range="$1"; shift ;;
      esac
    done
    cmd_history "$symbol" "$range"
    ;;
  summary) shift; cmd_summary "\${1:?symbol required}" ;;
  -h|--help|help|"") usage ;;
  *) echo "quote: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
