/**
 * Quote tool wrapper generator - market data via Yahoo Finance API.
 *
 * Generates a bash script that fetches stock quotes, historical data,
 * and market summaries using Yahoo Finance's public API endpoints.
 * Routes through cred-proxy /yahoo prefix when available for egress control.
 * No API key required - uses public Yahoo Finance endpoints.
 */

export function generateQuoteTool(): string {
  return `#!/usr/bin/env bash
# quote - market data and financial quotes via Yahoo Finance
# Generated by ClawHQ
# All results piped through ClawWall sanitizer for prompt injection defense.
set -euo pipefail

# Auth: prefer credential proxy (egress control), fall back to direct
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/yahoo/v8/finance"
else
  API="https://query1.finance.yahoo.com/v8/finance"
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source quote --log
  else
    cat
  fi
}

usage() {
  cat <<'USAGE'
Usage: quote <command> [args]

Commands:
  get <symbol>                  Get current quote for a symbol
  batch <sym1,sym2,...>         Get quotes for multiple symbols
  history <symbol> [--range R]  Price history (range: 1d,5d,1mo,3mo,6mo,1y,5y)
  summary <symbol>              Detailed quote summary
USAGE
}

cmd_get() {
  local symbol="$1"
  curl -sS "$API/quote?symbols=$(echo "$symbol" | tr '[:lower:]' '[:upper:]')" \\
    -H "User-Agent: ClawHQ/1.0" | _sanitize
}

cmd_batch() {
  local symbols="$1"
  curl -sS "$API/quote?symbols=$(echo "$symbols" | tr '[:lower:]' '[:upper:]')" \\
    -H "User-Agent: ClawHQ/1.0" | _sanitize
}

cmd_history() {
  local symbol="$1"
  local range="\${2:-1mo}"
  curl -sS "$API/chart/$(echo "$symbol" | tr '[:lower:]' '[:upper:]')?range=$range&interval=1d" \\
    -H "User-Agent: ClawHQ/1.0" | _sanitize
}

cmd_summary() {
  local symbol="$1"
  curl -sS "$API/quote?symbols=$(echo "$symbol" | tr '[:lower:]' '[:upper:]')&fields=regularMarketPrice,regularMarketChange,regularMarketChangePercent,marketCap,fiftyTwoWeekHigh,fiftyTwoWeekLow,regularMarketVolume" \\
    -H "User-Agent: ClawHQ/1.0" | _sanitize
}

case "\${1:-}" in
  get)     shift; cmd_get "\${1:?symbol required}" ;;
  batch)   shift; cmd_batch "\${1:?symbols required}" ;;
  history) shift; cmd_history "\${1:?symbol required}" "\${2:-1mo}" ;;
  summary) shift; cmd_summary "\${1:?symbol required}" ;;
  -h|--help|help|"") usage ;;
  *) echo "quote: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
