/**
 * Substack tool wrapper generator — Substack reader with cookie auth.
 *
 * Each Substack publication has its own subdomain (pub.substack.com),
 * so this tool calls publication APIs directly (not through the proxy).
 * Cookie auth is injected from SUBSTACK_COOKIE env var for paid content.
 *
 * Subcommands: latest, search, read. Results piped through sanitize.
 */

export function generateSubstackTool(): string {
  return `#!/usr/bin/env bash
# substack - Substack newsletter reader
# Generated by ClawHQ
# All results piped through ClawWall sanitizer for prompt injection defense.
#
# Commands:
#   latest <publication>             Get latest posts from a publication (JSON)
#   search <publication> <query>     Search posts in a publication (JSON)
#   read <publication> <slug>        Read a specific post (JSON)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\$0")" && pwd)"
COOKIE="\${SUBSTACK_COOKIE:-}"

_curl() {
  if [[ -n "\$COOKIE" ]]; then
    curl -sS -H "Cookie: \$COOKIE" "\$@"
  else
    curl -sS "\$@"
  fi
}

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "\$SCRIPT_DIR/sanitize" ]]; then
    "\$SCRIPT_DIR/sanitize" --source substack --log
  else
    cat
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "\$cmd" in
  latest)
    pub="\${1:?Usage: substack latest <publication>}"
    _curl "https://\$pub.substack.com/api/v1/posts?limit=10" | _sanitize
    ;;
  search)
    pub="\${1:?Usage: substack search <publication> <query>}"
    query="\${*:2}"
    [[ -z "\$query" ]] && { echo "Usage: substack search <publication> <query>" >&2; exit 1; }
    encoded=\$(jq -rn --arg q "\$query" '\$q | @uri')
    _curl "https://\$pub.substack.com/api/v1/posts?query=\$encoded&limit=10" | _sanitize
    ;;
  read)
    pub="\${1:?Usage: substack read <publication> <slug>}"
    slug="\${2:?Usage: substack read <publication> <slug>}"
    _curl "https://\$pub.substack.com/api/v1/posts/\$slug" | _sanitize
    ;;
  help|--help|-h|"")
    sed -n '2,10p' "\$0" | sed 's/^# \\\\?//'
    ;;
  *)
    echo "substack: unknown command '\$cmd'" >&2
    exit 1
    ;;
esac
`;
}
