/**
 * Substack tool wrapper generator — Substack reader via credential proxy.
 *
 * Routes through cred-proxy /substack prefix with cookie auth for paid
 * content. Subcommands: latest, search, read. Results piped through
 * sanitize. Handles paid content via session cookies.
 *
 * Auth: credential proxy (preferred) or direct SUBSTACK_COOKIE fallback.
 */

export function generateSubstackTool(): string {
  return `#!/usr/bin/env bash
# substack - Substack newsletter reader
# Generated by ClawHQ
# All results piped through ClawWall sanitizer for prompt injection defense.
#
# Commands:
#   latest <publication>             Get latest posts from a publication (JSON)
#   search <publication> <query>     Search posts in a publication (JSON)
#   read <publication> <slug>        Read a specific post (JSON)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\$0")" && pwd)"

# Auth: prefer credential proxy, fall back to direct cookie
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/substack"
  _curl() { curl -sS "\$@"; }
else
  COOKIE="\${SUBSTACK_COOKIE:-}"
  _curl() {
    if [[ -n "\$COOKIE" ]]; then
      curl -sS -H "Cookie: \$COOKIE" "\$@"
    else
      curl -sS "\$@"
    fi
  }
fi

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "\$SCRIPT_DIR/sanitize" ]]; then
    "\$SCRIPT_DIR/sanitize" --source substack --log
  else
    cat
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "\$cmd" in
  latest)
    pub="\${1:?Usage: substack latest <publication>}"
    if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
      _curl "\$API/\$pub/api/v1/posts?limit=10"
    else
      _curl "https://\$pub.substack.com/api/v1/posts?limit=10"
    fi | _sanitize
    ;;
  search)
    pub="\${1:?Usage: substack search <publication> <query>}"
    query="\${*:2}"
    [[ -z "\$query" ]] && { echo "Usage: substack search <publication> <query>" >&2; exit 1; }
    encoded=\$(jq -rn --arg q "\$query" '\$q | @uri')
    if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
      _curl "\$API/\$pub/api/v1/posts?query=\$encoded&limit=10"
    else
      _curl "https://\$pub.substack.com/api/v1/posts?query=\$encoded&limit=10"
    fi | _sanitize
    ;;
  read)
    pub="\${1:?Usage: substack read <publication> <slug>}"
    slug="\${2:?Usage: substack read <publication> <slug>}"
    if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
      _curl "\$API/\$pub/api/v1/posts/\$slug"
    else
      _curl "https://\$pub.substack.com/api/v1/posts/\$slug"
    fi | _sanitize
    ;;
  help|--help|-h|"")
    sed -n '2,10p' "\$0" | sed 's/^# \\\\?//'
    ;;
  *)
    echo "substack: unknown command '\$cmd'" >&2
    exit 1
    ;;
esac
`;
}
