/**
 * Substack tool wrapper generator — Substack reader with cookie auth.
 *
 * Each Substack publication has its own subdomain (pub.substack.com),
 * so this tool calls publication APIs directly (not through the proxy).
 * Cookie auth is injected from SUBSTACK_COOKIE env var for paid content.
 *
 * Supports publication aliases via config/substack-aliases.json:
 *   { "mancini": "tradecompanion", "oc": "openclawunboxed" }
 *
 * Subcommands: latest, search, read. Results piped through sanitize.
 */

export function generateSubstackTool(): string {
  return `#!/usr/bin/env bash
# substack - Substack newsletter reader
# Generated by ClawHQ
# All results piped through ClawWall sanitizer for prompt injection defense.
#
# Commands:
#   list                             List the reader's Substack subscriptions (JSON)
#   latest <publication>             Get latest posts from a publication (JSON)
#   search <publication> <query>     Search posts in a publication (JSON)
#   read <publication> <slug>        Read a specific post (JSON)
#   aliases                          Show configured publication aliases (JSON)
#
# Publication aliases are loaded from config/substack-aliases.json.
# Example: { "mancini": "tradecompanion" } → "substack latest mancini" fetches tradecompanion.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COOKIE="\${SUBSTACK_COOKIE:-}"
ALIASES_FILE="\${SCRIPT_DIR}/config/substack-aliases.json"

# Resolve publication alias → subdomain
_resolve_pub() {
  local name="$1"
  if [[ -f "$ALIASES_FILE" ]] && command -v jq >/dev/null 2>&1; then
    local resolved
    resolved=$(jq -r --arg n "$name" '.[$n] // empty' "$ALIASES_FILE" 2>/dev/null)
    if [[ -n "$resolved" ]]; then
      echo "$resolved"
      return
    fi
  fi
  # No alias — use as-is (it's the subdomain)
  echo "$name"
}

_curl() {
  # -L follows redirects: custom-domain publications (e.g. example.com backed by
  # example.substack.com) 301 from the substack subdomain to the custom domain.
  if [[ -n "$COOKIE" ]]; then
    curl -sSL --fail-with-body -H "Cookie: $COOKIE" "$@"
  else
    curl -sSL --fail-with-body "$@"
  fi
}

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source substack --log
  else
    cat
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  list)
    # Substack's account-level subscriptions endpoint. Requires the reader's
    # session cookie. Response contains parallel subscriptions[] and
    # publications[] arrays joined by publication_id. 301s to /page_v2 — -L
    # follows it. Host is substack.com (not a publication subdomain).
    if [[ -z "$COOKIE" ]]; then
      echo "substack list: SUBSTACK_COOKIE not set (session cookie required)" >&2
      exit 1
    fi
    _curl "https://substack.com/api/v1/subscriptions" | \\
      jq '[
        .subscriptions[] as $s
        | (.publications[] | select(.id == $s.publication_id)) as $p
        | {
            subdomain: $p.subdomain,
            name: $p.name,
            membership_state: $s.membership_state,
            expiry: $s.expiry,
            is_favorite: $s.is_favorite,
            is_founding: $s.is_founding,
            subscribed_at: $s.created_at
          }
      ] | sort_by(.name)' 2>/dev/null | _sanitize
    ;;
  latest)
    pub=$(_resolve_pub "\${1:?Usage: substack latest <publication>}")
    _curl "https://$pub.substack.com/api/v1/posts?limit=10" | \\
      jq '[.[] | {title, slug, post_date, subtitle, audience, canonical_url, wordcount, description: .truncated_body_text[0:200]}]' 2>/dev/null | _sanitize
    ;;
  search)
    pub=$(_resolve_pub "\${1:?Usage: substack search <publication> <query>}")
    query="\${*:2}"
    [[ -z "$query" ]] && { echo "Usage: substack search <publication> <query>" >&2; exit 1; }
    encoded=$(jq -rn --arg q "$query" '$q | @uri')
    _curl "https://$pub.substack.com/api/v1/posts?query=$encoded&limit=10" | \\
      jq '[.[] | {title, slug, post_date, subtitle, audience, canonical_url, wordcount, description: .truncated_body_text[0:200]}]' 2>/dev/null | _sanitize
    ;;
  read)
    pub=$(_resolve_pub "\${1:?Usage: substack read <publication> <slug>}")
    slug="\${2:?Usage: substack read <publication> <slug>}"
    _curl "https://$pub.substack.com/api/v1/posts/$slug" | _sanitize
    ;;
  aliases)
    if [[ -f "$ALIASES_FILE" ]]; then
      jq '.' "$ALIASES_FILE"
    else
      echo "No aliases configured. Create $ALIASES_FILE"
    fi
    ;;
  help|--help|-h|"")
    sed -n '2,14p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "substack: unknown command '$cmd'" >&2
    exit 1
    ;;
esac
`;
}
