/**
 * Tasks tool wrapper generator — local work queue.
 *
 * Generates a bash script that manages a local JSON-based task queue.
 * This is the core task tool — always available, no external service needed.
 * Tasks are stored in workspace/memory/tasks.json.
 */

export function generateTasksTool(): string {
  return `#!/usr/bin/env bash
# tasks — local work queue for autonomous task execution
# Generated by ClawHQ from blueprint config
set -euo pipefail

TASKS_FILE="\${TASKS_FILE:-\${OPENCLAW_HOME:-$HOME/.openclaw}/workspace/memory/tasks.json}"

# Ensure tasks file exists
if [ ! -f "$TASKS_FILE" ]; then
  echo '[]' > "$TASKS_FILE"
fi

usage() {
  cat <<'USAGE'
Usage: tasks <command> [args]

Commands:
  list [--status STATUS]         List tasks (all, pending, done)
  add <title> [--priority P]     Add a task (priority: low, medium, high)
  done <id>                      Mark task as done
  remove <id>                    Remove a task
  clear [--done]                 Clear all tasks (--done: only completed)
  count                          Count pending tasks
USAGE
}

now_iso() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
gen_id() { head -c 8 /dev/urandom | od -An -tx1 | tr -d ' \\n'; }

cmd_list() {
  local status="\${1:-all}"
  if [ "$status" = "all" ]; then
    cat "$TASKS_FILE"
  else
    TASKS_FILE="$TASKS_FILE" FILTER_STATUS="$status" python3 -c "
import json, os, sys
tasks = json.load(open(os.environ['TASKS_FILE']))
for t in tasks:
    if t.get('status') == os.environ['FILTER_STATUS']:
        print(json.dumps(t))
"
  fi
}

cmd_add() {
  local title="$1"
  local priority="\${2:-medium}"
  local id
  id="$(gen_id)"
  local created
  created="$(now_iso)"
  TASKS_FILE="$TASKS_FILE" TASK_ID="$id" TASK_TITLE="$title" TASK_PRIORITY="$priority" TASK_CREATED="$created" python3 -c "
import json, os
tf = os.environ['TASKS_FILE']
tasks = json.load(open(tf))
tasks.append({
    'id': os.environ['TASK_ID'],
    'title': os.environ['TASK_TITLE'],
    'priority': os.environ['TASK_PRIORITY'],
    'status': 'pending',
    'created': os.environ['TASK_CREATED']
})
json.dump(tasks, open(tf, 'w'), indent=2)
print(f'Added: {os.environ[\"TASK_TITLE\"]} (id: {os.environ[\"TASK_ID\"]})')
"
}

cmd_done() {
  local id="$1"
  TASKS_FILE="$TASKS_FILE" TASK_ID="$id" python3 -c "
import json, os, sys
tf = os.environ['TASKS_FILE']
tid = os.environ['TASK_ID']
tasks = json.load(open(tf))
found = False
for t in tasks:
    if t['id'] == tid:
        t['status'] = 'done'
        found = True
        print(f'Done: {t[\"title\"]}')
if not found:
    print(f'Task not found: {tid}', file=sys.stderr)
    sys.exit(1)
json.dump(tasks, open(tf, 'w'), indent=2)
"
}

cmd_remove() {
  local id="$1"
  TASKS_FILE="$TASKS_FILE" TASK_ID="$id" python3 -c "
import json, os, sys
tf = os.environ['TASKS_FILE']
tid = os.environ['TASK_ID']
tasks = json.load(open(tf))
new_tasks = [t for t in tasks if t['id'] != tid]
if len(new_tasks) == len(tasks):
    print(f'Task not found: {tid}', file=sys.stderr)
    sys.exit(1)
json.dump(new_tasks, open(tf, 'w'), indent=2)
print(f'Removed task: {tid}')
"
}

cmd_clear() {
  local only_done="\${1:-}"
  if [ "$only_done" = "--done" ]; then
    TASKS_FILE="$TASKS_FILE" python3 -c "
import json, os
tf = os.environ['TASKS_FILE']
tasks = json.load(open(tf))
tasks = [t for t in tasks if t.get('status') != 'done']
json.dump(tasks, open(tf, 'w'), indent=2)
print('Cleared completed tasks')
"
  else
    echo '[]' > "$TASKS_FILE"
    echo "Cleared all tasks"
  fi
}

cmd_count() {
  TASKS_FILE="$TASKS_FILE" python3 -c "
import json, os
tasks = json.load(open(os.environ['TASKS_FILE']))
pending = sum(1 for t in tasks if t.get('status') == 'pending')
print(pending)
"
}

case "\${1:-}" in
  list)    shift; cmd_list "\${1:-all}" ;;
  add)     shift; cmd_add "\${1:?title required}" "\${2:-medium}" ;;
  done)    shift; cmd_done "\${1:?id required}" ;;
  remove)  shift; cmd_remove "\${1:?id required}" ;;
  clear)   shift; cmd_clear "\${1:-}" ;;
  count)   cmd_count ;;
  -h|--help|help|"") usage ;;
  *) echo "tasks: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
