/**
 * Tavily tool wrapper generator — web research via Tavily API.
 *
 * Generates a bash script that wraps curl calls to Tavily's search API.
 * API key comes from TAVILY_API_KEY environment variable.
 */

export function generateTavilyTool(): string {
  return `#!/usr/bin/env bash
# tavily — web research via Tavily API
# Generated by ClawHQ from blueprint config
set -euo pipefail

API="https://api.tavily.com"
KEY="\${TAVILY_API_KEY:?TAVILY_API_KEY not set}"

usage() {
  cat <<'USAGE'
Usage: tavily <command> [args]

Commands:
  search <query> [--depth basic|advanced]   Search the web (default: basic)
  extract <url>                             Extract content from a URL
USAGE
}

cmd_search() {
  local query="$1"
  local depth="\${2:-basic}"
  curl -sS -X POST "$API/search" \\
    -H "Content-Type: application/json" \\
    -d "{
      \\"api_key\\": \\"$KEY\\",
      \\"query\\": \\"$query\\",
      \\"search_depth\\": \\"$depth\\",
      \\"include_answer\\": true,
      \\"max_results\\": 5
    }"
}

cmd_extract() {
  local url="$1"
  curl -sS -X POST "$API/extract" \\
    -H "Content-Type: application/json" \\
    -d "{
      \\"api_key\\": \\"$KEY\\",
      \\"urls\\": [\\"$url\\"]
    }"
}

case "\${1:-}" in
  search)  shift; cmd_search "\${1:?query required}" "\${2:-basic}" ;;
  extract) shift; cmd_extract "\${1:?url required}" ;;
  -h|--help|help|"") usage ;;
  *) echo "tavily: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
