/**
 * Tavily tool wrapper generator — web research via Tavily API.
 *
 * Generates a bash script that wraps curl calls to Tavily's search API.
 * API key comes from TAVILY_API_KEY environment variable.
 */

export function generateTavilyTool(): string {
  return `#!/usr/bin/env bash
# tavily — web research via Tavily API
# Generated by ClawHQ from blueprint config
# All results piped through ClawWall sanitizer for prompt injection defense.
# API key injected by credential proxy — never in this container.
set -euo pipefail

# Credential proxy injects the API key; tool never sees the secret.
PROXY="\${CRED_PROXY_URL:?CRED_PROXY_URL not set — credential proxy not configured}"
API="\${PROXY}/tavily"
TOOLS_DIR="$(cd "$(dirname "$0")" && pwd)"
SANITIZE="\${TOOLS_DIR}/sanitize"

# Pipe output through ClawWall sanitizer if available.
pipe_sanitize() {
  if [ -x "$SANITIZE" ]; then
    "$SANITIZE" --source tavily --strict --wrap
  else
    cat
  fi
}

usage() {
  cat <<'USAGE'
Usage: tavily <command> [args]

Commands:
  search <query> [--depth basic|advanced]   Search the web (default: basic)
  extract <url>                             Extract content from a URL
USAGE
}

cmd_search() {
  local query="$1"
  local depth="\${2:-basic}"
  local payload
  payload=$(jq -n --arg q "$query" --arg d "$depth" '{
    query: $q,
    search_depth: $d,
    include_answer: true,
    max_results: 5
  }')
  curl -sS -X POST "$API/search" \\
    -H "Content-Type: application/json" \\
    -d "$payload" | pipe_sanitize
}

cmd_extract() {
  local url="$1"
  local payload
  payload=$(jq -n --arg u "$url" '{
    urls: [$u]
  }')
  curl -sS -X POST "$API/extract" \\
    -H "Content-Type: application/json" \\
    -d "$payload" | pipe_sanitize
}

case "\${1:-}" in
  search)  shift; cmd_search "\${1:?query required}" "\${2:-basic}" ;;
  extract) shift; cmd_extract "\${1:?url required}" ;;
  -h|--help|help|"") usage ;;
  *) echo "tavily: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
