/**
 * Tavily tool wrapper generator - web search and research.
 *
 * Purpose-built for AI agents. Structured JSON output with sources.
 * Supports basic (fast) and advanced (deep) search modes.
 * All results piped through ClawWall sanitizer - external content
 * may contain prompt injection payloads.
 *
 * Auth: credential proxy (preferred) or direct API key fallback.
 */

export function generateTavilyTool(): string {
  return `#!/usr/bin/env bash
# search - web search and research via Tavily API
# Generated by ClawHQ
#
# Commands:
#   search <query>                   Quick search (JSON with sources)
#   research <query>                 Deep research with more results (JSON)
#   extract <url>                    Extract content from URL (JSON)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Help works without credentials
case "\${1:-}" in help|--help|-h|"")
  sed -n '2,8p' "$0" | sed 's/^# \\?//'
  exit 0 ;; esac

# Auth: prefer credential proxy, fall back to direct token
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/tavily"
  _search() {
    local body=$(jq -n --arg q "$1" --arg d "$2" --argjson n "$3" \\
      '{query: $q, search_depth: $d, max_results: $n, include_answer: true}')
    curl -sS --fail-with-body -X POST -H "Content-Type: application/json" -d "$body" "$API/search"
  }
  _extract() {
    curl -sS --fail-with-body -X POST -H "Content-Type: application/json" \\
      -d "$(jq -n --arg u "$1" '{urls: [$u]}')" "$API/extract"
  }
else
  API="https://api.tavily.com"
  TOKEN="\${TAVILY_API_KEY:?Set TAVILY_API_KEY or CRED_PROXY_URL}"
  _search() {
    local body=$(jq -n --arg q "$1" --arg d "$2" --argjson n "$3" --arg k "$TOKEN" \\
      '{api_key: $k, query: $q, search_depth: $d, max_results: $n, include_answer: true}')
    curl -sS --fail-with-body -X POST -H "Content-Type: application/json" -d "$body" "$API/search"
  }
  _extract() {
    curl -sS --fail-with-body -X POST -H "Content-Type: application/json" \\
      -d "$(jq -n --arg u "$1" --arg k "$TOKEN" '{api_key: $k, urls: [$u]}')" "$API/extract"
  }
fi

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source search --log
  else
    cat
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  search)
    _search "\${*:?Usage: tavily search <query>}" "basic" 5 | _sanitize
    ;;
  research)
    _search "\${*:?Usage: tavily research <query>}" "advanced" 10 | _sanitize
    ;;
  extract)
    _extract "\${1:?Usage: tavily extract <url>}" | _sanitize
    ;;
  help|--help|-h|"")
    sed -n '2,8p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "search: unknown command '$cmd'" >&2
    exit 1
    ;;
esac
`;
}
