/**
 * Todoist tool wrapper generator — task tracking via Todoist REST API.
 *
 * Generates a bash script that wraps curl calls to the Todoist REST API v2.
 * API token comes from TODOIST_API_TOKEN environment variable.
 */

export function generateTodoistTool(): string {
  return `#!/usr/bin/env bash
# todoist — task tracking via Todoist REST API
# Generated by ClawHQ from blueprint config
set -euo pipefail

API="https://api.todoist.com/rest/v2"
TOKEN="\${TODOIST_API_TOKEN:?TODOIST_API_TOKEN not set}"

auth_header="Authorization: Bearer $TOKEN"

usage() {
  cat <<'USAGE'
Usage: todoist <command> [args]

Commands:
  list [--project PROJECT]      List active tasks
  add <content> [--project P]   Add a task
  close <id>                    Complete a task
  delete <id>                   Delete a task
  projects                      List projects
  get <id>                      Get task details
USAGE
}

cmd_list() {
  local project="\${1:-}"
  local url="$API/tasks"
  if [ -n "$project" ]; then
    url="$url?project_id=$project"
  fi
  curl -sS -H "$auth_header" "$url"
}

cmd_add() {
  local content="$1"
  local project="\${2:-}"
  local body
  if [ -n "$project" ]; then
    body=$(jq -n --arg c "$content" --arg p "$project" '{content: $c, project_id: $p}')
  else
    body=$(jq -n --arg c "$content" '{content: $c}')
  fi
  curl -sS -X POST -H "$auth_header" -H "Content-Type: application/json" -d "$body" "$API/tasks"
}

cmd_close() {
  local id="$1"
  curl -sS -X POST -H "$auth_header" "$API/tasks/$id/close"
  echo "Closed task: $id"
}

cmd_delete() {
  local id="$1"
  curl -sS -X DELETE -H "$auth_header" "$API/tasks/$id"
  echo "Deleted task: $id"
}

cmd_projects() {
  curl -sS -H "$auth_header" "$API/projects"
}

cmd_get() {
  local id="$1"
  curl -sS -H "$auth_header" "$API/tasks/$id"
}

case "\${1:-}" in
  list)     shift; cmd_list "\${1:-}" ;;
  add)      shift; cmd_add "\${1:?content required}" "\${2:-}" ;;
  close)    shift; cmd_close "\${1:?id required}" ;;
  delete)   shift; cmd_delete "\${1:?id required}" ;;
  projects) cmd_projects ;;
  get)      shift; cmd_get "\${1:?id required}" ;;
  -h|--help|help|"") usage ;;
  *) echo "todoist: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
