/**
 * Todoist tool wrapper generator — task tracking via Todoist REST API v1.
 *
 * Implements the standard ClawHQ task CLI interface:
 *   list, today, overdue, search, get, add, update, complete, reopen,
 *   delete, move, projects, project, comment, comments
 *
 * This is the reference implementation for the task tool interface.
 * Other providers (Asana, TickTick, etc.) should implement the same
 * command surface with provider-specific API calls.
 *
 * Supports two auth modes:
 * 1. Credential proxy (CRED_PROXY_URL) — token never enters container
 * 2. Direct API token (TODOIST_API_KEY) — fallback when no proxy
 *
 * All list endpoints use cursor-based pagination and return flat JSON arrays.
 * Filter queries use the dedicated /tasks/filter endpoint.
 * External responses are piped through ClawWall sanitizer.
 */

export function generateTodoistTool(): string {
  return `#!/usr/bin/env bash
# tasks - task tracking via Todoist REST API v1
# Generated by ClawHQ
#
# Commands:
#   list [--project ID]                                   List active tasks
#   today                                                 Tasks due today
#   overdue                                               Overdue tasks
#   search <filter>                                       Filter tasks (Todoist filter syntax)
#   get <id>                                              Get single task details
#   add <content> [--project ID] [--due DATE] [--priority 1-4]  Add a task
#   update <id> [--content TEXT] [--due DATE] [--priority 1-4]  Update a task
#   complete <id>                                         Complete a task
#   reopen <id>                                           Reopen a completed task
#   delete <id>                                           Delete a task
#   move <id> --project <id>                              Move task to another project
#   projects                                              List all projects
#   project <id>                                          Full project with tasks and sections
#   comment <id> <text>                                   Add comment to task
#   comments <id>                                         List comments on task
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Help works without credentials
case "\${1:-}" in help|--help|-h|"")
  grep '^#' "$0" | tail -n +2 | head -n 19 | sed 's/^# \\?//'
  exit 0 ;; esac

# Auth: prefer credential proxy, fall back to direct token
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/todoist"
  _curl() { curl -sS --fail-with-body "$@"; }
else
  API="https://api.todoist.com/api/v1"
  TOKEN="\${TODOIST_API_KEY:?Set TODOIST_API_KEY or CRED_PROXY_URL}"
  _curl() { curl -sS --fail-with-body -H "Authorization: Bearer $TOKEN" "$@"; }
fi

# ClawWall: sanitize external content before passing to agent
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source tasks --log
  else
    cat
  fi
}

# Paginate through all pages of a v1 endpoint.
# Collects .results arrays, follows next_cursor until exhausted.
# Returns a flat JSON array. Max 20 pages as safety limit.
_fetch_all() {
  local path="$1"
  local extra="\${2:-}"
  local cursor=""
  local all="[]"
  local max_pages=20
  local page_num=0
  while true; do
    local params=""
    [[ -n "$extra" ]] && params="$extra"
    if [[ -n "$cursor" ]]; then
      [[ -n "$params" ]] && params="\${params}&cursor=\${cursor}" || params="cursor=\${cursor}"
    fi
    local url="$API$path"
    [[ -n "$params" ]] && url="\${url}?\${params}"
    local resp
    resp=$(_curl "$url") || { echo "tasks: API request failed" >&2; return 1; }
    local page
    page=$(printf '%s' "$resp" | jq '.results // empty')
    if [[ -z "$page" ]]; then
      printf '%s\\n' "$resp"
      return
    fi
    all=$(printf '%s\\n%s' "$all" "$page" | jq -s '.[0] + .[1]')
    cursor=$(printf '%s' "$resp" | jq -r '.next_cursor // empty')
    if [[ -z "$cursor" ]]; then
      break
    fi
    page_num=$((page_num + 1))
    if [[ "$page_num" -ge "$max_pages" ]]; then
      echo "tasks: warning: hit $max_pages page limit, results may be incomplete" >&2
      break
    fi
  done
  printf '%s\\n' "$all"
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  list)
    project=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --project) project="\${2:?--project requires an ID}"; shift 2 ;;
        *) project="$1"; shift ;;
      esac
    done
    if [[ -n "$project" ]]; then
      _fetch_all "/tasks" "project_id=$project" | _sanitize
    else
      _fetch_all "/tasks" | _sanitize
    fi
    ;;
  today)
    _fetch_all "/tasks/filter" "query=today" | _sanitize
    ;;
  overdue)
    _fetch_all "/tasks/filter" "query=overdue" | _sanitize
    ;;
  search)
    filter="\${1:?Usage: todoist search <filter>}"
    encoded=$(jq -rn --arg q "$filter" '$q|@uri')
    _fetch_all "/tasks/filter" "query=$encoded" | _sanitize
    ;;
  get)
    id="\${1:?Usage: todoist get <id>}"
    _curl "$API/tasks/$id" | _sanitize
    ;;
  add)
    content="\${1:?Usage: todoist add <content> [--project ID] [--due DATE] [--priority 1-4]}"
    shift
    project="" due="" priority=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --project) project="\${2:?--project requires an ID}"; shift 2 ;;
        --due) due="\${2:?--due requires a date string}"; shift 2 ;;
        --priority) priority="\${2:?--priority requires 1-4}"; shift 2 ;;
        *) echo "tasks add: unknown option '$1'" >&2; exit 1 ;;
      esac
    done
    body=$(jq -n \\
      --arg c "$content" \\
      --arg p "$project" \\
      --arg d "$due" \\
      --arg pr "$priority" \\
      '{content: $c}
       + (if $p  != "" then {project_id: $p} else {} end)
       + (if $d  != "" then {due_string: $d} else {} end)
       + (if $pr != "" then {priority: ($pr | tonumber)} else {} end)')
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/tasks" | _sanitize
    ;;
  update)
    id="\${1:?Usage: todoist update <id> [--content TEXT] [--due DATE] [--priority 1-4]}"
    shift
    content="" due="" priority=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --content) content="\${2:?--content requires text}"; shift 2 ;;
        --due) due="\${2:?--due requires a date string}"; shift 2 ;;
        --priority) priority="\${2:?--priority requires 1-4}"; shift 2 ;;
        *) content="$1"; shift ;;
      esac
    done
    if [[ -z "$content" && -z "$due" && -z "$priority" ]]; then
      echo "tasks update: provide at least one of --content, --due, or --priority" >&2
      exit 1
    fi
    body=$(jq -n \\
      --arg c "$content" \\
      --arg d "$due" \\
      --arg pr "$priority" \\
      '(if $c  != "" then {content: $c} else {} end)
       + (if $d  != "" then {due_string: $d} else {} end)
       + (if $pr != "" then {priority: ($pr | tonumber)} else {} end)')
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/tasks/$id" | _sanitize
    ;;
  complete)
    id="\${1:?Usage: todoist complete <id>}"
    _curl -X POST "$API/tasks/$id/close" > /dev/null
    jq -n --arg id "$id" '{status:"completed",id:$id}'
    ;;
  reopen)
    id="\${1:?Usage: todoist reopen <id>}"
    _curl -X POST "$API/tasks/$id/reopen" > /dev/null
    jq -n --arg id "$id" '{status:"reopened",id:$id}'
    ;;
  delete)
    id="\${1:?Usage: todoist delete <id>}"
    _curl -X DELETE "$API/tasks/$id" > /dev/null
    jq -n --arg id "$id" '{status:"deleted",id:$id}'
    ;;
  move)
    id="\${1:?Usage: todoist move <id> --project <project_id>}"
    shift
    target_project=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --project) target_project="\${2:?--project requires an ID}"; shift 2 ;;
        *) echo "tasks move: unknown option '$1'" >&2; exit 1 ;;
      esac
    done
    if [[ -z "$target_project" ]]; then
      echo "tasks move: --project is required" >&2
      exit 1
    fi
    body=$(jq -n --arg p "$target_project" '{project_id: $p}')
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/tasks/$id/move" | _sanitize
    ;;
  comment)
    id="\${1:?Usage: todoist comment <id> <text>}"
    text="\${2:?Usage: todoist comment <id> <text>}"
    body=$(jq -n --arg c "$text" --arg t "$id" '{task_id: $t, content: $c}')
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/comments" | _sanitize
    ;;
  comments)
    id="\${1:?Usage: todoist comments <id>}"
    _fetch_all "/comments" "task_id=$id" | _sanitize
    ;;
  projects)
    _fetch_all "/projects" | _sanitize
    ;;
  project)
    id="\${1:?Usage: todoist project <id>}"
    _curl "$API/projects/$id/full" | _sanitize
    ;;
  help|--help|-h|"")
    grep '^#' "$0" | tail -n +2 | head -n 19 | sed 's/^# \\?//'
    ;;
  *)
    echo "tasks: unknown command '$cmd'" >&2
    grep '^#' "$0" | tail -n +2 | head -n 19 | sed 's/^# \\?//' >&2
    exit 1
    ;;
esac
`;
}
