/**
 * Todoist-sync tool wrapper generator — task alerts and reminders.
 *
 * Generates a bash script that uses the Todoist Sync API for
 * deadline alerts, overdue detection, and follow-up reminders.
 * API token comes from TODOIST_API_TOKEN environment variable.
 */

export function generateTodoistSyncTool(): string {
  return `#!/usr/bin/env bash
# todoist-sync — task deadline alerts and follow-up reminders
# Generated by ClawHQ from blueprint config
set -euo pipefail

API="https://api.todoist.com/sync/v9"
TOKEN="\${TODOIST_API_TOKEN:?TODOIST_API_TOKEN not set}"

usage() {
  cat <<'USAGE'
Usage: todoist-sync <command> [args]

Commands:
  overdue                       List overdue tasks
  due-today                     List tasks due today
  due-soon [--days N]           List tasks due within N days (default: 3)
  activity [--count N]          Recent activity log (default: 20)
  sync                          Full sync — fetch latest state
USAGE
}

sync_request() {
  local resource_types="$1"
  curl -sS -X POST "$API/sync" \\
    -H "Authorization: Bearer $TOKEN" \\
    -H "Content-Type: application/x-www-form-urlencoded" \\
    -d "sync_token=*&resource_types=[\\"$resource_types\\"]"
}

cmd_overdue() {
  python3 -c "
import json, subprocess, sys
from datetime import datetime, timezone

result = subprocess.run(
    ['curl', '-sS', '-H', 'Authorization: Bearer $TOKEN', 'https://api.todoist.com/rest/v2/tasks'],
    capture_output=True, text=True
)
tasks = json.loads(result.stdout)
now = datetime.now(timezone.utc)
for t in tasks:
    due = t.get('due')
    if due and due.get('date'):
        due_date = datetime.fromisoformat(due['date'].replace('Z', '+00:00'))
        if hasattr(due_date, 'tzinfo') and due_date.tzinfo is None:
            from datetime import date
            if isinstance(due_date, datetime):
                due_date = due_date.replace(tzinfo=timezone.utc)
        if due_date.date() < now.date() if hasattr(due_date, 'date') else True:
            print(f"OVERDUE: {t['content']} (due: {due['date']})")
"
}

cmd_due_today() {
  python3 -c "
import json, subprocess
from datetime import date

result = subprocess.run(
    ['curl', '-sS', '-H', 'Authorization: Bearer $TOKEN', 'https://api.todoist.com/rest/v2/tasks'],
    capture_output=True, text=True
)
tasks = json.loads(result.stdout)
today = date.today().isoformat()
for t in tasks:
    due = t.get('due')
    if due and due.get('date', '').startswith(today):
        print(f"{t['content']} (due: {due['date']})")
"
}

cmd_due_soon() {
  local days="\${1:-3}"
  python3 -c "
import json, subprocess
from datetime import date, timedelta

result = subprocess.run(
    ['curl', '-sS', '-H', 'Authorization: Bearer $TOKEN', 'https://api.todoist.com/rest/v2/tasks'],
    capture_output=True, text=True
)
tasks = json.loads(result.stdout)
cutoff = (date.today() + timedelta(days=$days)).isoformat()
today = date.today().isoformat()
for t in tasks:
    due = t.get('due')
    if due and due.get('date'):
        d = due['date'][:10]
        if today <= d <= cutoff:
            print(f"{t['content']} (due: {due['date']})")
"
}

cmd_activity() {
  local count="\${1:-20}"
  curl -sS -H "Authorization: Bearer $TOKEN" \\
    "$API/activity/get?limit=$count"
}

cmd_sync() {
  sync_request "items"
}

case "\${1:-}" in
  overdue)   cmd_overdue ;;
  due-today) cmd_due_today ;;
  due-soon)  shift; cmd_due_soon "\${1:-3}" ;;
  activity)  shift; cmd_activity "\${1:-20}" ;;
  sync)      cmd_sync ;;
  -h|--help|help|"") usage ;;
  *) echo "todoist-sync: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
