/**
 * Todoist-sync tool wrapper generator — task alerts and deadline monitoring.
 *
 * Generates a bash script that uses the Todoist REST API v1 filter endpoint
 * for deadline alerts, overdue detection, and upcoming task summaries.
 * Designed for cron-triggered monitoring — complements the main todoist tool.
 * External responses are piped through ClawWall sanitizer.
 */

export function generateTodoistSyncTool(): string {
  return `#!/usr/bin/env bash
# todoist-sync - task deadline alerts and monitoring via Todoist REST API v1
# Generated by ClawHQ from blueprint config
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Auth: prefer credential proxy, fall back to direct token
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/todoist"
  _curl() { curl -sS --fail-with-body "$@"; }
else
  API="https://api.todoist.com/api/v1"
  TOKEN="\${TODOIST_API_KEY:?Set TODOIST_API_KEY or CRED_PROXY_URL}"
  _curl() { curl -sS --fail-with-body -H "Authorization: Bearer $TOKEN" "$@"; }
fi

usage() {
  cat <<'USAGE'
Usage: todoist-sync <command> [args]

Commands:
  overdue                       List overdue tasks
  due-today                     List tasks due today
  due-soon [--days N]           List tasks due within N days (default: 3)
  activity [--count N]          Recent activity log (default: 20)
USAGE
}

# ClawWall: sanitize external content before passing to agent
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source tasks --log
  else
    cat
  fi
}

# Paginate through all pages, returning flat JSON array of .results.
# Max 20 pages as safety limit.
_fetch_all() {
  local path="$1"
  local extra="\${2:-}"
  local cursor=""
  local all="[]"
  local max_pages=20
  local page_num=0
  while true; do
    local params=""
    [[ -n "$extra" ]] && params="$extra"
    if [[ -n "$cursor" ]]; then
      [[ -n "$params" ]] && params="\${params}&cursor=\${cursor}" || params="cursor=\${cursor}"
    fi
    local url="$API$path"
    [[ -n "$params" ]] && url="\${url}?\${params}"
    local resp
    resp=$(_curl "$url") || { echo "tasks: API request failed" >&2; return 1; }
    local page
    page=$(printf '%s' "$resp" | jq '.results // empty')
    if [[ -z "$page" ]]; then
      printf '%s\\n' "$resp"
      return
    fi
    all=$(printf '%s\\n%s' "$all" "$page" | jq -s '.[0] + .[1]')
    cursor=$(printf '%s' "$resp" | jq -r '.next_cursor // empty')
    if [[ -z "$cursor" ]]; then
      break
    fi
    page_num=$((page_num + 1))
    if [[ "$page_num" -ge "$max_pages" ]]; then
      echo "tasks: warning: hit $max_pages page limit, results may be incomplete" >&2
      break
    fi
  done
  printf '%s\\n' "$all"
}

# Format tasks as human-readable lines for cron alerts.
_format_tasks() {
  jq -r '.[] | "  \\(.content) (due: \\(.due.date // "none"), project: \\(.project_id))"'
}

cmd_overdue() {
  local tasks
  tasks=$(_fetch_all "/tasks/filter" "query=overdue") || return 1
  local count
  count=$(printf '%s' "$tasks" | jq 'length')
  if [[ "$count" -eq 0 ]]; then
    echo "No overdue tasks."
  else
    echo "OVERDUE: $count task(s)"
    printf '%s' "$tasks" | _format_tasks
  fi
}

cmd_due_today() {
  local tasks
  tasks=$(_fetch_all "/tasks/filter" "query=today") || return 1
  local count
  count=$(printf '%s' "$tasks" | jq 'length')
  if [[ "$count" -eq 0 ]]; then
    echo "No tasks due today."
  else
    echo "DUE TODAY: $count task(s)"
    printf '%s' "$tasks" | _format_tasks
  fi
}

cmd_due_soon() {
  local days="3"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --days) days="\${2:?--days requires a number}"; shift 2 ;;
      *) days="$1"; shift ;;
    esac
  done
  local encoded
  encoded=$(jq -rn --arg q "due before: +\${days} days" '$q|@uri')
  local tasks
  tasks=$(_fetch_all "/tasks/filter" "query=$encoded") || return 1
  local count
  count=$(printf '%s' "$tasks" | jq 'length')
  if [[ "$count" -eq 0 ]]; then
    echo "No tasks due in the next $days day(s)."
  else
    echo "DUE SOON ($days days): $count task(s)"
    printf '%s' "$tasks" | _format_tasks
  fi
}

cmd_activity() {
  local count="20"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --count) count="\${2:?--count requires a number}"; shift 2 ;;
      *) count="$1"; shift ;;
    esac
  done
  # Single page fetch — limit controls total results, not page size
  local resp
  resp=$(_curl "$API/activities?limit=$count") || { echo "tasks: API request failed" >&2; return 1; }
  printf '%s' "$resp" | jq '.results' | _sanitize
}

case "\${1:-}" in
  overdue)   cmd_overdue ;;
  due-today) cmd_due_today ;;
  due-soon)  shift; cmd_due_soon "$@" ;;
  activity)  shift; cmd_activity "$@" ;;
  -h|--help|help|"") usage ;;
  *) echo "tasks: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
