/**
 * Todoist tool wrapper generator - task tracking via Todoist API v1.
 *
 * Supports two auth modes:
 * 1. Credential proxy (CRED_PROXY_URL) - token never enters container
 * 2. Direct API token (TODOIST_API_KEY) - fallback when no proxy
 */

export function generateTodoistTool(): string {
  return `#!/usr/bin/env bash
# todoist - task tracking via Todoist API v1
# Generated by ClawHQ
#
# Commands:
#   list [--project ID]            List active tasks (JSON)
#   today                          List tasks due today (JSON)
#   add <content> [--project ID]   Add a task
#   complete <id>                  Complete a task
#   update <id> <content>          Update task content
#   comment <id> <text>            Add comment to task
#   comments <id>                  List comments on task (JSON)
#   projects                       List projects (JSON)
#   get <id>                       Get task details (JSON)
set -euo pipefail

# Auth: prefer credential proxy, fall back to direct token
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/todoist"
  _curl() { curl -sS "$@"; }
else
  API="https://api.todoist.com/api/v1"
  TOKEN="\${TODOIST_API_KEY:?Set TODOIST_API_KEY or CRED_PROXY_URL}"
  _curl() { curl -sS -H "Authorization: Bearer $TOKEN" "$@"; }
fi

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  list)
    project="\${1:-}"
    if [[ -n "$project" ]]; then
      _curl "$API/tasks?project_id=$project"
    else
      _curl "$API/tasks"
    fi
    ;;
  today)
    _curl "$API/tasks?filter=today"
    ;;
  add)
    content="\${1:?Usage: todoist add <content> [--project ID]}"
    project="\${2:-}"
    if [[ -n "$project" ]]; then
      body=$(jq -n --arg c "$content" --arg p "$project" '{content: $c, project_id: $p}')
    else
      body=$(jq -n --arg c "$content" '{content: $c}')
    fi
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/tasks"
    ;;
  complete)
    id="\${1:?Usage: todoist complete <id>}"
    _curl -X POST "$API/tasks/$id/close"
    echo '{"status":"completed","id":"'"$id"'"}'
    ;;
  update)
    id="\${1:?Usage: todoist update <id> <content>}"
    content="\${2:?Usage: todoist update <id> <content>}"
    body=$(jq -n --arg c "$content" '{content: $c}')
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/tasks/$id"
    ;;
  comment)
    id="\${1:?Usage: todoist comment <id> <text>}"
    text="\${2:?Usage: todoist comment <id> <text>}"
    body=$(jq -n --arg c "$text" --arg t "$id" '{task_id: $t, content: $c}')
    _curl -X POST -H "Content-Type: application/json" -d "$body" "$API/comments"
    ;;
  comments)
    id="\${1:?Usage: todoist comments <id>}"
    _curl "$API/comments?task_id=$id"
    ;;
  projects)
    _curl "$API/projects"
    ;;
  get)
    id="\${1:?Usage: todoist get <id>}"
    _curl "$API/tasks/$id"
    ;;
  help|--help|-h|"")
    sed -n '2,14p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "todoist: unknown command '$cmd'" >&2
    sed -n '2,14p' "$0" | sed 's/^# \\?//' >&2
    exit 1
    ;;
esac
`;
}
