/**
 * Todoist-sync tool wrapper generator — task alerts and reminders.
 *
 * Generates a bash script that uses the Todoist Sync API for
 * deadline alerts, overdue detection, and follow-up reminders.
 * API token comes from TODOIST_API_TOKEN environment variable.
 */

export function generateTodoistSyncTool(): string {
  return `#!/usr/bin/env bash
# todoist-sync — task deadline alerts and follow-up reminders
# Generated by ClawHQ from blueprint config
# Auth header injected by credential proxy — token never in this container.
set -euo pipefail

# Credential proxy injects Authorization header; tool never sees the token.
PROXY="\${CRED_PROXY_URL:?CRED_PROXY_URL not set — credential proxy not configured}"
API="\${PROXY}/todoist-sync"
# REST API tasks also go through the proxy (todoist route).
REST_API="\${PROXY}/todoist"

usage() {
  cat <<'USAGE'
Usage: todoist-sync <command> [args]

Commands:
  overdue                       List overdue tasks
  due-today                     List tasks due today
  due-soon [--days N]           List tasks due within N days (default: 3)
  activity [--count N]          Recent activity log (default: 20)
  sync                          Full sync — fetch latest state
USAGE
}

sync_request() {
  local resource_types="$1"
  curl -sS -X POST "$API/sync" \\
    -H "Content-Type: application/x-www-form-urlencoded" \\
    -d "sync_token=*&resource_types=[\\"$resource_types\\"]"
}

cmd_overdue() {
  TODOIST_REST_API="$REST_API" python3 -c "
import json, os, subprocess
from datetime import datetime, timezone

rest_api = os.environ['TODOIST_REST_API']
result = subprocess.run(
    ['curl', '-sS', rest_api + '/tasks'],
    capture_output=True, text=True
)
tasks = json.loads(result.stdout)
now = datetime.now(timezone.utc)
for t in tasks:
    due = t.get('due')
    if due and due.get('date'):
        due_date = datetime.fromisoformat(due['date'].replace('Z', '+00:00'))
        if hasattr(due_date, 'tzinfo') and due_date.tzinfo is None:
            from datetime import date
            if isinstance(due_date, datetime):
                due_date = due_date.replace(tzinfo=timezone.utc)
        if due_date.date() < now.date() if hasattr(due_date, 'date') else True:
            print(f'OVERDUE: {t[\"content\"]} (due: {due[\"date\"]})')
"
}

cmd_due_today() {
  TODOIST_REST_API="$REST_API" python3 -c "
import json, os, subprocess
from datetime import date

rest_api = os.environ['TODOIST_REST_API']
result = subprocess.run(
    ['curl', '-sS', rest_api + '/tasks'],
    capture_output=True, text=True
)
tasks = json.loads(result.stdout)
today = date.today().isoformat()
for t in tasks:
    due = t.get('due')
    if due and due.get('date', '').startswith(today):
        print(f'{t[\"content\"]} (due: {due[\"date\"]})')
"
}

cmd_due_soon() {
  local days="\${1:-3}"
  TODOIST_REST_API="$REST_API" DUE_DAYS="$days" python3 -c "
import json, os, subprocess
from datetime import date, timedelta

rest_api = os.environ['TODOIST_REST_API']
days = int(os.environ['DUE_DAYS'])
result = subprocess.run(
    ['curl', '-sS', rest_api + '/tasks'],
    capture_output=True, text=True
)
tasks = json.loads(result.stdout)
cutoff = (date.today() + timedelta(days=days)).isoformat()
today = date.today().isoformat()
for t in tasks:
    due = t.get('due')
    if due and due.get('date'):
        d = due['date'][:10]
        if today <= d <= cutoff:
            print(f'{t[\"content\"]} (due: {due[\"date\"]})')
"
}

cmd_activity() {
  local count="\${1:-20}"
  curl -sS "$API/activity/get?limit=$count"
}

cmd_sync() {
  sync_request "items"
}

case "\${1:-}" in
  overdue)   cmd_overdue ;;
  due-today) cmd_due_today ;;
  due-soon)  shift; cmd_due_soon "\${1:-3}" ;;
  activity)  shift; cmd_activity "\${1:-20}" ;;
  sync)      cmd_sync ;;
  -h|--help|help|"") usage ;;
  *) echo "todoist-sync: unknown command '$1'" >&2; usage >&2; exit 1 ;;
esac
`;
}
