/**
 * 1Password vault tool wrapper generator — op CLI via credential proxy.
 *
 * Routes through cred-proxy /op prefix, fallback to op CLI with
 * OP_SERVICE_ACCOUNT_TOKEN. Subcommands: get, list. Read-only, never write.
 *
 * Auth: credential proxy (preferred) or direct op CLI fallback.
 */

export function generateVaultTool(): string {
  return `#!/usr/bin/env bash
# vault - 1Password secret retrieval (read-only)
# Generated by ClawHQ
# Read-only — never writes to the vault. Secrets are fetched at use time,
# never stored in LLM context or logged.
#
# Commands:
#   get <vault> <item> [field]       Get a secret (field defaults to "password")
#   list <vault>                     List items in a vault (titles only, no secrets)
set -euo pipefail

# Auth: prefer credential proxy, fall back to op CLI
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/op"
  _get_item() {
    local vault="\$1" item="\$2" field="\${3:-password}"
    curl -sS "\$API/v1/vaults/\$vault/items/\$item?fields=\$field"
  }
  _list_items() {
    local vault="\$1"
    curl -sS "\$API/v1/vaults/\$vault/items"
  }
else
  : "\${OP_SERVICE_ACCOUNT_TOKEN:?Set OP_SERVICE_ACCOUNT_TOKEN or CRED_PROXY_URL}"
  _get_item() {
    local vault="\$1" item="\$2" field="\${3:-password}"
    op item get "\$item" --vault "\$vault" --fields "\$field" --format json 2>/dev/null
  }
  _list_items() {
    local vault="\$1"
    op item list --vault "\$vault" --format json 2>/dev/null
  }
fi

cmd="\${1:-help}"
shift 2>/dev/null || true

case "\$cmd" in
  get)
    vault="\${1:?Usage: vault get <vault> <item> [field]}"
    item="\${2:?Usage: vault get <vault> <item> [field]}"
    field="\${3:-password}"
    _get_item "\$vault" "\$item" "\$field"
    ;;
  list)
    vault="\${1:?Usage: vault list <vault>}"
    _list_items "\$vault"
    ;;
  help|--help|-h|"")
    sed -n '2,10p' "\$0" | sed 's/^# \\\\?//'
    ;;
  *)
    echo "vault: unknown command '\$cmd'" >&2
    exit 1
    ;;
esac
`;
}
