/**
 * X/Twitter tool wrapper generator — read-only Twitter API v2 scanner.
 *
 * Routes through cred-proxy /x prefix, fallback to X_BEARER_TOKEN.
 * Subcommands: search, timeline, user. All results piped through
 * sanitize. Read-only only — no posting via this tool.
 *
 * Auth: credential proxy (preferred) or direct X_BEARER_TOKEN fallback.
 */

export function generateXTool(): string {
  return `#!/usr/bin/env bash
# x - X/Twitter read-only scanner via Twitter API v2
# Generated by ClawHQ
# Read-only — no posting via this tool. All results piped through ClawWall.
#
# Commands:
#   search <query>                   Search recent tweets (JSON)
#   timeline <user_id>               Get user timeline (JSON)
#   user <username>                  Look up user by username (JSON)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Help works without credentials
case "\${1:-}" in help|--help|-h|"")
  sed -n '2,9p' "$0" | sed 's/^# \\?//'
  exit 0 ;; esac

# Auth: prefer credential proxy, fall back to direct token
if [[ -n "\${CRED_PROXY_URL:-}" ]]; then
  API="\${CRED_PROXY_URL}/x"
  _curl() { curl -sS --fail-with-body "$@"; }
else
  API="https://api.twitter.com/2"
  TOKEN="\${X_BEARER_TOKEN:?Set X_BEARER_TOKEN or CRED_PROXY_URL}"
  _curl() { curl -sS --fail-with-body -H "Authorization: Bearer $TOKEN" "$@"; }
fi

# ClawWall: sanitize external content
_sanitize() {
  if [[ -x "$SCRIPT_DIR/sanitize" ]]; then
    "$SCRIPT_DIR/sanitize" --source x --log
  else
    cat
  fi
}

cmd="\${1:-help}"
shift 2>/dev/null || true

case "$cmd" in
  search)
    query="\${*:?Usage: x search <query>}"
    encoded=$(jq -rn --arg q "$query" '$q | @uri')
    _curl "$API/tweets/search/recent?query=$encoded&max_results=10&tweet.fields=created_at,author_id,public_metrics" | _sanitize
    ;;
  timeline)
    user_id="\${1:?Usage: x timeline <user_id>}"
    _curl "$API/users/$user_id/tweets?max_results=10&tweet.fields=created_at,public_metrics" | _sanitize
    ;;
  user)
    username="\${1:?Usage: x user <username>}"
    _curl "$API/users/by/username/$username?user.fields=description,public_metrics,created_at" | _sanitize
    ;;
  help|--help|-h|"")
    sed -n '2,9p' "$0" | sed 's/^# \\?//'
    ;;
  *)
    echo "x: unknown command '$cmd'" >&2
    exit 1
    ;;
esac
`;
}
