/**
 * Credential proxy server script generator.
 *
 * Generates a self-contained Node.js HTTP proxy script that runs inside
 * the cred-proxy Docker sidecar. The script:
 *   1. Reads routes.json at startup
 *   2. Listens for HTTP requests from the agent container
 *   3. Matches requests to routes by path prefix
 *   4. Injects credentials (from env vars) into the forwarded request
 *   5. Forwards to the upstream API
 *   6. Returns the upstream response
 *   7. Appends audit log entry for every proxied request
 *
 * The generated script uses only Node.js built-ins (http, https, fs, path)
 * so the sidecar container needs no npm install.
 */

/** Generate the complete proxy server Node.js script. */
export function generateProxyServerScript(): string {
  return `#!/usr/bin/env node
"use strict";

/**
 * ClawHQ Credential Proxy — host-side token proxy.
 *
 * Secrets never enter the agent container. Tool wrappers call this proxy,
 * which injects credentials and forwards to upstream APIs.
 *
 * Generated by ClawHQ. Do not edit manually.
 */

const http = require("http");
const https = require("https");
const fs = require("fs");
const path = require("path");
const { URL } = require("url");

// ── Config ────────────────────────────────────────────────────────────────

const ROUTES_PATH = process.env.CRED_PROXY_ROUTES || "/app/routes.json";
const AUDIT_LOG_PATH = process.env.CRED_PROXY_AUDIT_LOG || "/app/audit/proxy-audit.jsonl";
const MAX_BODY_BYTES = 10 * 1024 * 1024; // 10 MB

let routesConfig;
try {
  routesConfig = JSON.parse(fs.readFileSync(ROUTES_PATH, "utf-8"));
} catch (err) {
  console.error(\`[cred-proxy] Failed to load routes from \${ROUTES_PATH}: \${err.message}\`);
  process.exit(1);
}

const HOST = routesConfig.host || "0.0.0.0";
const PORT = routesConfig.port || 9876;
const routes = (routesConfig.routes || []).map(function(r) {
  // Resolve "env:VAR_NAME" upstream references from environment
  if (r.upstream && r.upstream.startsWith("env:")) {
    const envVar = r.upstream.slice(4);
    const resolved = process.env[envVar];
    if (resolved) {
      return Object.assign({}, r, { upstream: resolved });
    }
    console.warn(\`[cred-proxy] Route \${r.id}: env:\${envVar} not set — route disabled\`);
    return null;
  }
  return r;
}).filter(Boolean);

// Sort longest prefix first for greedy matching
routes.sort(function(a, b) { return b.pathPrefix.length - a.pathPrefix.length; });

console.log(\`[cred-proxy] Loaded \${routes.length} route(s) from \${ROUTES_PATH}\`);
for (const r of routes) {
  const envLabel = r.auth.type === "basic"
    ? \`\${r.auth.userEnvVar}+\${r.auth.passEnvVar}\`
    : r.auth.type === "none" ? "none" : r.auth.envVar;
  console.log(\`  \${r.pathPrefix} → \${r.upstream} (auth: \${r.auth.type}, env: \${envLabel})\`);
}

// ── Audit Logging ─────────────────────────────────────────────────────────

function ensureAuditDir() {
  const dir = path.dirname(AUDIT_LOG_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function auditLog(entry) {
  try {
    ensureAuditDir();
    fs.appendFileSync(AUDIT_LOG_PATH, JSON.stringify(entry) + "\\n");
  } catch {
    // Best-effort — audit logging never disrupts the proxy
  }
}

// ── Request Body Reader ───────────────────────────────────────────────────

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        reject(new Error("Request body too large"));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

// ── Route Matching ────────────────────────────────────────────────────────

function matchRoute(urlPath) {
  for (const route of routes) {
    if (urlPath === route.pathPrefix || urlPath.startsWith(route.pathPrefix + "/")) {
      return route;
    }
  }
  return null;
}

// ── Credential Injection ──────────────────────────────────────────────────

function injectCredential(route, headers, bodyBuffer) {
  const auth = route.auth;

  // No-auth routes (public APIs routed through proxy for egress control)
  if (auth.type === "none") {
    return { headers, body: bodyBuffer, injected: true };
  }

  // Basic auth — user:pass base64-encoded
  if (auth.type === "basic") {
    const user = process.env[auth.userEnvVar] || "";
    const pass = process.env[auth.passEnvVar] || "";
    if (!user) {
      return { headers, body: bodyBuffer, injected: false };
    }
    headers["authorization"] = "Basic " + Buffer.from(user + ":" + pass).toString("base64");
    return { headers, body: bodyBuffer, injected: true };
  }

  const credValue = process.env[auth.envVar];
  if (!credValue) {
    return { headers, body: bodyBuffer, injected: false };
  }

  if (auth.type === "header") {
    const headerValue = (auth.prefix || "") + credValue;
    headers[auth.header.toLowerCase()] = headerValue;
    return { headers, body: bodyBuffer, injected: true };
  }

  if (auth.type === "body-json-field") {
    try {
      const bodyStr = bodyBuffer.toString("utf-8");
      const bodyObj = bodyStr.length > 0 ? JSON.parse(bodyStr) : {};
      bodyObj[auth.field] = credValue;
      const newBody = Buffer.from(JSON.stringify(bodyObj));
      headers["content-length"] = String(newBody.length);
      return { headers, body: newBody, injected: true };
    } catch {
      // If body isn't valid JSON, forward as-is without injection
      return { headers, body: bodyBuffer, injected: false };
    }
  }

  return { headers, body: bodyBuffer, injected: false };
}

// ── Upstream Forwarding ───────────────────────────────────────────────────

function forwardRequest(route, req, bodyBuffer, injectedHeaders) {
  return new Promise((resolve, reject) => {
    // Strip the route path prefix to get the upstream path
    const remainingPath = req.url.slice(route.pathPrefix.length) || "";
    // Concatenate upstream base + remaining path (URL constructor discards
    // base path when given an absolute path like "/tasks")
    const base = route.upstream.replace(/\\/+$/, "");
    const upstreamUrl = new URL(base + remainingPath);

    const mod = upstreamUrl.protocol === "https:" ? https : http;

    // Copy original headers, apply injected ones
    const fwdHeaders = { ...injectedHeaders };
    // Set host to upstream
    fwdHeaders["host"] = upstreamUrl.host;
    // Remove hop-by-hop headers
    delete fwdHeaders["connection"];
    delete fwdHeaders["transfer-encoding"];

    const opts = {
      hostname: upstreamUrl.hostname,
      port: upstreamUrl.port || (upstreamUrl.protocol === "https:" ? 443 : 80),
      path: upstreamUrl.pathname + upstreamUrl.search,
      method: req.method,
      headers: fwdHeaders,
      timeout: 60000,
    };

    const upstream = mod.request(opts, (res) => {
      // Follow 3xx redirects within the same upstream domain (re-inject auth)
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume(); // drain response
        try {
          const loc = new URL(res.headers.location, upstreamUrl.href);
          if (loc.hostname === upstreamUrl.hostname) {
            // Same domain redirect — follow with auth preserved
            const redirectReq = Object.assign({}, req, {
              url: route.pathPrefix + loc.pathname + loc.search,
            });
            resolve(forwardRequest(route, redirectReq, bodyBuffer, injectedHeaders));
            return;
          }
        } catch { /* invalid URL — fall through to return the redirect */ }
      }
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => {
        resolve({
          statusCode: res.statusCode,
          headers: res.headers,
          body: Buffer.concat(chunks),
        });
      });
    });

    upstream.on("error", reject);
    upstream.on("timeout", () => {
      upstream.destroy(new Error("Upstream timeout"));
    });

    if (bodyBuffer.length > 0) {
      upstream.write(bodyBuffer);
    }
    upstream.end();
  });
}

// ── Health Endpoint ───────────────────────────────────────────────────────

function handleHealth(res) {
  const routeStatus = routes.map((r) => ({
    id: r.id,
    pathPrefix: r.pathPrefix,
    upstream: r.upstream,
    credConfigured: r.auth.type === "none" ? true
      : r.auth.type === "basic" ? !!(process.env[r.auth.userEnvVar])
      : !!process.env[r.auth.envVar],
  }));

  const body = JSON.stringify({
    status: "ok",
    routes: routeStatus,
    uptime: process.uptime(),
  });

  res.writeHead(200, { "content-type": "application/json" });
  res.end(body);
}

// ── Server ────────────────────────────────────────────────────────────────

const server = http.createServer(async (req, res) => {
  // Health check endpoint
  if (req.url === "/health" && req.method === "GET") {
    handleHealth(res);
    return;
  }

  const startTime = Date.now();
  const route = matchRoute(req.url);

  if (!route) {
    res.writeHead(404, { "content-type": "application/json" });
    res.end(JSON.stringify({ error: "No matching proxy route", path: req.url }));
    return;
  }

  try {
    const bodyBuffer = await readBody(req);

    // Build forwarding headers from original request
    const fwdHeaders = {};
    for (const [key, value] of Object.entries(req.headers)) {
      fwdHeaders[key] = value;
    }

    // Inject credential
    const injected = injectCredential(route, fwdHeaders, bodyBuffer);

    // Forward to upstream
    const upstream = await forwardRequest(route, req, injected.body, injected.headers);
    const durationMs = Date.now() - startTime;

    // Audit log
    auditLog({
      ts: new Date().toISOString(),
      routeId: route.id,
      method: req.method,
      upstream: route.upstream + (req.url.slice(route.pathPrefix.length) || "/"),
      statusCode: upstream.statusCode,
      durationMs,
      credInjected: injected.injected,
    });

    // Return upstream response to caller
    const responseHeaders = { ...upstream.headers };
    // Remove hop-by-hop headers from response
    delete responseHeaders["connection"];
    delete responseHeaders["transfer-encoding"];

    res.writeHead(upstream.statusCode, responseHeaders);
    res.end(upstream.body);
  } catch (err) {
    const durationMs = Date.now() - startTime;

    auditLog({
      ts: new Date().toISOString(),
      routeId: route.id,
      method: req.method,
      upstream: route.upstream,
      statusCode: 502,
      durationMs,
      credInjected: false,
    });

    res.writeHead(502, { "content-type": "application/json" });
    res.end(JSON.stringify({ error: "Upstream request failed", detail: err.message }));
  }
});

server.listen(PORT, HOST, () => {
  console.log(\`[cred-proxy] Listening on \${HOST}:\${PORT}\`);
});

// Graceful shutdown
process.on("SIGTERM", () => {
  console.log("[cred-proxy] Shutting down…");
  server.close(() => process.exit(0));
});

process.on("SIGINT", () => {
  console.log("[cred-proxy] Interrupted, shutting down…");
  server.close(() => process.exit(0));
});
`;
}
